### PR TITLE
Drop Windows CE support.

### PR DESCRIPTION
**Pull request by bob-beck**
Windows CE has been out of mainstream support since 2018 and will not have a modern toolchain capable of compiling a modern OpenSSL.

The vc_wince_info Perl helper, the crypto/LPdir_wince.c directory backend, and a long tail of _WIN32_WCE
 / OPENSSL_SYS_WINCE guards across the Windows code paths are pulled out.

Spotted by idrassi while reviewing https://github.com/openssl/openssl/pull/31580

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by bob-beck** [comment]
drat, I broke this moving it.  wait a bit

**Comment by bob-beck** [comment]
yeah broken rebase to master.. fixed.

**Comment by nhorman** [comment]
I'm all for doing this, but I have to ask, do we know if Windows CE is still buildable on master?  If it is, it might suck if we pull the rug out from under any active users.

On the other hand, if its no buildable (i expect it isn't), then yeah, out it goes.

**Review by simo5 — DISMISSED** [review]
LGTM

**Comment by bob-beck** [comment]
Amusingly the nanny didn't think this needed a CHANGES entry, when, IMO, it does.

**Review by simo5 — DISMISSED** [review]

**Comment by idrassi** [comment]
@nhorman 12 years ago I worked on porting OpenSSL 0.9.8y to Windows CE for a customer and I still have the build VM.
The build environment uses Windows Embedded Compact 2013 and Visual Studio 2013.

So, I gave it a try with the codebase from master. The build hit a hard blocker because of compiler error: 

```
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(294) : error C2143: syntax error : missing ';' before
  'const'
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(297) : error C2065: 'p' : undeclared identifier
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(297) : warning C4047: '=' : 'int' differs in levels of indirection from 'const OSSL_PARAM *'
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(304) : error C2065: 'p' : undeclared identifier
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(304) : warning C4047: '!=' : 'int' differs in levels of indirection from 'void *'
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(304) : warning C4047: 'function' : 'const OSSL_PARAM *' differs in levels of indirection from 'int'
  ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(304) : warning C4024: 'OSSL_PARAM_get_octet_ptr' : different types for formal and actual parameter 1
  NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\x86_ARM\cl.EXE"' : return code '0x2'
```

So it looks like current master is not compatible with Windows CE build and probably also not compatible with VS 2013 since this is the compiler used (although it is for arm).

For reference, the explicit Configure command I used for that build was:

```
perl C:\dev\libraries\openssl_master\Configure VC-CE ^
  no-async no-dso no-dsa no-ikev2kdf no-asm no-shared no-apps no-tests ^
  --prefix=C:\dev\libraries\openssl_master_wec2013_install ^
  --openssldir=C:\dev\libraries\openssl_master_wec2013_install\ssl
```

The compiler is initialized with:

`call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_arm`

and the generated makefile has:

```
CC="cl"
CFLAGS=/W3 /wd4090 /nologo /O1i
CNF_CFLAGS=/GF /Gy  /MT
LIB_CFLAGS=/Z7 $(CNF_CFLAGS) $(CFLAGS)
```

**Comment by t8m** [comment]
I do not think we are buildable for Win CE for quite some time. IMO removing the support is not a breaking change then.

**Review by nhorman — DISMISSED** [review]

**Comment by esyr** [comment]
> ..\openssl_master\providers\implementations\keymgmt\ec_kmgmt.c(294) : error C2143: syntax error : missing ';' before 'const'

This one is because of a middle-of-a-block variable definition, introduced in c13e46f20441 "Add a newdata_ex function which takes params and use it" (`openssl-4.0.0-alpha1~344`).

**Review by t8m — APPROVED** [review]

**Review by npajkovsky — APPROVED** [review]
crypto/LPdir_wince.c seems to be unused now.

**Comment by jogme** [comment]
Merged. Thanks!

**Comment by jogme** [comment]
@npajkovsky created https://github.com/openssl/openssl/pull/31718 for removing `crypto/LPdir_wince.c `
