### PR TITLE
Defined out MUTEX attributes not available on NonStop SPT Threads.

### LINKED ISSUE #15885: OpenSSL-3.0.0-beta1 compile breaks under Standard Posix Threads (NonStop)
The definitions associated with the change at lines 60-64 in `crypto/threads_pthread.c` are not defined for all Standard Posix Thread (SPT) implementations.

https://github.com/openssl/openssl/blob/86ff7cf2a6cdf26f2ba7e64db6fe5c92c64bf9ac/crypto/threads_pthread.c#L60-L64

In particular, `PTHREAD_MUTEX_NORMAL` is undefined. I will look into fixing this ASAP.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Standard Posix Threads (SPT) Threads are an older separate branch of
pthreads that do not support some of the capabilities in the current
Posix User Threads (PUT).

Fixes #15885

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

**Comment by rsbeckerca** [comment]
I moved this back from WIP as this fix does solve the two compile issues that showed up. The SPT build is currently under test. If any issues come up, I will open a new case for the specifics after whatever analysis is needed.

File: crypto/store/store_lib.c [hunk 1]
```diff
@@ -513,7 +513,14 @@ static int ossl_store_close_it(OSSL_STORE_CTX *ctx)
         ret = ctx->loader->p_close(ctx->loader_ctx);
 #ifndef OPENSSL_NO_DEPRECATED_3_0
     if (ctx->fetched_loader == NULL)
+# if defined (OPENSSL_TANDEM_FLOSS) && defined (_SPT_MODEL_)
```
Comment (paulidale) [inline crypto/store/store_lib.c:516]: This would be better sited up the top of the file.  There are no calls to `close(2)` in this file.

File: crypto/store/store_lib.c [hunk 2]
```diff
@@ -513,7 +513,14 @@ static int ossl_store_close_it(OSSL_STORE_CTX *ctx)
...
+   /* NonStop SPT redirects close to spt_close causing a compile failure. */
+#  undef close
+# endif
         ret = ctx->loader->close(ctx->loader_ctx);
+# if defined (OPENSSL_TANDEM_FLOSS) && defined (_SPT_MODEL_)
```
Comment (paulidale) [inline crypto/store/store_lib.c:521]: There is no need for this at all.  `close(2)` is never calls.

**Review by paulidale — CHANGES_REQUESTED** [review]

File: crypto/store/store_lib.c (hunk 1 above)
Comment (levitte) [reply crypto/store/store_lib.c:516]: Uhmm @paulidale, a couple of lines down, you have this:

``` C
         ret = ctx->loader->close(ctx->loader_ctx);
```

Comment (paulidale) [reply crypto/store/store_lib.c:516]: I know, it's just that this kind of rewriting is out of place here.  Also so the fix up afterwards.

Since there is no other instance of the word _close_ in this file, it doesn't hurt to fix this up the top with an explanatory comment.  That where this kind of kludge is oft put.

Comment (levitte) [reply crypto/store/store_lib.c:516]: Yes, I agree that it's a bit misplaced, and also that the re-definition after isn't necessary

Comment (levitte) [reply crypto/store/store_lib.c:516]: ... and now that I've re-read your first review comment...  I read it differently half an hour ago, so never mind my blabbering.

Comment (levitte) [reply crypto/store/store_lib.c:516]: (I may need more coffee... yeah, that's probably it)

Comment (paulidale) [reply crypto/store/store_lib.c:516]: or more sleep :wink:

File: crypto/threads_pthread.c [hunk 3]
```diff
@@ -57,10 +57,14 @@ CRYPTO_RWLOCK *CRYPTO_THREAD_lock_new(void)
      * We don't use recursive mutexes, but try to catch errors if we do.
      */
     pthread_mutexattr_init(&attr);
-#  if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
+#  if defined (__TANDEM) && defined (_SPT_MODEL_)
+    /* SPT does not define MUTEX attributes. */
+#  else
```
Comment (t8m) [inline crypto/threads_pthread.c:62]: Why not `if !defined (__TANDEM) || !defined (_SPT_MODEL_)` and drop the else?

File: crypto/store/store_lib.c (hunk 1 above)
Comment (t8m) [reply crypto/store/store_lib.c:516]: also why not just `# if defined(close)` ? (but keep the comment of course)

File: crypto/threads_pthread.c (hunk 3 above)
Comment (richsalz) [reply crypto/threads_pthread.c:62]: Why not make it more general and use only `ifdef PTHREAD_MUTEX_xxx` as appropriate?

**Comment by richsalz** [comment]
This set of changes is kinda gross for a non-supported platform during the beta phase.

**Comment by t8m** [comment]
> This set of changes is kinda gross for a non-supported platform during the beta phase.

Is it really non-supported? It is a secondary platform, yes, but I would not call that non-supported.

**Comment by paulidale** [comment]
I don't consider this somewhat exotic platform to be project supported.  I.e. it's not primary or secondary as per policy.

**Comment by rsbeckerca** [comment]
> 
> 
> I don't consider this somewhat exotic platform to be project supported. I.e. it's not primary or secondary as per policy.

I'm not sure this discussion belongs here, but I'm wondering why I am putting the effort in, following the discussion I had with the team in the 1.1.x timeframe to bring NonStop back into support (looking for it but it's on an old computer). The consideration was to have a designated person (me as part of my team) who would provide ongoing testing and modification support for the platform. NonStop, while an MPP architecture, is a currently supported platform, by Hewlett Packard Enterprises in a large number of financial, manufacturing, and telco data centres. It is not, nor are there plans, to move the x86 variant operating system to a community supported platform. I have a backup in this activity in case I am unable to continue this role. So if the requirement changes, how can this be rectified? I don't think a simple "Well GitHub doesn't support it" is a sufficient decision point.

File: crypto/store/store_lib.c (hunk 2 above)
Comment (rsbeckerca) [reply crypto/store/store_lib.c]: > 
> 
> There is no need for this at all. `close(2)` is never called here.

The textual `close` is replaced by the c99 preprocessor with `spt_close` by virtue of matching the macro's structure.

**Comment by t8m** [comment]
Regardless of whether supported or unsupported, given the substantial effort @rsbeckerca spends testing and ensuring the NonStop works with 3.0, I think his work deserves attention and fixes (if approved) being merged before the final release.

File: crypto/store/store_lib.c (hunk 1 above)
Comment (rsbeckerca) [reply crypto/store/store_lib.c]: I have used the suggestion @t8m made, being the simplest to do and understand.

File: crypto/threads_pthread.c [hunk 4]
```diff
@@ -57,10 +57,14 @@ CRYPTO_RWLOCK *CRYPTO_THREAD_lock_new(void)
...
+#   if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_ERRORCHECK);
-# else
+#   else
```
Comment (t8m) [inline crypto/threads_pthread.c:65]: Yep, better alternative would be to do here: `# elif defined(PTHREAD_MUTEX_NORMAL)`

**Comment by t8m** [comment]
The build failure on Windows is _interesting_ and meaning that we have the same redefinition of close on Windows as well although it somehow applies to the declaration as well and so it does not break the build. Hmm, the proper fix might be to rename the close member of the struct to something less overloaded.

File: crypto/store/store_lib.c (hunk 1 above)
Comment (t8m) [reply crypto/store/store_lib.c]: Unfortunately this breaks the Windows build. A proper thing would be to rename the structure member as we have this redefinition on Windows as well but it apparently applies in the headers declaring the struct as well which for some reason does not on NonStop.

File: crypto/threads_pthread.c (hunk 4 above)
Comment (rsbeckerca) [reply crypto/threads_pthread.c]: @t8m Please have a look at my proposed revision.

**Comment by rsbeckerca** [comment]
> 
> 
> The build failure on Windows is _interesting_ and meaning that we have the same redefinition of close on Windows as well although it somehow applies to the declaration as well and so it does not break the build. Hmm, the proper fix might be to rename the `close` member of the struct to something less overloaded.

I tend to agree. New issue or cover it here? Given that this is in the `OPENSSL_STORE_INFO`, the impact might be severe to others now at beta.

**Comment by mattcaswell** [comment]
> the impact might be severe to others now at beta.

I don't think so. The field name in the structure is entirely internal. The fix is relatively minimal:

```` diff
diff --git a/crypto/store/store_lib.c b/crypto/store/store_lib.c
index 4b31c6f7d5..56fb9a0239 100644
--- a/crypto/store/store_lib.c
+++ b/crypto/store/store_lib.c
@@ -513,7 +513,7 @@ static int ossl_store_close_it(OSSL_STORE_CTX *ctx)
         ret = ctx->loader->p_close(ctx->loader_ctx);
 #ifndef OPENSSL_NO_DEPRECATED_3_0
     if (ctx->fetched_loader == NULL)
-        ret = ctx->loader->close(ctx->loader_ctx);
+        ret = ctx->loader->closefn(ctx->loader_ctx);
 #endif
 
     sk_OSSL_STORE_INFO_pop_free(ctx->cached_info, OSSL_STORE_INFO_free);
diff --git a/crypto/store/store_local.h b/crypto/store/store_local.h
index 6aeaaa915f..8f817fd514 100644
--- a/crypto/store/store_local.h
+++ b/crypto/store/store_local.h
@@ -92,7 +92,7 @@ struct ossl_store_loader_st {
     OSSL_STORE_load_fn load;
     OSSL_STORE_eof_fn eof;
     OSSL_STORE_error_fn error;
-    OSSL_STORE_close_fn close;
+    OSSL_STORE_close_fn closefn;
     OSSL_STORE_open_ex_fn open_ex;
 #endif
 
diff --git a/crypto/store/store_register.c b/crypto/store/store_register.c
index dfb0cdc811..6fa7352ccd 100644
--- a/crypto/store/store_register.c
+++ b/crypto/store/store_register.c
@@ -130,7 +130,7 @@ int OSSL_STORE_LOADER_set_error(OSSL_STORE_LOADER *loader,
 int OSSL_STORE_LOADER_set_close(OSSL_STORE_LOADER *loader,
                                 OSSL_STORE_close_fn close_function)
 {
-    loader->close = close_function;
+    loader->closefn = close_function;
     return 1;
 }
 
@@ -185,7 +185,7 @@ int ossl_store_register_loader_int(OSSL_STORE_LOADER *loader)
 
     /* Check that functions we absolutely require are present */
     if (loader->open == NULL || loader->load == NULL || loader->eof == NULL
-        || loader->error == NULL || loader->close == NULL) {
+        || loader->error == NULL || loader->closefn == NULL) {
         ERR_raise(ERR_LIB_OSSL_STORE, OSSL_STORE_R_LOADER_INCOMPLETE);
         return 0;
     }
@@ -220,7 +220,7 @@ const OSSL_STORE_LOADER *ossl_store_get0_loader_int(const char *scheme)
     template.open = NULL;
     template.load = NULL;
     template.eof = NULL;
-    template.close = NULL;
+    template.closefn = NULL;
     template.open_ex = NULL;
 
     if (!RUN_ONCE(&registry_init, do_registry_init)) {
@@ -251,7 +251,7 @@ OSSL_STORE_LOADER *ossl_store_unregister_loader_int(const char *scheme)
     template.open = NULL;
     template.load = NULL;
     template.eof = NULL;
-    template.close = NULL;
+    template.closefn = NULL;
 
     if (!RUN_ONCE(&registry_init, do_registry_init)) {
         ERR_raise(ERR_LIB_OSSL_STORE, ERR_R_MALLOC_FAILURE);
````

**Comment by rsbeckerca** [comment]
> 
> 
> > the impact might be severe to others now at beta.
> 
> I don't think so. The field name in the structure is entirely internal. The fix is relatively minimal:
> 
> ```diff
> diff --git a/crypto/store/store_lib.c b/crypto/store/store_lib.c
> index 4b31c6f7d5..56fb9a0239 100644
> --- a/crypto/store/store_lib.c
> +++ b/crypto/store/store_lib.c
> @@ -513,7 +513,7 @@ static int ossl_store_close_it(OSSL_STORE_CTX *ctx)
>          ret = ctx->loader->p_close(ctx->loader_ctx);
>  #ifndef OPENSSL_NO_DEPRECATED_3_0
>      if (ctx->fetched_loader == NULL)
> -        ret = ctx->loader->close(ctx->loader_ctx);
> +        ret = ctx->loader->closefn(ctx->loader_ctx);
>  #endif
>  
>      sk_OSSL_STORE_INFO_pop_free(ctx->cached_info, OSSL_STORE_INFO_free);
> diff --git a/crypto/store/store_local.h b/crypto/store/store_local.h
> index 6aeaaa915f..8f817fd514 100644
> --- a/crypto/store/store_local.h
> +++ b/crypto/store/store_local.h
> @@ -92,7 +92,7 @@ struct ossl_store_loader_st {
>      OSSL_STORE_load_fn load;
>      OSSL_STORE_eof_fn eof;
>      OSSL_STORE_error_fn error;
> -    OSSL_STORE_close_fn close;
> +    OSSL_STORE_close_fn closefn;
>      OSSL_STORE_open_ex_fn open_ex;
>  #endif
>  
> diff --git a/crypto/store/store_register.c b/crypto/store/store_register.c
> index dfb0cdc811..6fa7352ccd 100644
> --- a/crypto/store/store_register.c
> +++ b/crypto/store/store_register.c
> @@ -130,7 +130,7 @@ int OSSL_STORE_LOADER_set_error(OSSL_STORE_LOADER *loader,
>  int OSSL_STORE_LOADER_set_close(OSSL_STORE_LOADER *loader,
>                                  OSSL_STORE_close_fn close_function)
>  {
> -    loader->close = close_function;
> +    loader->closefn = close_function;
>      return 1;
>  }
>  
> @@ -185,7 +185,7 @@ int ossl_store_register_loader_int(OSSL_STORE_LOADER *loader)
>  
>      /* Check that functions we absolutely require are present */
>      if (loader->open == NULL || loader->load == NULL || loader->eof == NULL
> -        || loader->error == NULL || loader->close == NULL) {
> +        || loader->error == NULL || loader->closefn == NULL) {
>          ERR_raise(ERR_LIB_OSSL_STORE, OSSL_STORE_R_LOADER_INCOMPLETE);
>          return 0;
>      }
> @@ -220,7 +220,7 @@ const OSSL_STORE_LOADER *ossl_store_get0_loader_int(const char *scheme)
>      template.open = NULL;
>      template.load = NULL;
>      template.eof = NULL;
> -    template.close = NULL;
> +    template.closefn = NULL;
>      template.open_ex = NULL;
>  
>      if (!RUN_ONCE(&registry_init, do_registry_init)) {
> @@ -251,7 +251,7 @@ OSSL_STORE_LOADER *ossl_store_unregister_loader_int(const char *scheme)
>      template.open = NULL;
>      template.load = NULL;
>      template.eof = NULL;
> -    template.close = NULL;
> +    template.closefn = NULL;
>  
>      if (!RUN_ONCE(&registry_init, do_registry_init)) {
>          ERR_raise(ERR_LIB_OSSL_STORE, ERR_R_MALLOC_FAILURE);
> ```

I can include this in my PR or separate it out. Your call, please.

**Comment by mattcaswell** [comment]
> I can include this in my PR or separate it out. Your call, please.

Just include it here.

File: crypto/store/store_lib.c (hunk 2 above)
Comment (rsbeckerca) [reply crypto/store/store_lib.c]: Field has been renamed to `closefn`, so this change goes away.

**Comment by rsbeckerca** [comment]
There appears to be a memory leak detected in the non-caching build, but I don't think it is a result of my changes.

File: crypto/threads_pthread.c [hunk 5]
```diff
@@ -58,9 +58,13 @@ CRYPTO_RWLOCK *CRYPTO_THREAD_lock_new(void)
...
     pthread_mutexattr_init(&attr);
 #  if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
+#   if defined(PTHREAD_MUTEX_ERRORCHECK)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_ERRORCHECK);
-# else
+#   endif
+#  else
+#   if defined(PTHREAD_MUTEX_NORMAL)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_NORMAL);
+#   endif
```
Comment (t8m) [inline crypto/threads_pthread.c:67]: I am sorry for confusing things but unfortunately I realized the PTHREAD_MUTEX_NORMAL/PTHREAD_MUTEX_ERRORCHECK are not macros but just enum values. So this will not work. So please just revert this part to your original solution (possibly with inverting the condition and else).

Comment (rsbeckerca) [reply crypto/threads_pthread.c:67]: > 
> 
> I am sorry for confusing things but unfortunately I realized the PTHREAD_MUTEX_NORMAL/PTHREAD_MUTEX_ERRORCHECK are not macros but just enum values. So this will not work. So please just revert this part to your original solution (possibly with inverting the condition and else).

Will correct. Note that these are macros under cygwin as well. My Ubuntu system has them as enums. The set of values in cygwin - pretty recent update - does not line up precisely with Ubuntu.

**Comment by rsbeckerca** [comment]
Tests pass for the SPT build. So this looks good.

**Comment by rsbeckerca** [comment]
@richsalz Are you good with this as it stands now?

File: crypto/threads_pthread.c [hunk 6]
```diff
@@ -57,10 +57,13 @@ CRYPTO_RWLOCK *CRYPTO_THREAD_lock_new(void)
      * We don't use recursive mutexes, but try to catch errors if we do.
      */
     pthread_mutexattr_init(&attr);
-#  if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
+#  if ! (defined (__TANDEM) || defined (_SPT_MODEL_))
```
Comment (paulidale) [inline crypto/threads_pthread.c:60]: Style nit: delete the space after the !
Alternatively apply De Morgan's: `!defined (__TANDEM) && !defined (_SPT_MODEL_)` to shorten it.

**Review by paulidale — APPROVED** [review]

File: crypto/threads_pthread.c (hunk 6 above)
Comment (t8m) [reply crypto/threads_pthread.c:60]: @rsbeckerca could you please apply paulidale's suggestion to shorten the condition?

Comment (rsbeckerca) [reply crypto/threads_pthread.c]: > 
> 
> @rsbeckerca could you please apply paulidale's suggestion to shorten the condition?

I went with @paulidale's second option to shorten it.

**Comment by rsbeckerca** [comment]
Hoping this can make beta2.

**Review by t8m — APPROVED** [review]

File: crypto/threads_pthread.c [hunk 7]
```diff
@@ -57,10 +57,13 @@ CRYPTO_RWLOCK *CRYPTO_THREAD_lock_new(void)
      * We don't use recursive mutexes, but try to catch errors if we do.
      */
     pthread_mutexattr_init(&attr);
-#  if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
+#  if !defined (__TANDEM) && !defined (_SPT_MODEL_)
+#   if !defined(NDEBUG) && !defined(OPENSSL_NO_MUTEX_ERRORCHECK)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_ERRORCHECK);
-# else
```
Comment (t8m) [inline crypto/threads_pthread.c:62]: Ouch, this looks wrong. This else has to be kept (indented by one space).

**Review by t8m — CHANGES_REQUESTED** [review]

File: crypto/threads_pthread.c (hunk 7 above)
Comment (rsbeckerca) [reply crypto/threads_pthread.c:62]: WT... Where did it go? It was there before I did the `rebase`. Trying again.

Comment (rsbeckerca) [reply crypto/threads_pthread.c:62]: What it looks like in my branch:
https://github.com/rsbeckerca/openssl/blob/d453475b2c5456b7631587299955d69a02c36b99/crypto/threads_pthread.c#L60-L67
which puts the `#   else` in the correct place although it looks a little awkward given the code contained.

Comment (t8m) [reply crypto/threads_pthread.c:62]: This is of course wrong - there is missing `#   else` between the pthread calls.

Comment (rsbeckerca) [reply crypto/threads_pthread.c:62]: > 
> 
> This is of course wrong - there is missing `# else` between the pthread calls.

Ack. Sorry.

Comment (rsbeckerca) [reply crypto/threads_pthread.c:62]: Should be fixed now.

**Review by t8m — APPROVED** [review]
LGTM now. @paulidale please re-confirm.

**Review by paulidale — APPROVED** [review]

**Comment by paulidale** [comment]
Merged, thanks for the fix.
