### ISSUE TITLE
OpenSSLl 1.1.1d does not compile on default OpenBSD 6.6 setup

### ISSUE THREAD

**Issue by denis1482** [openssl/openssl#10552]
OpenSSL 1.1.1d build fails on default OpenBSD 6.6 (amd64) setup:
````
./config --prefix=/home/disik/tmp/openssl
gmake install
<...> [https://pastebin.com/2c8h00HM](https://pastebin.com/2c8h00HM)
cc  -I. -Icrypto/include -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/disik/tmp/openssl/ssl\"" -DENGINESDIR="\"/home/disik/tmp/openssl/lib/engines-1.1\"" -D_THREAD_SAFE -D_REENTRANT -DNDEBUG  -MMD -MF crypto/engine/eng_devcrypto.d.tmp -MT crypto/engine/eng_devcrypto.o -c -o crypto/engine/eng_devcrypto.o crypto/engine/eng_devcrypto.c
crypto/engine/eng_devcrypto.c:40:43: warning: declaration of 'struct session_op' will not be visible outside of this function [-Wvisibility]
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:41:39: error: incomplete definition of type 'struct session_op'
    if (ioctl(cfd, CIOCFSESSION, &sess->ses) < 0) {
                                  ~~~~^
crypto/engine/eng_devcrypto.c:40:43: note: forward declaration of 'struct session_op'
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:41:20: error: use of undeclared identifier 'CIOCFSESSION'
    if (ioctl(cfd, CIOCFSESSION, &sess->ses) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:45:21: error: invalid application of 'sizeof' to an incomplete type 'struct session_op'
    memset(sess, 0, sizeof(struct session_op));
                    ^     ~~~~~~~~~~~~~~~~~~~
crypto/engine/eng_devcrypto.c:40:43: note: forward declaration of 'struct session_op'
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:60:23: error: field has incomplete type 'struct session_op'
    struct session_op sess;
                      ^
crypto/engine/eng_devcrypto.c:60:12: note: forward declaration of 'struct session_op'
    struct session_op sess;
           ^
crypto/engine/eng_devcrypto.c:78:48: error: use of undeclared identifier 'CRYPTO_DES_CBC'
    { NID_des_cbc, 8, 8, 8, EVP_CIPH_CBC_MODE, CRYPTO_DES_CBC },
                                               ^
crypto/engine/eng_devcrypto.c:91:50: error: use of undeclared identifier 'CRYPTO_ARC4'; did you mean 'CRYPTO_free'?
    { NID_rc4, 1, 16, 0, EVP_CIPH_STREAM_CIPHER, CRYPTO_ARC4 },
                                                 ^~~~~~~~~~~
                                                 CRYPTO_free
include/openssl/crypto.h:271:6: note: 'CRYPTO_free' declared here
void CRYPTO_free(void *ptr, const char *file, int line);
     ^
crypto/engine/eng_devcrypto.c:114:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:116:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:118:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:126:21: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
    for (i = 0; i < OSSL_NELEM(cipher_data); i++)
                    ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:165:28: error: use of undeclared identifier 'COP_ENCRYPT'
    cipher_ctx->op = enc ? COP_ENCRYPT : COP_DECRYPT;
                           ^
crypto/engine/eng_devcrypto.c:165:42: error: use of undeclared identifier 'COP_DECRYPT'
    cipher_ctx->op = enc ? COP_ENCRYPT : COP_DECRYPT;
                                         ^
crypto/engine/eng_devcrypto.c:168:20: error: use of undeclared identifier 'CIOCGSESSION'
    if (ioctl(cfd, CIOCGSESSION, &cipher_ctx->sess) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:181:21: error: variable has incomplete type 'struct crypt_op'
    struct crypt_op cryp;
                    ^
crypto/engine/eng_devcrypto.c:181:12: note: forward declaration of 'struct crypt_op'
    struct crypt_op cryp;
           ^
crypto/engine/eng_devcrypto.c:220:20: error: use of undeclared identifier 'CIOCCRYPT'
    if (ioctl(cfd, CIOCCRYPT, &cryp) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:314:47: error: use of undeclared identifier 'COP_ENCRYPT'
                           (cipher_ctx->op == COP_ENCRYPT));
                                              ^
crypto/engine/eng_devcrypto.c:340:30: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
static int known_cipher_nids[OSSL_NELEM(cipher_data)];
                             ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:342:41: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
static EVP_CIPHER *known_cipher_methods[OSSL_NELEM(cipher_data)] = { NULL, };
                                        ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:347:23: error: variable has incomplete type 'struct session_op'
    struct session_op sess;
                      ^
crypto/engine/eng_devcrypto.c:60:12: note: forward declaration of 'struct session_op'
    struct session_op sess;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
gmake[1]: *** [Makefile:3160: crypto/engine/eng_devcrypto.o] Error 1
gmake[1]: Leaving directory '/home/disik/tmp/openssl-1.1.1d'
gmake: *** [Makefile:177: build_libs] Error 2
````

**Comment by mattcaswell** [comment]
@levitte

**Comment by levitte** [comment]
@cotequeiroz, would you mind helping out?  I have this tentative diff (@denis1482, please feel free to try it out)...

``` diff
diff --git a/engines/e_devcrypto.c b/engines/e_devcrypto.c
index 489109a80d..e76bd1d05c 100644
--- a/engines/e_devcrypto.c
+++ b/engines/e_devcrypto.c
@@ -70,6 +70,7 @@ struct driver_info_st {
 void engine_load_devcrypto_int(void);
 #endif
 
+#ifdef CIOCGSESSION
 static int clean_devcrypto_session(struct session_op *sess) {
     if (ioctl(cfd, CIOCFSESSION, &sess->ses) < 0) {
         ERR_raise_data(ERR_LIB_SYS, errno, "calling ioctl()");
@@ -78,6 +79,7 @@ static int clean_devcrypto_session(struct session_op *sess) {
     memset(sess, 0, sizeof(struct session_op));
     return 1;
 }
+#endif
 
 /******************************************************************************
  *
@@ -90,7 +92,9 @@ static int clean_devcrypto_session(struct session_op *sess) {
  *****/
 
 struct cipher_ctx {
+#ifdef CIOCGSESSION
     struct session_op sess;
+#endif
     int op;                      /* COP_ENCRYPT or COP_DECRYPT */
     unsigned long mode;          /* EVP_CIPH_*_MODE */
 
@@ -403,7 +407,9 @@ static int devcrypto_test_cipher(size_t cipher_data_index)
 static void prepare_cipher_methods(void)
 {
     size_t i;
+#ifdef CIOCGSESSION
     struct session_op sess;
+#endif
     unsigned long cipher_mode;
 #ifdef CIOCGSESSINFO
     struct session_info_op siop;
@@ -411,13 +417,16 @@ static void prepare_cipher_methods(void)
 
     memset(&cipher_driver_info, 0, sizeof(cipher_driver_info));
 
+#ifdef CIOCGSESSION
     memset(&sess, 0, sizeof(sess));
     sess.key = (void *)"01234567890123456789012345678901234567890123456789";
+#endif
 
     for (i = 0, known_cipher_nids_amount = 0;
          i < OSSL_NELEM(cipher_data); i++) {
 
         selected_ciphers[i] = 1;
+#ifdef CIOCGSESSION
         /*
          * Check that the cipher is usable
          */
@@ -427,7 +436,7 @@ static void prepare_cipher_methods(void)
             cipher_driver_info[i].status = DEVCRYPTO_STATUS_NO_CIOCGSESSION;
             continue;
         }
-
+#endif
         cipher_mode = cipher_data[i].flags & EVP_CIPH_MODE;
 
         if ((known_cipher_methods[i] =
@@ -621,7 +630,9 @@ static void dump_cipher_info(void)
  *****/
 
 struct digest_ctx {
+#ifdef CIOCGSESSION
     struct session_op sess;
+#endif
     /* This signals that the init function was called, not that it succeeded. */
     int init_called;
     unsigned char digest_res[HASH_MAX_LEN];
@@ -840,7 +851,9 @@ static void rebuild_known_digest_nids(ENGINE *e)
 static void prepare_digest_methods(void)
 {
     size_t i;
+#ifdef CIOCGSESSION
     struct session_op sess1, sess2;
+#endif
 #ifdef CIOCGSESSINFO
     struct session_info_op siop;
 #endif
@@ -848,14 +861,17 @@ static void prepare_digest_methods(void)
 
     memset(&digest_driver_info, 0, sizeof(digest_driver_info));
 
+#ifdef CIOCGSESSION
     memset(&sess1, 0, sizeof(sess1));
     memset(&sess2, 0, sizeof(sess2));
+#endif
 
     for (i = 0, known_digest_nids_amount = 0; i < OSSL_NELEM(digest_data);
          i++) {
 
         selected_digests[i] = 1;
 
+#ifdef CIOCGSESSION
         /*
          * Check that the digest is usable
          */
@@ -865,6 +881,7 @@ static void prepare_digest_methods(void)
             digest_driver_info[i].status = DEVCRYPTO_STATUS_NO_CIOCGSESSION;
             goto finish;
         }
+#endif
 
 #ifdef CIOCGSESSINFO
         /* gather hardware acceleration info from the driver */
@@ -882,6 +899,7 @@ static void prepare_digest_methods(void)
         }
 #endif
 
+#ifdef CIOCGSESSION
         /* digest must be capable of hash state copy */
         sess2.mac = sess1.mac;
         if (ioctl(cfd, CIOCGSESSION, &sess2) < 0) {
@@ -894,6 +912,7 @@ static void prepare_digest_methods(void)
             digest_driver_info[i].status = DEVCRYPTO_STATUS_NO_CIOCCPHASH;
             goto finish;
         }
+#endif
         if ((known_digest_methods[i] = EVP_MD_meth_new(digest_data[i].nid,
                                                        NID_undef)) == NULL
             || !EVP_MD_meth_set_input_blocksize(known_digest_methods[i],
@@ -914,9 +933,11 @@ static void prepare_digest_methods(void)
         }
         digest_driver_info[i].status = DEVCRYPTO_STATUS_USABLE;
 finish:
+#ifdef CIOCGSESSION
         ioctl(cfd, CIOCFSESSION, &sess1.ses);
         if (sess2.ses != 0)
             ioctl(cfd, CIOCFSESSION, &sess2.ses);
+#endif
         if (devcrypto_test_digest(i))
             known_digest_nids[known_digest_nids_amount++] = digest_data[i].nid;
     }
```

**Comment by denis1482** [comment]
@levitte I cannot test it on https://www.openssl.org/source/openssl-1.1.1d.tar.gz which the issue is for, the patch program does not succeed.

**Comment by cotequeiroz** [comment]
I will take a look at it.

**Comment by levitte** [comment]
Oh argh, this is 1.1.1, right!  So uhm, same principle there, guards around any use of `struct session_op`

**Comment by cotequeiroz** [comment]
OpenBSD removed /dev/crypto support in 5.8, so we should not be compiling the engine for it.

**Comment by levitte** [comment]
Ah, ok then, a configuration problem.  Please try #10565
