### ISSUE TITLE
Build broken by #32178

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#32548]
@t8m as soon as you merged #32178 our kryoptic builds started to fail like this:

```
  apps/ca.c:2431:5: error: call to undeclared function 'BIO_snprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   2431 |     BIO_snprintf(str, i, "%.*s", (int)ASN1_STRING_get_length(revtm),
        |     ^
  1 error generated.
  make[1]: *** [Makefile:22801: apps/openssl-bin-ca.o] Error 1
```

I think we are missing a proper CI to catch these things

**Comment by bob-beck** [comment]
should be fixed by https://github.com/openssl/openssl/pull/32547

**Comment by simo5** [comment]
Yeah it is fixed by latest master, thanks!
