### ISSUE TITLE
Undefined reference when using GF2m in CentOS

### ISSUE THREAD

**Issue by liorbiu** [openssl/openssl#2072]
I'm trying to use OpenSSL on Centos 7. When I'm compiling my code I'm getting two error messages at linking:

```
In function `OpenSSLDlogECF2m::createCurve()':
DlogOpenSSL.cpp:(.text+0x510f): undefined reference to `EC_GROUP_new_curve_GF2m'
../scapi.a(DlogOpenSSL.o): In function `OpenSSLECF2mPoint::OpenSSLECF2mPoint(boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1> const&, boost::multiprecision::number<boost::multiprecision::backends::gmp_int, (boost::multiprecision::expression_template_option)1> const&, OpenSSLDlogECF2m*, bool)':
DlogOpenSSL.cpp:(.text+0x88e3): undefined reference to `EC_POINT_set_affine_coordinates_GF2m'
```

The code is compiling and running on ubuntu 16.04 with openssl 1.0.2j.

What could be the problem? Is there any flag that I need to compile with in order to linking GF2m curves?

**Comment by richsalz** [comment]
Which version of openssl?

**Comment by liorbiu** [comment]
I'm using 1.0.2.j. I tried to compile with openssl 1.1.0, but my code doesn't compile with this version.

**Comment by levitte** [comment]
Quite a lot has happened between the 1.0.2 series and 1.1.0. DlogOpenSSL.cpp will need some changes.

**Comment by richsalz** [comment]
do "nm -o libcrypto.a | grep GF2" and what do you get?  What is the config line you used?

**Comment by snhenson** [comment]
The no-ec2m option will disable GF2m curves but that is not set by default.

**Comment by liorbiu** [comment]
Thanks for your reply. because I'm compiling openssl-1.0.2j manually, I forgot to link libcrypto.a to it's new position. After I linked it to the right place my code is running.
