### ISSUE TITLE
1.0.1t-1+deb8u2 causing compilation failures "error: ‘SSLv2_method’ redeclared as different kind of symbol"

### ISSUE THREAD

**Issue by russmac** [openssl/openssl#1190]
On Debian 8.4, Linux ip-10-1-1-99 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Since upgrading from 1.0.1k-3+deb8u5 ->  1.0.1t-1+deb8u2 I cannot install pip cryptography packages (irrespective of their version)

#### Reproduce
```
apt-get install --force-yes libssl-dev=1.0.1t-1+deb8u2 libssl1.0.0=1.0.1t-1+deb8u2 openssl=1.0.1t-1+deb8u2 build-essential python-pip python-dev libffi-dev
pip install cryptography
```
#### Workaround
```
apt-get install --force-yes libssl-dev=1.0.1k-3+deb8u5 libssl1.0.0=1.0.1k-3+deb8u5 openssl=1.0.1k-3+deb8u5
pip install cryptography
```

Force installing the previous version of openssl resolves the issue. Ive tried several version of pip cryptography from 1.0 to 1.4

It is easily reproduced with the packages / pip install cryptography.

I've debugged:
```
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 59: ordinal not in range(128)
```

And determined the encoding of my provisioner or shell has no effect and has always been set UTF8.

It looks like this may be the cause (caveat, I know zero C):
```
build/temp.linux-x86_64-2.7/_openssl.c:2096:15: error: ‘SSLv2_method’ redeclared as different kind of symbol
```

### full trace
```
building '_openssl' extension

creating build/temp.linux-x86_64-2.7/build

creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o

build/temp.linux-x86_64-2.7/_openssl.c:2096:15: error: ‘SSLv2_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2021:19: note: previous declaration of ‘SSLv2_method’ was here

 const SSL_METHOD *SSLv2_method(void); /* SSLv2 */

                   ^

build/temp.linux-x86_64-2.7/_openssl.c:2097:15: error: ‘SSLv2_client_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_client_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2023:19: note: previous declaration of ‘SSLv2_client_method’ was here

 const SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */

                   ^

build/temp.linux-x86_64-2.7/_openssl.c:2098:15: error: ‘SSLv2_server_method’ redeclared as different kind of symbol

 SSL_METHOD* (*SSLv2_server_method)(void) = NULL;

               ^

In file included from build/temp.linux-x86_64-2.7/_openssl.c:523:0:

/usr/include/openssl/ssl.h:2022:19: note: previous declaration of ‘SSLv2_server_method’ was here

 const SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */

                   ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of cryptography
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-13wIIt/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1C0XrA-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-13wIIt/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 59: ordinal not in range(128)
```

**Comment by mattcaswell** [comment]
1.0.1s made this change due to CVE-2016-0800:

````
  * Disable SSLv2 default build, default negotiation and weak ciphers.  SSLv2
    is by default disabled at build-time.  Builds that are not configured with
    "enable-ssl2" will not support SSLv2.  Even if "enable-ssl2" is used,
    users who want to negotiate SSLv2 via the version-flexible SSLv23_method()
    will need to explicitly call either of:

        SSL_CTX_clear_options(ctx, SSL_OP_NO_SSLv2);
    or
        SSL_clear_options(ssl, SSL_OP_NO_SSLv2);

    as appropriate.  Even if either of those is used, or the application
    explicitly uses the version-specific SSLv2_method() or its client and
    server variants, SSLv2 ciphers vulnerable to exhaustive search key
    recovery have been removed.  Specifically, the SSLv2 40-bit EXPORT
    ciphers, and SSLv2 56-bit DES are no longer available.
    (CVE-2016-0800)
    [Viktor Dukhovni]
````
So, either you need to use a build of OpenSSL which has been compiled with the "enable-ssl2" option, or packages that use SSLv2 need to be updated to not use it.

**Comment by levitte** [comment]
@mattcaswell, that's not the issue.  The issue is a clash between symbols defined in the `_openssl` python extension and declared in our `ssl.h`.  I suspect that commit 03c71b84d351a3a5de0bc7d39a99336369277849 and 66299660976540fa59450a5edc700e61ce4685d0 are behind this, as they change the guard from `OPENSSL_NO_SSL2` to `OPENSSL_NO_SSL2_METHOD`, and I further suspect that the latter isn't defined (which @russmac can confirm by having a look in `/usr/include/openssl/opensslconf.h` or `/usr/include/x86_64-linux-gnu/openssl/opensslconf.h`, whichever applies)

@russmac, could you have a look and confirm?

**Comment by russmac** [comment]
Hi Guys, Thanks for the updates.

No results for OPENSSL_NO_SSL2_METHOD in that file.
```
root@ip-10-1-1-99:/home/admin# cat /usr/include/x86_64-linux-gnu/openssl/opensslconf.h | grep OPENSSL_NO_SSL2_METHOD
```

**Comment by levitte** [comment]
Like I suspected.

I would suggest that you do a bit of renaming in `_openssl.c`...  those symbols have been with us for quite a while, it's really just *pure luck* that you haven't had a clash before now.

Either way, this isn't an OpenSSL issue, so I'm closing this:

**Comment by russmac** [comment]
@levitte 
Sorry if I dont quite understand, But the issue only occurs on the new version of OpenSSL but its not an OpenSSL issue and the code causing it despite not causing the issue existed before this version?

**Comment by levitte** [comment]
You misunderstand, but perhaps this will help...  this is a grep in the 0.9.8 source:

```
: ; grep 'SSLv[23].*_meth' ssl/*.h
ssl/ssl.h:SSL_METHOD *SSLv2_method(void); /* SSLv2 */
ssl/ssl.h:SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */
ssl/ssl.h:SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */
ssl/ssl.h:SSL_METHOD *SSLv3_method(void); /* SSLv3 */
ssl/ssl.h:SSL_METHOD *SSLv3_server_method(void); /* SSLv3 */
ssl/ssl.h:SSL_METHOD *SSLv3_client_method(void); /* SSLv3 */
ssl/ssl.h:SSL_METHOD *SSLv23_method(void); /* SSLv3 but can rollback to v2 */
ssl/ssl.h:SSL_METHOD *SSLv23_server_method(void); /* SSLv3 but can rollback to v2 */
ssl/ssl.h:SSL_METHOD *SSLv23_client_method(void); /* SSLv3 but can rollback to v2 */
```

It's therefore safe to say that those functions have been around for a while.

You haven't had a clash with the `SSLv2_*` functions because they were disabled in the Debian packaging.  That's pure luck (or lack of luck).

Since it's the `cryptography` package that produces `_openssl.c` (and I'm not savvy enough to tell you how that's done), I'd say you should talk to the maintainers of that package.  Perhaps [here on github](https://github.com/pyca/cryptography)

**Comment by russmac** [comment]
@levitte thanks for explaining, The Debian package changing makes sense to me. I'll be the optimist and say its pure luck ;). Cryptography have taken on the issue.

**Comment by alex** [comment]
@levitte Thanks for directing this our way -- we seem to hit an unnatural number of these sorts of compilation errors, due to the large number of platforms we support. Please keep sending them back our way, if there's really an OpenSSL bug we'll make sure they make it back to you guys :-)
