### ISSUE TITLE
Incomplete definition of type 'struct x509_revoked_st'

### ISSUE THREAD

**Issue by ecnepsnai** [openssl/openssl#2990]
I'm using OpenSSL 1.1.0e in my project, and I've run into an issue where I cannot access any properties of a X509 revoked struct. 

Here's the relevant area of my source:

```c
#include <openssl/ssl.h>
#include <openssl/ossl_typ.h>
#include <openssl/x509v3.h>

X509_CRL * crl;
crl = d2i_X509_CRL(NULL, &crlData, crlLength);
struct x509_revoked_st * revoked;
const ASN1_INTEGER * serial = X509_get0_serialNumber(certificate);
X509_CRL_get0_by_serial(crl, &revoked, (ASN1_INTEGER *)serial);
if (revoked->reason == CRL_REASON_REMOVE_FROM_CRL) { // Incomplete definition of type 'struct x509_revoked_st'

}
```

I also noticed that I can't find the definition of `x509_revoked_st` anywhere in the headers, but I see its defined in `crypto/include/internal/x509_int.h`

The only reference I see to it in the public headers are the typdef to `X509_REVOKED` in ossl_typ.h:

```c
typedef struct x509_revoked_st X509_REVOKED;
```

**Comment by richsalz** [comment]
Yes, like most of the OpenSSL structures it is now an opaque datatype.  What fields do you need?  We would have to write accessors and documentation.  It would go into master and 1.1.0 because missing accessors we consider a bug.

**Comment by levitte** [comment]
Actually, in this particular case, you could simply look at the value returned by `X509_CRL_get0_by_serial`.  If it's 2, then the `revoked` you got has the reason `CRL_REASON_REMOVE_FROM_CRL`.  Unfortunately, our manual is incomplete in this regard.

**Comment by levitte** [comment]
Either way, you *should* look at the value returned by `X509_CRL_get0_by_serial`.  If it's 0, you're in for a crash at some point...

**Comment by levitte** [comment]
FYI, I've made a clarifying update of the manual, see #2993

**Comment by ecnepsnai** [comment]
Just out of curiosity, what about the other properties like revocation date? Would a accessor be needed for that?

**Comment by richsalz** [comment]
Yes, what fields do you need access to?

**Comment by ecnepsnai** [comment]
Just the date, please.

I'd be happy to write the accessor if you could provide an example of a similar one that I would use as a reference.

**Comment by levitte** [comment]
From `include/openssl/x509.h`:

``` C
const ASN1_INTEGER *X509_REVOKED_get0_serialNumber(const X509_REVOKED *x);
const ASN1_TIME *X509_REVOKED_get0_revocationDate(const X509_REVOKED *x);
const STACK_OF(X509_EXTENSION) *X509_REVOKED_get0_extensions(const X509_REVOKED *r);
```

and that actually covers everything contained in a `revokedCertificate` field, any other information is found in the extensions (that includes the revokation reason, actually).

**Comment by ecnepsnai** [comment]
Oh, that's great!

Thanks for the help @levitte and @richsalz!

**Comment by ecnepsnai** [comment]
Sorry to keep bringing this closed bug back, I just realized I had my understanding of how `X509_CRL_get0_by_serial` worked wrong.

I thought `X509_CRL_get0_by_serial` returned the revoked reason enum value, but it does not. The question is then, how do I get the reason?

In my example in the original issue it was just a coincidence that I was checking for remove from CRL.

**Comment by v-sijeff** [comment]
Hello, I have been tasked with fixing a program that I have never seen before.  It compiles and runs quite nicely with openssl 1.0 but will not compile with 1.1  The error message is:

```
$ make
  CC      main.c
main.c: In function ‘do_signature’:
main.c:63:10: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  memcpy(x->signature->data, sig_buf, sig_len);
          ^~
Makefile:54: recipe for target 'main.o' failed
make: *** [main.o] Error 1
$ 
```

The relevant code is:
```
        /* Replace the signature in the Cert with HSM signature */
        memcpy(x->signature->data, sig_buf, sig_len);
        x->signature->length = sig_len;

```
I see where X509 is defined in ossl.h but I am having trouble following beyond that.

Thank you
