### ISSUE TITLE
Building on the openssl-3.0 branch is broken

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#19015]
Seems to have been broken by commit d6e3a2c15 (#18906):

````
crypto/property/property.c: In function 'ossl_method_cache_flush_some':
crypto/property/property.c:676:9: error: implicit declaration of function 'tsan_add'; did you mean 'tsan_load'? [-Werror=implicit-function-declaration]
  676 |         tsan_add(&global_seed, state.seed);
      |         ^~~~~~~~
      |         tsan_load
cc1: all warnings being treated as errors
make[1]: *** [Makefile:17281: crypto/property/libcrypto-lib-property.o] Error 1
make[1]: Leaving directory '/home/matt/dev/openssl-write'
make: *** [Makefile:3205: build_sw] Error 2
````

**Comment by t8m** [comment]
There is a fix in #19009

**Comment by levitte** [comment]
#19009 merged, so closing this
