### ISSUE TITLE
undefined reference to `EVP_MD_get_size`

### ISSUE THREAD

**Issue by Bab95** [openssl/openssl#19970]
Openssl version 3.0.7

For build issues:

I was building project that uses openssl in docker container where i installed openssl 

```
apt-get install -y libssl-dev
```

which installed openssl 1.1.

I updated my docker image to use latest version 3.0.7. built with the following snippet
```
# Install Openssl
RUN apt-get update && \
    apt-get install -y perl

ENV OPENSSL_VERSION="3.0.7"
RUN set -x && \
 ### BUILD OpenSSL
    wget --no-check-certificate -O /tmp/openssl-${OPENSSL_VERSION}.tar.gz "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" && \
    tar -xzf /tmp/openssl-${OPENSSL_VERSION}.tar.gz -C /tmp/ && \
    rm -rf /tmp/openssl-${OPENSSL_VERSION}.tar.gz && \ 
    cd /tmp/openssl-${OPENSSL_VERSION} && \
    ./Configure linux-x86_64 shared && \
    make && \
    make test && \
    make install && \
    ldconfig /usr/local/lib64/ && \
    cd .. && \
    rm -rf openssl-${OPENSSL_VERSION}
```

for building there are bunch of cmake files in the project. 
when i upgraded to 3.0.7 It started giving error undefined reference to **EVP_MD_get_size**

Encrypt.cpp:(.text+0x1976): undefined reference to `EVP_MD_get_size'
collect2: error: ld returned 1 exit status
make[2]: *** [<filePath>] Error 1
make[1]: *** [<filepath>] Error 2
../lib/libTpm2.a(Encrypt.cpp.o): In function `Encrypt::GeneratePcrDigest(encrypt::PcrSet const&, encpryt::HashAlg)':
Encrypt.cpp:(.text+0x1976): undefined reference to `EVP_MD_get_size'
collect2: error: ld returned 1 exit status

**CMAKELists.txt** file

outermost:
```
if (NOT DEFINED ENV{CC} )
    set (CMAKE_C_COMPILER "/usr/bin/gcc-8")
    set (CMAKE_CXX_COMPILER "/usr/bin/g++-8")
endif ()
set (CMAKE_CXX_STANDARD 14)
```

innner cmakelists.txt: where library link is being made

```
target_link_libraries(${CMAKE_PROJECT_TARGET} ssl crypto)

```

**Comment by t8m** [comment]
Most probably the linker does not see the libcrypto.so from the openssl-3.0.7 build. Assuming it is installed in `/usr/local/lib64` directory `-L/usr/local/lib64` has to be added to the linker flags of the project you're building.

**Comment by Bab95** [comment]
@t8m  Thanks. I have added the link_directories(/usr/local/lib64) in cmake file after this project compiles but still linking with the libcrypto.so.1.1 (container is ubuntu 18.04 version so by default it has openssl 1.1 installed). When i try to execute binary on ubuntu 22.04 which has libcrypto.so.3.0 not libcrypto.so.1.1 it fails saying libcrypto.so.1.1 not found.
Why this is happening?
Shouldn't application take whatever is present at runtime?

CMakeLists.txt :
```
link_directories(/usr/local/lib64/)

target_link_libraries(${PROJECT_NAME} ssl crypto)
```

```
$ldd <application>
 linux-vdso.so.1 (0x00007ffc4a060000)
 libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fc885ac0000)
.
.
.
```

**Comment by t8m** [comment]
I assume it is possible to install some libcrypto11 package on ubuntu 22.04. The 3.0 and 1.1 OpenSSL libraries are not binary compatible so that means an application compiled against 1.1.x cannot be run with 3.x.y OpenSSL library.

**Comment by Bab95** [comment]
@t8m thanks for confirming this. Anyways liking static libs would work fine right!

**Comment by t8m** [comment]
Yeah, if you link to static libcrypto.a / libssl.a when building then it won't use the shared OpenSSL libraries from the system at runtime.

**Comment by zahidpichen** [comment]
Hi, @Bab95 did adding statically work for you? in my case, i'm building open3d with cuda in jetson orin nano, inside a jetson-container to be specific.

while doing the build i had similar error to what you had and i was search for different solutions. finally stumbled upon this issue

thank you @t8m and @Bab95

**Comment by Bab95** [comment]
Yes. Static worked for me.

**Comment by zahidpichen** [comment]
okay, will try!
