### PR TITLE
Untangle version and config header file

### LINKED ISSUE #7874: opensslconf.h and opensslv.h include each other
The subject line says it all.  These two files should be untangled somehow.  One option, probably the simplest (I spent a bit of time trying to do it and failed) is to merge opensslv.h into opensslconf.h.in and make the first one just be a one-liner that includes the second one.

### LINKED ISSUE #9601: OPENSSL_API macros don't work if <openssl/macros.h> is included first
In commit e039ca38c8d77f1e2f182123727c884aaf2d683d the `OPENSSL_API` macros were moved into a separate file `<openssl/macros.h>` Somehow this change does not make sense (yet), because it is not possible to include  `<openssl/macros.h>` without including `<openssl/opensslv.h>` first. If one does it (as suggested by @levitte in https://github.com/openssl/openssl/pull/9333#discussion_r312785544), one gets a compiler error, see the example below.

But since there is an include chain `<openssl/opensslv.h>` => `<openssl/opensslconf.h>` => `<openssl/macros.h>`, it does not make sense to include `<openssl/macros.h>` after `<openssl/opensslv.h>` anymore.

So either a solution needs to be found to break up this vicious circle somehow (which would be helpful for https://github.com/openssl/openssl/pull/9333#discussion_r312785544) or it does not make sense to have the `OPENSSL_API` macros in a separate file.

#### See also

This dependency problem seems  to reoccur intermittently:

- #7874 opensslconf.h and opensslv.h include each other (by @richsalz)
- #9528 err.h needs macros.h, which needs opensslv.h (by @DDvO)

#### Example

You can try it for yourself on master: simply patch openssl.c and run make:

```diff
diff --git a/apps/openssl.c b/apps/openssl.c
index 123c1ff4ce..e1be6a5d6e 100644
--- a/apps/openssl.c
+++ b/apps/openssl.c
@@ -7,6 +7,8 @@
  * https://www.openssl.org/source/license.html
  */
 
+#include <openssl/macros.h>
+
 #include <internal/cryptlib.h>
 #include <stdio.h>
 #include <string.h>
```

```make
In file included from apps/openssl.c:10:
include/openssl/macros.h:80:6: error: "OPENSSL_VERSION_MAJOR" is not defined, evaluates to 0 [-Werror=undef]
 # if OPENSSL_VERSION_MAJOR < 4
      ^~~~~~~~~~~~~~~~~~~~~
include/openssl/macros.h:60:29: error: "OPENSSL_MIN_API" is not defined, evaluates to 0 [-Werror=undef]
 #  define OPENSSL_API_LEVEL OPENSSL_MIN_API
                             ^~~~~~~~~~~~~~~
include/openssl/macros.h:91:6: note: in expansion of macro 'OPENSSL_API_LEVEL'
 # if OPENSSL_API_LEVEL < 3
      ^~~~~~~~~~~~~~~~~
include/openssl/macros.h:60:29: error: "OPENSSL_MIN_API" is not defined, evaluates to 0 [-Werror=undef]
 #  define OPENSSL_API_LEVEL OPENSSL_MIN_API
                             ^~~~~~~~~~~~~~~
include/openssl/macros.h:99:6: note: in expansion of macro 'OPENSSL_API_LEVEL'
 # if OPENSSL_API_LEVEL < 2
      ^~~~~~~~~~~~~~~~~
include/openssl/macros.h:60:29: error: "OPENSSL_MIN_API" is not defined, evaluates to 0 [-Werror=undef]
 #  define OPENSSL_API_LEVEL OPENSSL_MIN_API
                             ^~~~~~~~~~~~~~~
include/openssl/macros.h:107:6: note: in expansion of macro 'OPENSSL_API_LEVEL'
 # if OPENSSL_API_LEVEL < 1
      ^~~~~~~~~~~~~~~~~
include/openssl/macros.h:60:29: error: "OPENSSL_MIN_API" is not defined, evaluates to 0 [-Werror=undef]
 #  define OPENSSL_API_LEVEL OPENSSL_MIN_API
                             ^~~~~~~~~~~~~~~
include/openssl/macros.h:115:6: note: in expansion of macro 'OPENSSL_API_LEVEL'
 # if OPENSSL_API_LEVEL < 0
      ^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by mspncp**
Since the new versioning scheme was introduced in commit 3a63dbef15b6,
the following two header files #include each other.

    <openssl/opensslconf.h>  ==> <openssl/opensslv.h>
    <openssl/opensslv.h>     ==> <openssl/opensslconf.h> (NEW)

The reason for the new inverse dependency is the fact that the legacy
OPENSSL_VERSION_NUMBER macro is now guarded by a deprecation guard.

No matter which one of the two headers is included by an application,
the other one will be included, too. Normally, it is always the other
header which ends up being read first by the preprocessor/compiler.
But in this case a "dirty" trick was used to enforce the following
inclusion order:

     <openssl/opensslv.h>     (first part)
     <openssl/opensslconf.h>
     <openssl/opensslv.h>     (second part)

The situation became even more complicated in e039ca38c8d7, when
the deprecation macros were moved from <openssl/opensslconf.h> into
a new file <openssl/macros.h>.

This commit detangles the three files by moving the deprecation macros into
<openssl/opensslv.h> instead, where they fit more naturally anyway.
This move was actually already suggested in https://github.com/openssl/openssl/issues/7874#issuecomment-446372494, but then the idea
abandoned for some reason.

The change makes <openssl/macros.h> independent from the other two.
There is still an inclusion order which needs to be enforced,

     <openssl/opensslconf.h>
     <openssl/opensslv.h>

but it is done in a more traditional way and a warning comment is added.

Note: the only remaining dependency from opensslv.h to opensslconf.h
is the configurable macro OPENSSL_MIN_API. It would be possible to
remove this dependency at the price of making opensslv.h a generated
file.

Fixes #7874
Fixes #9601

### CODE REVIEW

File: include/openssl/opensslconf.h.in [hunk 1]
```diff
@@ -9,11 +9,22 @@
...
  */
 
-#include <openssl/opensslv.h>
-
 #ifndef HEADER_OPENSSLCONF_H
 # define HEADER_OPENSSLCONF_H
 
+/*
+ * Important Note: Since the change of the versioning scheme in commit
+ * 3a63dbef15b6, the two header files
```
Comment (richsalz) [inline include/openssl/opensslconf.h.in]: I don't think it's a good idea to have commit ID's in the source; maybe a link to the PR?  Even that is not great, IMO.

Comment (mspncp) [reply include/openssl/opensslconf.h.in]: IMO, git is a distributed vcs, so every information should be available in the local repository, without needing an internet connection. For that reason I think good commit messages are more important than good pull request writeups, and that references should be commit ids, not GitHub links.

Comment (mspncp) [reply include/openssl/opensslconf.h.in]: I could add the pull request number in the comment, but not the link.

File: include/openssl/opensslv.h [hunk 2]
```diff
@@ -119,9 +121,129 @@ const char *OPENSSL_version_build_metadata(void);
...
- * SECTION 3: BACKWARD COMPATIBILITY
+ * SECTION 4: BACKWARD COMPATIBILITY
  */
-# include <openssl/opensslconf.h>
+
+/*
+ * Sometimes OPENSSSL_NO_xxx ends up with an empty file and some compilers
+ * don't like that.  This will hopefully silence them.
+ */
+# define NON_EMPTY_TRANSLATION_UNIT static void *dummy = &dummy;
```
Comment (mspncp) [inline include/openssl/opensslv.h]: Maybe this definition should remain in macros.h @levitte?

File: include/openssl/opensslconf.h.in (hunk 1 above)
Comment (richsalz) [reply include/openssl/opensslconf.h.in]: Are most people who are looking at the header files just folks looking at a bundled distro release, or who are cloning the repo and building from source?

Comment (mspncp) [reply include/openssl/opensslconf.h.in]: > Are most people who are looking at the header files just folks looking at a bundled distro release, or who are cloning the repo and building from source?

The former type of people won't read the comment anyway.

But honestly, I always pay attention that the comment contains all essential information, nothing important was omitted. So there is no need to look up the commit message in order to understand the comment. But the reference to that commit is useful information nevertheless.  Would it look better for you, if the commit id was in parentheses, to make it look less important?

```
 * Important Note: Since the change of the versioning scheme (commit
 * 3a63dbef15b6), the two header files
```

Comment (richsalz) [reply include/openssl/opensslconf.h.in]: You don't need to please me. :)  I made a point, you disagree, that's okay.

**Comment by levitte** [comment]
I very strongly dislike having the deprecation macros in opensslv.h. Couldn't macros.h simply include opensslv.h? And then leave opensslconf.h.in as it is?

**Comment by mspncp** [comment]
> Couldn't macros.h simply include opensslv.h?

If macros.h would inlcude opensslv.h, then there would be three header files which would be mutually dependent. So no matter which of the three headers you get all three. And by some "dirty" trick (opensslconf.h includes opensslv.h _before_ defining it's include guard the following read order is guaranteed.

```
 <openssl/opensslv.h>     (first part)
 <openssl/opensslconf.h>
 <openssl/macros.h>
 <openssl/opensslv.h>     (second part)
```

What is the point of all this? I don't get it.

**Comment by mspncp** [comment]
Closed by accident, wrong keystroke ;-)

**Comment by mspncp** [comment]
I had to edit my last comment a bit, because I prematurely posted it.

**Comment by mspncp** [comment]
> I very strongly dislike having the deprecation macros in opensslv.h.

Hmmm... I thought I was following [your suggestion](https://github.com/openssl/openssl/issues/7874#issuecomment-446372494)?

**Comment by levitte** [comment]
> Hmmm... I thought I was following your suggestion?

I guess I have changed my mind then (that was more than half a year ago).

**Comment by levitte** [comment]
> What is the point of all this? I don't get it.

openssl/opensslconf.h should really just define a bunch of macros that correspond to configuration.  Anything else doesn't really belong there (the inclusion of openssl/macros.h is only there to retain backward compatibility)
openssl/opensslv.h should really just define a bunch of version macros.  Deprecation macros should not be defined there.
openssl/macros.h is basically the bunch of useful macros that were previously defined in opensslconf.h

The only *real* trouble is that macros.h depends on opensslv.h.  It shouldn't have to...  I have an alternative PR that untangles this in a different manner, #9626

**Comment by mspncp** [comment]
Closing in favour of #9626.
