### PR TITLE
Fix for EBCDIC builds in 1.1.1d

### LINKED ISSUE #9869: Compilation error in EBCDIC case with 1.1.1d
I got a compilation error with 1.1.1d on BS2000 (EBCDIC system):
```
openssl-1.1.1d/ssl/statem/statem_lib.c:176:` error: expected a "}"
```
It points into:
```
#ifdef CHARSET_EBCDIC
    static const char *servercontext = { 0x54, 0x4c, 0x53, 0x20, 0x31, 0x2e,
     0x33, 0x2c, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x20, 0x43, 0x65,
     0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72,
     0x69, 0x66, 0x79, 0x00 };
    static const char *clientcontext = { 0x54, 0x4c, 0x53, 0x20, 0x31, 0x2e,
     0x33, 0x2c, 0x20, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x20, 0x43, 0x65,
     0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72,
     0x69, 0x66, 0x79, 0x00 };
#else
    static const char *servercontext = "TLS 1.3, server CertificateVerify";
    static const char *clientcontext = "TLS 1.3, client CertificateVerify";
#endif
```
Which tries to initialize clientcontext and servercontext char pointers with arrays.

It should be changed like that:
```
static const char clientcontext[] = { 0x54, 0x4c, 0x53, 0x20, 0x31, 0x2e,...
```
Probably non-EBCDIC case should be changed the same way.

### PR DESCRIPTION
**Pull request by velemas**
ssl/statem/statem_lib.c: make servercontext/clientcontext arrays of chars instead of char pointers to fix EBCDIC builds.

Fixes #9869

##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Comment by t8m** [comment]
@levitte @mattcaswell I hope your approval still holds.

**Comment by levitte** [comment]
Ye

**Comment by levitte** [comment]
Wanna merge?  I've other things to focus on
