### ISSUE TITLE
unknown type name 'OSSL_i2d_of_void_ctx' when using header files

### ISSUE THREAD

**Issue by alistair23** [openssl/openssl#27344]
Since updating to use [OpenSSL 3.5.0](https://github.com/openssl/openssl/releases/tag/openssl-3.5.0) I have started seeing the following error when using OpenSSL headers in my project

```
In file included from ./os_stub/cryptlib_openssl/pk/x509.c:18:
/usr/include/openssl/pem.h:399:28: error: unknown type name 'OSSL_i2d_of_void_ctx'
  399 | int PEM_ASN1_write_bio_ctx(OSSL_i2d_of_void_ctx *i2d, void *vctx,
```

The code that causes the error looks like this

```
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/asn1.h>
#include <openssl/rsa.h>

#include <openssl/bn.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
```

The same code works fine with OpenSSL 3.4.0

**Comment by alistair23** [comment]
I would assume that https://github.com/openssl/openssl/commit/35f6e7ea02b599d5aaf220b4720cbadd946d8023 is the commit that caused this

**Comment by vdukhovni** [comment]
Perhaps your search path includes older OpenSSL headers???

```
$ grep -n '^# *include <openssl/evp.h>' include/openssl/pem.h
include/openssl/pem.h:22:# include <openssl/evp.h>

$ grep -n '^# *include <openssl/objects.h>' include/openssl/evp.h
include/openssl/evp.h:47:# include <openssl/objects.h>

$ grep -n '^# *include <openssl/asn1.h>' include/openssl/objects.h
include/openssl/objects.h:21:# include <openssl/asn1.h>

$ grep -n OSSL_i2d_of_void_ctx -- include/openssl/asn1.h
374:typedef int OSSL_i2d_of_void_ctx(const void *, unsigned char **, void *vctx);
```

**Comment by vdukhovni** [comment]
The problem is not reproducible. Marking as not a bug, please close the issue unless you can demonstrate that you're including OpenSSL headers exclusively from the 3.5.0 release and not some additional source.

In the OpenSSL 3.5 source tree, I can `#include <openssl/pem.h>` without any unresolved types.
```c
$ cat testme.c
#include <stdio.h>
#include <openssl/pem.h>

int main(void)
{
    printf("Hello World!\n");
    return 0;
}
$ cc -I./include -o testme testme.c
$ ./testme 
Hello World!

$ cc -E -I./include testme.c | grep OSSL_i2d_of_void_ctx
typedef int OSSL_i2d_of_void_ctx(const void *, unsigned char **, void *vctx);
int PEM_ASN1_write_bio_ctx(OSSL_i2d_of_void_ctx *i2d, void *vctx,
```

**Comment by slontis** [comment]
pem.h includes x509.h which includes asn1.h which should have the typedef..

**Comment by alistair23** [comment]
Yeah, it does all look correct. Something strange must be going on with my paths. I have closed this issue
