### ISSUE TITLE
Commands in libcrypto-3.dll or libs changed names or not found

### ISSUE THREAD

**Issue by smileface123** [openssl/openssl#18602]
Hi there,
I am trying to use a 3rd Party software in my app which uses OpenSSL.
Until now it was working fine with all 1.1.1 OpenSSL versions. 
However after I upgraded to OpenSSL 3.0.3, I noticed following errors in Visual Studio 2019 when building my app:

`3rdpartylib.lib(3rdparty.cpp.obj) : error LNK2019: unresolved external symbol _EVP_PKEY_base_id referenced in function "public: enum 3rdpartyvariable __thiscall 3rdparty::keyType(void)const " (?keyType@3rdparty@@QBE?AW43rdpartyPkiKeyType@@XZ) [D:\dev\projectfolder\project.vcxproj]`

and a similiar one with "`_EVP_PKEY_bits`".

Could it be that "`_EVP_PKEY_base_id`" and "`_EVP_PKEY_bits`" are not longer available in libcrypto-3.dll and the libs? Are they now without underscore as "`EVP_PKEY_base_id`" and "`EVP_PKEY_bits`" available?
Do I have to change some flags when building OpenSSL or does the 3rdParty software need to change for OpenSSL 3?

**Comment by xtkoba** [comment]
I guess that the third-party library needs to be rebuilt against OpenSSL 3 (using OpenSSL 3 public headers).

**Comment by qbe** [comment]
@vskarlsruhe please avoid tagging users with short user names by using code blocks
`like this`

```
or like this
multiline block
```

thank you.

**Comment by vskarlsruhe** [comment]
@xtkoba will try that, thanks
@qbe changed, thanks

**Comment by paulidale** [comment]
Yes, the library needs to be rebuilt against 3.0.  These functions were changes to macros in 3.0.
