### ISSUE TITLE
openssl-1.0.2j does not compile with 'no-des' option

### ISSUE THREAD

**Issue by MirkoDziadzka** [openssl/openssl#1746]
# how to reproduce
 
Using either Centos6 64bit or MacOS 10.12 (probably other Unix system too)
 
$ tar xzf openssl-1.0.2j.tar.gz
$ cd openssl-1.0.2j
$ ./config shared no-des no-comp no-engine
…
$ make depend
$ make
…
 
# expected result
 
it compiles
 
# actual result
 
make[2]: Entering directory ‘…./openssl-1.0.2j/apps'
../libcrypto.so: undefined reference to `EVP_des_ede3_wrap'
 
# remarks
 
·         it works fine when I remove the “no-des” option form ./config
·         it works fine with openssl-1.0.1

**Comment by levitte** [comment]
Fix in #1748, please try it out.

**Comment by levitte** [comment]
Thanks for the report.  The fix will be present for next 1.0.2 release.

**Comment by MirkoDziadzka** [comment]
The fix is working for me. Waiting for the next 1.0.2 release. Thanks for the fast response.
