### ISSUE TITLE
openssl 1.0.2j does not build with no-ec no-dh

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#2080]
The following configuration does not build with openssl 1.0.2 but it did work with 1.0.1:

./config no-ec no-dh
make depend && make
ake[1]: Entering directory `/home/ed/OPC/openssl-1.0.2j/ssl'
gcc -I../crypto -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o ssl_cert.o ssl_cert.c
ssl_cert.c: In function 'ssl_cert_dup':
ssl_cert.c:390:9: error: label 'err' used but not defined
make[1]: *** [ssl_cert.o] Error 1
make[1]: Leaving directory `/home/ed/OPC/openssl-1.0.2j/ssl'
make: *** [build_ssl] Error 1

build succeeds with the following patch:

``` diff
--- ssl/ssl_cert.c.orig	2016-09-26 11:49:07.000000000 +0200
+++ ssl/ssl_cert.c	2016-12-14 08:02:08.283175581 +0100
@@ -392,7 +392,7 @@ CERT *ssl_cert_dup(CERT *cert)
 
     return (ret);
 
-#if !defined(OPENSSL_NO_DH) || !defined(OPENSSL_NO_ECDH)
+#if !defined(OPENSSL_NO_DH) || !defined(OPENSSL_NO_ECDH) || !defined(OPENSSL_NO_TLSEXT)
  err:
 #endif
 #ifndef OPENSSL_NO_RSA
```

**Comment by levitte** [comment]
Actually, the correct thing to do is to remove the conditional around the lable entirely.  There is unconditional code with `goto err;`...

**Comment by bernd-edlinger** [comment]
yes, indeed.  Thanks.

**Comment by bernd-edlinger** [comment]
one more thing,

I think in line 318 the return (NULL) should also be a goto err;

right?

**Comment by levitte** [comment]
That's right, thanks for pointing that out.

**Comment by levitte** [comment]
Fixes for both got merged into the 1.0.2 branch moments ago.  They will appear in the next 1.0.2 release.

Thank you.

Closing this.
