### ISSUE TITLE
Compile on VS2008 OpenSSL 1.0.2d

### ISSUE THREAD

**Issue by R00T88** [openssl/openssl#335]
Hi all,
i'm not able to compile anymore my project under visual studio 2008 because of these external unresolved reference on libeay32.lib and ssleay32.lib.

error LNK2019: unresolved external symbol ___report_rangecheckfailure referenced in function _nid_cb	ssleay32.lib
error LNK2001: unresolved external symbol ___report_rangecheckfailure	libeay32.lib

i think the problem is related to C runtime library.
Can you make it retro-compatible?

Thank you
