### ISSUE TITLE
Existing utilities fail to build with openssl 1.1.1b 

### ISSUE THREAD

**Issue by nidhidamodaran** [openssl/openssl#9357]
I am able to build and install openssl 1.1.1b.
I am running into issues while trying to compile existing openssl based utilities.
Pasting error logs below :

ktls.c:72:34: error: dereferencing pointer to incomplete type
  EVP_CIPHER_CTX * write_ctx = ssl->enc_write_ctx;
                                  ^
ktls.c:73:59: error: dereferencing pointer to incomplete type
  EVP_AES_GCM_CTX* gcm_write = (EVP_AES_GCM_CTX*)(write_ctx->cipher_data);
                                                           ^
ktls.c:77:39: error: dereferencing pointer to incomplete type
  unsigned char* seq_number_write = ssl->s3->write_sequence;
                                       ^

When I checked, did not find struct ssl_st definition in any of the header files. 
How do I get around this error ?

**Comment by beldmit** [comment]
During the development of OpenSSL 1.1.* many structures became opaque. So you can't just access separate fields, as it was possible in 1.0.* and earlier branches. You'll have to rewrite your code using the accessors introduced in 1.1.*

**Comment by nidhidamodaran** [comment]
Thanks @beldmit . I could not find any getters to access this specify field enc_write_ctx. It would be grest if you could help out or point me to any sort of documentation about the changes.

**Comment by mattcaswell** [comment]
These are very low level fields that you are attempting to use that should not typically be accessed by applications. There is no accessor for `enc_write_ctx`. From the errors above it looks like you are attempting to access it, in order to get hold of the EVP_AES_GCM_CTX data contained within it. That type wasn't part of the public API even in 1.0.x (it was internal only) so it looks like you're trying to do stuff you're not supposed to do.

What are you attempting to do that means you need access to these things?

**Comment by nidhidamodaran** [comment]
I was trying to get this particular piece of code to compile for using kernel TLS (https://github.com/crazyguitar/ktls-example/blob/43bf0c4d016c748ab202243c44f84676cd5d35ee/lib/ktls.c#L65).

**Comment by nidhidamodaran** [comment]
@mattcaswell  Would that mean it would be no longer be possible to get these fields or are there any apis which can do the same ?

**Comment by mspncp** [comment]
> I was trying to get this particular piece of code to compile for using kernel TLS (https://github.com/crazyguitar/ktls-example/blob/43bf0c4d016c748ab202243c44f84676cd5d35ee/lib/ktls.c#L65).

In this case it might interest you that currently on 'master' there is some work going on related to KTLS. See for example the [list of (merged) pull requests](https://github.com/openssl/openssl/pulls?q=is%3Apr+author%3AborisPis+is%3Aclosed) by @borisPis.

**Comment by mattcaswell** [comment]
> @mattcaswell Would that mean it would be no longer be possible to get these fields or are there any apis which can do the same ?

There are no APIs that provide this low level of access. As @mspncp says our master branch already has Kernel TLS support integrated though.

**Comment by nidhidamodaran** [comment]
Thanks @mspncp @mattcaswell
