### ISSUE TITLE
Build issue Mingw64 - error: 'struct in_pktinfo' has no member named 'ipi_spec_dst'

### ISSUE THREAD

**Issue by nandaccio** [openssl/openssl#25915]
I have successfully compiled OpenSSL on my Windows system using GCC 13.3.0 at the beginning of October 2024 and the commands below:

 ```
configure mingw64
make
 ```

Today I downloaded a newer version of the repository using the "Download ZIP" functionality, but now I am facing this issue:

 ```
crypto/bio/bss_dgram.c: In function 'pack_local':
crypto/bio/bss_dgram.c:1196:13: error: 'struct in_pktinfo' has no member named 'ipi_spec_dst'
 1196 |         info->ipi_spec_dst      = local->s_in.sin_addr;
      |             ^~
make[1]: *** [Makefile:15355: crypto/bio/libcrypto-lib-bss_dgram.obj] Error 1
make[1]: Leaving directory '/d/Temp'
make: *** [Makefile:3728: build_sw] Error 2
 ```

 ```
   
Command line (with current working directory = .):

    perl ./Configure mingw64

Perl information:

    perl
    5.38.2 for x86_64-msys-thread-multi

Enabled features:

    apps
    argon2
    aria
    asm
    async
    atexit
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    bulk
    cached-fetch
    camellia
    capieng
    winstore
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    default-thread-pool
    deprecated
    des
    dgram
    dh
    docs
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    ecx
    engine
    err
    filenames
    gost
    http
    idea
    legacy
    loadereng
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    ocb
    ocsp
    padlockeng
    pic
    pinshared
    poly1305
    posix-io
    psk
    quic
    unstable-qlog
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm2-precomp
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    ssl-trace
    static-engine
    stdio
    tests
    thread-pool
    threads
    tls
    integrity-only-ciphers
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    acvp-tests             [cascade]        OPENSSL_NO_ACVP_TESTS
    afalgeng               [not-linux]      OPENSSL_NO_AFALGENG
    asan                   [default]        OPENSSL_NO_ASAN
    brotli                 [default]        OPENSSL_NO_BROTLI
    brotli-dynamic         [default]        OPENSSL_NO_BROTLI_DYNAMIC
    buildtest-c++          [default]        
    crypto-mdebug          [default]        OPENSSL_NO_CRYPTO_MDEBUG
    demos                  [default]        OPENSSL_NO_DEMOS
    h3demo                 [default]        OPENSSL_NO_H3DEMO
    devcryptoeng           [default]        OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128    [default]        OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                    [default]        OPENSSL_NO_EGD
    external-tests         [default]        OPENSSL_NO_EXTERNAL_TESTS
    fips                   [default]        
    fips-securitychecks    [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS
    fips-post              [cascade]        OPENSSL_NO_FIPS_POST
    fips-jitter            [default]        OPENSSL_NO_FIPS_JITTER
    fuzz-afl               [default]        OPENSSL_NO_FUZZ_AFL
    fuzz-libfuzzer         [default]        OPENSSL_NO_FUZZ_LIBFUZZER
    jitter                 [default]        OPENSSL_NO_JITTER
    ktls                   [default]        OPENSSL_NO_KTLS
    md2                    [default]        OPENSSL_NO_MD2 (skip crypto/md2)
    msan                   [default]        OPENSSL_NO_MSAN
    pie                    [default]        OPENSSL_NO_PIE
    rc5                    [default]        OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                   [default]        OPENSSL_NO_SCTP
    sslkeylog              [default]        OPENSSL_NO_SSLKEYLOG
    tfo                    [default]        OPENSSL_NO_TFO
    trace                  [default]        OPENSSL_NO_TRACE
    ubsan                  [default]        OPENSSL_NO_UBSAN
    unit-test              [default]        OPENSSL_NO_UNIT_TEST
    uplink                 [no uplink_arch] OPENSSL_NO_UPLINK
    weak-ssl-ciphers       [default]        OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                   [default]        OPENSSL_NO_ZLIB
    zlib-dynamic           [default]        OPENSSL_NO_ZLIB_DYNAMIC
    zstd                   [default]        OPENSSL_NO_ZSTD
    zstd-dynamic           [default]        OPENSSL_NO_ZSTD_DYNAMIC
    ssl3                   [default]        OPENSSL_NO_SSL3
    ssl3-method            [default]        OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "qc",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    OBJCOPY => "objcopy",
    RANLIB => "ranlib",
    RC => "windres",
    asm_arch => "x86_64",
    bin_cflags => "",
    bin_lflags => "",
    bn_ops => "SIXTY_FOUR_BIT",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-m64",
    cppflags => "-DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT",
    defines => [ "OPENSSL_BUILDING_OPENSSL" ],
    disable => [  ],
    dso_scheme => "win32",
    enable => [  ],
    ex_libs => "-lws2_32 -lgdi32 -lcrypt32",
    includes => [  ],
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DL_ENDIAN",
    lib_defines => [  ],
    module_cflags => "",
    module_cxxflags => undef,
    module_ldflags => "-static-libgcc -shared -Wl,--enable-auto-image-base",
    multilib => "64",
    perl_platform => "mingw",
    perlasm_scheme => "mingw64",
    shared_argfileflag => "\@",
    shared_cflag => "",
    shared_cppflags => "_WINDLL",
    shared_defflag => "",
    shared_defines => [  ],
    shared_impflag => "-Wl,--out-implib=",
    shared_ldflag => "-static-libgcc -shared -Wl,--enable-auto-image-base",
    shared_rcflag => "--target=pe-x86-64",
    shared_target => "mingw-shared",
    sys_id => "MINGW64",
    thread_defines => [  ],
    thread_scheme => "winthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OBJCOPY = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = ar
    ARFLAGS         = qc
    ASFLAGS         = 
    CC              = gcc
    CFLAGS          = -Wall -O3
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CXXFLAGS        = 
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    OBJCOPY         = objcopy
    PERL            = perl
    RANLIB          = ranlib
    RC              = windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl

    ```

**Comment by nhorman** [comment]
What version of openssl did you download?

**Comment by nandaccio** [comment]
I downloaded https://github.com/openssl/openssl/archive/refs/heads/master.zip as I did a month ago. The reported version is still 3.5.0-dev, but of course the code is likely different.

I just tried again, but this time with gcc **14.2.0** (Rev2, Built by MSYS2 project), and it worked: this problem seems to affect gcc **13.3.0** when using the mingw profile.

**Comment by nhorman** [comment]
Does msys2 use musl as it's libc implementation?  The missing struct member may have gotten updated in the musl system header files recently

**Comment by CypherpunkSamurai** [comment]
@nhorman No msys2 doesn't use musl.

**Comment by nandaccio** [comment]
Commenting out   info->ipi_spec_dst      = local->s_in.sin_addr; in crypto\bio\bss_dgram.c allows to bypass the compilation error above (not sure about which condition does not work with gcc 13.3.0 with the mingw64 target)
![image](https://github.com/user-attachments/assets/3c0abdc7-21ff-4521-9484-585d9bc838e7)

But there are more errors then:
![image](https://github.com/user-attachments/assets/f75d11a7-8130-4bea-8349-fdf41ea6203d)

For the time being, I am using gcc 14.2.0 as it works without issues, but it might be necessary to look what happens with mingw64 / gcc 13.3.0.

**Comment by CypherpunkSamurai** [comment]
@nandaccio try building from stable release: https://openssl-library.org/source/

**Comment by nandaccio** [comment]
I may not be a regression, I've just tried to compile both OpenSSL 3.4.0 and OpenSSL 3.3.2 (stable) for target mingw64, using gcc 13.3.0:

https://github.com/openssl/openssl/releases/download/openssl-3.4.0/openssl-3.4.0.tar.gz
https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz

```
# ./Configure mingw64
Configuring OpenSSL version 3.4.0 for target mingw64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
```

```
Configuring OpenSSL version 3.3.2 for target mingw64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
```
And it both cases the compilation process ends here:
```
crypto/bio/bss_dgram.c: In function 'pack_local':
crypto/bio/bss_dgram.c:1196:13: error: 'struct in_pktinfo' has no member named 'ipi_spec_dst'
 1196 |         info->ipi_spec_dst      = local->s_in.sin_addr;
      |             ^~
make[1]: *** [Makefile:15109: crypto/bio/libcrypto-lib-bss_dgram.obj] Error 1
make[1]: Leaving directory '/d/Temp'
make: *** [Makefile:3680: build_sw] Error 2
```

So maybe at the beginning of October I used gcc 14.x instead of gcc 13.x, as gcc 14.x (mingw64/Windows) does NOT try to compile extract_local and pack_local, as "# if M_METHOD == M_METHOD_RECVMMSG || M_METHOD == M_METHOD_RECVMSG || M_METHOD == M_METHOD_WSARECVMSG" is FALSE on gcc 14.x, but true on gcc 13.x.

There might be also other issues with gcc 13.x on mingw64, as shown before.

**Comment by rainsdm** [comment]
> I downloaded https://github.com/openssl/openssl/archive/refs/heads/master.zip as I did a month ago. The reported version is still 3.5.0-dev, but of course the code is likely different.
> 
> I just tried again, but this time with gcc **14.2.0** (Rev2, Built by MSYS2 project), and it worked: this problem seems to affect gcc **13.3.0** when using the mingw profile.
> 
> gcc **13.3.0** : ![image](https://private-user-images.githubusercontent.com/13116598/384621527-35501338-6b2d-4038-9550-b6a4be19f00e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjA1NjEsIm5iZiI6MTczNDc2MDI2MSwicGF0aCI6Ii8xMzExNjU5OC8zODQ2MjE1MjctMzU1MDEzMzgtNmIyZC00MDM4LTk1NTAtYjZhNGJlMTlmMDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA1NTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZTIwMTdhYWZiY2U0MmMxMTJlN2M2NjQ2YWIyYjQwMDVmNjg3NDA0NGJhZjRiZjAyYTA3MGM5NjM5ZDZlODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i1_AS0-I8QQLCH8YPWit6I3I0EB7RJ6inFLq1hvPBPs)
> 
> gcc **14.2.0** --> No compilation errors: ![image](https://private-user-images.githubusercontent.com/13116598/384621595-45b4f26a-e501-473a-958b-87a4654b5d3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjA1NjEsIm5iZiI6MTczNDc2MDI2MSwicGF0aCI6Ii8xMzExNjU5OC8zODQ2MjE1OTUtNDViNGYyNmEtZTUwMS00NzNhLTk1OGItODdhNDY1NGI1ZDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA1NTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZGE0MzRhMjRjMDQ4YmJiMGJjODQwMjJmYzlmNzEwZDFlNTk1MGYxOWEwNjY0NDYwN2FlZDVkN2JjNzllMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KjOXSawZtxBaH-5wn8-GtyyOFRwdunlcS2WguLz8Eno)
> 
> Note: perl configdata.pm --dump produces the same output on both toolchains.

I met the same error.

**Comment by nhorman** [comment]
It sounds like you're gcc 13.3.0 version isn't defining _WIN32 or _WIN64.  Try running the following command:
```
echo | gcc -E -dM - | grep WIN
```
on both the 13.3.0 and 14.2.0 compiler.  I would expect that the former isn't defining _WIN64, but the latter is

**Comment by SalvatoreMeschini** [comment]
gcc (Rev2, Built by MSYS2 project) **14.2.0**

#define _WIN64 1
#define __WINT_MAX__ 0xffff
#define __WINT_MIN__ 0
**#define __WIN64 1**
#define __WINNT__ 1
#define __WIN32__ 1
#define __SIZEOF_WINT_T__ 2
#define _WIN32 1
#define __WIN64__ 1
#define WIN32 1
#define WIN64 1
#define __WINT_TYPE__ short unsigned int
#define __WINT_WIDTH__ 16
#define __WIN32 1
#define __WINNT 1
#define WINNT 1

gcc (GCC) *13.3.0*
#define __WINT_MAX__ 0xffffffffU
#define __WINT_MIN__ 0U
#define __SIZEOF_WINT_T__ 4
#define __CYGWIN__ 1
#define __WINT_TYPE__ unsigned int
#define __WINT_WIDTH__ 32

**Comment by nandaccio** [comment]
gcc (Rev2, Built by MSYS2 project) **14.2.0**:

**#define _WIN64 1**
#define __WINT_MAX__ 0xffff
#define __WINT_MIN__ 0
**#define __WIN64 1**
#define __WINNT__ 1
#define __WIN32__ 1
#define __SIZEOF_WINT_T__ 2
#define _WIN32 1
#define __WIN64__ 1
#define WIN32 1
#define WIN64 1
#define __WINT_TYPE__ short unsigned int
#define __WINT_WIDTH__ 16
#define __WIN32 1
#define __WINNT 1
#define WINNT 1

gcc (GCC) **13.3.0**:

#define __WINT_MAX__ 0xffffffffU
#define __WINT_MIN__ 0U
#define __SIZEOF_WINT_T__ 4
#define __CYGWIN__ 1
#define __WINT_TYPE__ unsigned int
#define __WINT_WIDTH__ 32

**Comment by nhorman** [comment]
yeah, thats the problem.   the code in question:
```
#   if !defined(OPENSSL_SYS_WINDOWS) && !defined(OPENSSL_SYS_CYGWIN) && !defined(__FreeBSD__) && !defined(__QNX__)
        info->ipi_spec_dst      = local->s_in.sin_addr;
#   endif
```
is omitted from the build if OPENSSL_SYS_WINDOWS is _not_ defined.

OPENSSL_SYS_WINDOWS is defined here in e_os2.h:
```
# if defined(OPENSSL_SYS_WIN32) || defined(OPENSSL_SYS_WIN64) || defined(OPENSSL_SYS_WINNT) || defined(OPENSSL_SYS_WINCE)
#  undef OPENSSL_SYS_UNIX
#  define OPENSSL_SYS_WINDOWS
#  ifndef OPENSSL_SYS_MSDOS
#   define OPENSSL_SYS_MSDOS
#  endif
# endif
```
if any of OPENSSL_SYS_WINNT, OPENSSL_SYS_WIN32 or OPENSSL_SYS_WIN64 are defined

Those three macros are defined higher up in e_os2.h if the corresponding platform defines are set by the compiler (_WIN32 => OPENSSL_SYS_WIN32, _WIN64 => OPENSSL_SYS_WIN64)

The problem here is that, for whatever reason, gcc 13.3.0 hasn't defined _WIN32 or _WIN64.

**Comment by nandaccio** [comment]
I also tried to manually modify (as a quick&dirty workaround) CFLAGS=-Wall -O3 to CFLAGS=-Wall -O3 -D_WIN64=1 -DWIN64=1 -DWIN32=1 -DWINNT=1 -DWINT_WIDTH=16 -D__WIN64=1 -D_WIN32=1 in the makefile, but gcc 13.3.0 did not like it:

gcc  -I. -Iinclude -Iapps/include  -m64 -Wall -O3 -D_WIN64=1 -DWIN64=1 -DWIN32=1 -DWINNT=1 -DWINT_WIDTH=16 -D__WIN64=1 -D_WIN32=1 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib64/engines-3\"" -DMODULESDIR="\"/usr/local/lib64/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF apps/lib/libapps-lib-app_libctx.d.tmp -c -o apps/lib/libapps-lib-app_libctx.obj apps/lib/app_libctx.c
In file included from include/openssl/x509.h:41,
                 from apps/include/apps.h:27,
                 from apps/lib/app_libctx.c:10:
include/openssl/sha.h:111:16: error: expected ':', ',', ';', '}' or '__attribute__' before 'h'
  111 |     SHA_LONG64 h[8];
      |                ^
make[1]: *** [Makefile:5657: apps/lib/libapps-lib-app_libctx.obj] Error 1

![Image](https://github.com/user-attachments/assets/f7d78472-2515-45a2-be61-11440ebee11f)

**Comment by nandaccio** [comment]
Thank you, actually they are 2 very different compilers:

![Image](https://github.com/user-attachments/assets/3f13bcd3-4432-4b03-9e8f-cc39cf91c216)

It may be useful to know that these packages can compile openssl on **Windows/mingw**:
mingw-w64-x86_64-gcc 14.2.0-2
mingw-w64-ucrt-x86_64-gcc 14.2.0-2

While (as more or less expected) gcc 13.3.0-1 can't.

**Comment by nandaccio** [comment]
So, given the following compilers on Windows:

![Image](https://github.com/user-attachments/assets/927371fb-89a1-4e25-8fd8-5101f7fc48df)

./configure mingw64 --> Works with 14.2.0-2
./configure Cygwin-x86_64 --> Works with 13.3.0-1
