### ISSUE TITLE
compile failed on aarch64-linux platform

### ISSUE THREAD

**Issue by zorrorffm** [openssl/openssl#9173]
After updating code through git pull command, the latest commit is e24bdcde5a80a7edeb1e0dbbcf45c3353a974974,  I compile project and get below failure.

06:14:57 ${LDCMD:-gcc} -pthread -Wa,--noexecstack -Wall -O3 -L.   \
06:14:57 	-o test/sparse_array_test test/sparse_array_test-bin-sparse_array_test.o \
06:14:57 	 test/libtestutil.a libcrypto.a -ldl -pthread 
06:14:57 ${LDCMD:-gcc} -pthread -Wa,--noexecstack -Wall -O3 -L.   \
06:14:57 	-o test/x509_internal_test test/x509_internal_test-bin-x509_internal_test.o \
06:14:57 	 test/libtestutil.a libcrypto.a -ldl -pthread 
06:14:58 libcrypto.a(libcrypto-lib-gcm128.o): In function `CRYPTO_gcm128_init':
06:14:58 gcm128.c:(.text+0x74): undefined reference to `gcm_gmult_4bit'
06:14:58 gcm128.c:(.text+0x7c): undefined reference to `gcm_ghash_4bit'
06:14:58 gcm128.c:(.text+0x134): undefined reference to `gcm_gmult_4bit'
06:14:58 gcm128.c:(.text+0x138): undefined reference to `gcm_ghash_4bit'

It seems this error was introduced by commit a9bb7e9270d26416cc387bc0777c18f9690e2302.  After deleting '$MODESDEF_aarch64=GHASH_ASM' in crypto/modes/build.info,  I can compile project successfully.

**Comment by mspncp** [comment]
Did you rerun your configure command between pulling the new commits and rebuilding?

**Comment by zorrorffm** [comment]
Yes,  I had rerun my configure command.

Actually, the code before my pulling new commits doesn't enalbe macro GHASH_ASM while the new pulling code does.   

The failure is reported because function CRYPTO_gcm128_init will use gcm_gmult_4bit which whould be implemented only if macro GHASH_ASM is disable.

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by levitte** [comment]
That might be related to #9166... Can you check if that change is part of your checkout?

**Comment by levitte** [comment]
If that's the case, I can probably fix later today

**Comment by levitte** [comment]
Ah, now I saw @zorrorffm's last comment.  I came the same conclusion, see #9178
