### PR TITLE
Disable devcryptoeng on newer OpenBSD versions [1.1.1]

### LINKED ISSUE #10552: OpenSSLl 1.1.1d does not compile on default OpenBSD 6.6 setup
OpenSSL 1.1.1d build fails on default OpenBSD 6.6 (amd64) setup:
````
./config --prefix=/home/disik/tmp/openssl
gmake install
<...> [https://pastebin.com/2c8h00HM](https://pastebin.com/2c8h00HM)
cc  -I. -Icrypto/include -Iinclude -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/disik/tmp/openssl/ssl\"" -DENGINESDIR="\"/home/disik/tmp/openssl/lib/engines-1.1\"" -D_THREAD_SAFE -D_REENTRANT -DNDEBUG  -MMD -MF crypto/engine/eng_devcrypto.d.tmp -MT crypto/engine/eng_devcrypto.o -c -o crypto/engine/eng_devcrypto.o crypto/engine/eng_devcrypto.c
crypto/engine/eng_devcrypto.c:40:43: warning: declaration of 'struct session_op' will not be visible outside of this function [-Wvisibility]
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:41:39: error: incomplete definition of type 'struct session_op'
    if (ioctl(cfd, CIOCFSESSION, &sess->ses) < 0) {
                                  ~~~~^
crypto/engine/eng_devcrypto.c:40:43: note: forward declaration of 'struct session_op'
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:41:20: error: use of undeclared identifier 'CIOCFSESSION'
    if (ioctl(cfd, CIOCFSESSION, &sess->ses) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:45:21: error: invalid application of 'sizeof' to an incomplete type 'struct session_op'
    memset(sess, 0, sizeof(struct session_op));
                    ^     ~~~~~~~~~~~~~~~~~~~
crypto/engine/eng_devcrypto.c:40:43: note: forward declaration of 'struct session_op'
static int clean_devcrypto_session(struct session_op *sess) {
                                          ^
crypto/engine/eng_devcrypto.c:60:23: error: field has incomplete type 'struct session_op'
    struct session_op sess;
                      ^
crypto/engine/eng_devcrypto.c:60:12: note: forward declaration of 'struct session_op'
    struct session_op sess;
           ^
crypto/engine/eng_devcrypto.c:78:48: error: use of undeclared identifier 'CRYPTO_DES_CBC'
    { NID_des_cbc, 8, 8, 8, EVP_CIPH_CBC_MODE, CRYPTO_DES_CBC },
                                               ^
crypto/engine/eng_devcrypto.c:91:50: error: use of undeclared identifier 'CRYPTO_ARC4'; did you mean 'CRYPTO_free'?
    { NID_rc4, 1, 16, 0, EVP_CIPH_STREAM_CIPHER, CRYPTO_ARC4 },
                                                 ^~~~~~~~~~~
                                                 CRYPTO_free
include/openssl/crypto.h:271:6: note: 'CRYPTO_free' declared here
void CRYPTO_free(void *ptr, const char *file, int line);
     ^
crypto/engine/eng_devcrypto.c:114:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:116:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:118:7: error: use of undeclared identifier 'CRYPTO_CAMELLIA_CBC'
      CRYPTO_CAMELLIA_CBC },
      ^
crypto/engine/eng_devcrypto.c:126:21: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
    for (i = 0; i < OSSL_NELEM(cipher_data); i++)
                    ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:165:28: error: use of undeclared identifier 'COP_ENCRYPT'
    cipher_ctx->op = enc ? COP_ENCRYPT : COP_DECRYPT;
                           ^
crypto/engine/eng_devcrypto.c:165:42: error: use of undeclared identifier 'COP_DECRYPT'
    cipher_ctx->op = enc ? COP_ENCRYPT : COP_DECRYPT;
                                         ^
crypto/engine/eng_devcrypto.c:168:20: error: use of undeclared identifier 'CIOCGSESSION'
    if (ioctl(cfd, CIOCGSESSION, &cipher_ctx->sess) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:181:21: error: variable has incomplete type 'struct crypt_op'
    struct crypt_op cryp;
                    ^
crypto/engine/eng_devcrypto.c:181:12: note: forward declaration of 'struct crypt_op'
    struct crypt_op cryp;
           ^
crypto/engine/eng_devcrypto.c:220:20: error: use of undeclared identifier 'CIOCCRYPT'
    if (ioctl(cfd, CIOCCRYPT, &cryp) < 0) {
                   ^
crypto/engine/eng_devcrypto.c:314:47: error: use of undeclared identifier 'COP_ENCRYPT'
                           (cipher_ctx->op == COP_ENCRYPT));
                                              ^
crypto/engine/eng_devcrypto.c:340:30: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
static int known_cipher_nids[OSSL_NELEM(cipher_data)];
                             ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:342:41: error: invalid application of 'sizeof' to an incomplete type 'const struct cipher_data_st []'
static EVP_CIPHER *known_cipher_methods[OSSL_NELEM(cipher_data)] = { NULL, };
                                        ^~~~~~~~~~~~~~~~~~~~~~~
include/internal/nelem.h:13:34: note: expanded from macro 'OSSL_NELEM'
# define OSSL_NELEM(x)    (sizeof(x)/sizeof((x)[0]))
                                 ^~~
crypto/engine/eng_devcrypto.c:347:23: error: variable has incomplete type 'struct session_op'
    struct session_op sess;
                      ^
crypto/engine/eng_devcrypto.c:60:12: note: forward declaration of 'struct session_op'
    struct session_op sess;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
gmake[1]: *** [Makefile:3160: crypto/engine/eng_devcrypto.o] Error 1
gmake[1]: Leaving directory '/home/disik/tmp/openssl-1.1.1d'
gmake: *** [Makefile:177: build_libs] Error 2
````

### PR DESCRIPTION
**Pull request by levitte**
It's reported that /dev/crypto support has been dropped in OpenBSD 5.7.

Fixes #10552

### CODE REVIEW

**Comment by levitte** [comment]
Ah, I see what happened with your test, @denis1482.  I just added a commit that i think should fix things.  Please try again?

**Comment by denis1482** [comment]
With this latest fix OpenSSL 1.1.1d builds without an error on OpenBSD 6.6
Thank you @levitte

**Comment by levitte** [comment]
Ping!  Anyone?

**Comment by levitte** [comment]
Ping!

**Review by t-j-h — APPROVED** [review]

**Comment by levitte** [comment]
Merged.

2b5827df6d6a4db4e190114a31540b413376b1e5 Disable devcryptoeng on newer OpenBSD versions
a53a694c575308e1511878f3466e9d01cda6ac3a Configuration: compute openssl_other_defines and related info later

**Comment by noloader** [comment]
What is the option we should use to disable the `/dev/crypto` until the next release? Is it `no-devcryptoeng`, or am I parsing 2b5827d incorrectly?

**Comment by mattcaswell** [comment]
> What is the option we should use to disable the /dev/crypto until the next release?

`no-devcryptoeng` should do it.

**Comment by mattcaswell** [comment]
...but it should also be disabled automatically on newer BSDs from 1.1.1e
