### PR TITLE
Fix build on illumos with gcc 5.3

### PR DESCRIPTION
**Pull request by pyhalov**
gcc 5.3 defines STDC_VERSION to 201112L (c99), together with _XOPEN_SOURCE 500 this leads to compilation error in feature-tests.h ("Compiler or options invalid for pre-UNIX 03 X/Open applications and pre-2001 POSIX applications").

### CODE REVIEW

**Comment by richsalz** [comment]
Duplicate of #1066, closing.

**Comment by ghedo** [comment]
@richsalz I think the idea was to have a PR for master (this one) and one for 1.0.2 (#1066).

**Comment by richsalz** [comment]
Ah, did I miss that?
I think backporting one for just a simple change is easier.
But still, why doesn't this break ALL sun builds?

**Comment by pyhalov** [comment]
This doesn't break all builds, because gcc 5.3 defaults to c99, defines __STDC_VERSION__ to 2011112L, and so should define _XOPEN_SOURCE to at least 600, according to sys/feature_tests.h. The better option usually is just don't touch _XOPEN_SOURCE and let system headers find out appropriate versions for the macroses. 
I've checked that without any special defines S_IFBLK and S_IFCHR are defined for gcc 4.9/5.3 and Sun Studio 12.1 on OpenIndiana.

**Comment by richsalz** [comment]
Thanks for the followup.  Others on the team will have to review.  @dot-asm ?

**Comment by dot-asm** [comment]
I've mentioned it earlier elsewhere, such definitions don't belong in source code files but should appear on command line (if actually justified). And if they for whatever (likely bad) reason have to appear in source code they may not appear past first #include directive. This kind of means that I kind of refuse to review anything else but *removal* of the said definition. So that you have to call upon somebody else, @richsalz :-) What I can do in the context is to assess what is the risk of breakage from removal by testing it on bunch of systems...

**Comment by richsalz** [comment]
@dot-asm I prefer your approach.
