### PR TITLE
testutil/driver.c: Fix function prototype warning [-Wstrict-prototypes]

### PR DESCRIPTION
**Pull request by mspncp**
[extended tests]

(introduced by commit 91860165820d, which added -Wstrict-prototypes)

### CODE REVIEW

**Comment by mspncp** [comment]
```
gcc  -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wformat -Wtype-limits -Wundef -Werror -Wall -O0 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/msp/install/openssl/ssl\"" -DENGINESDIR="\"/home/msp/install/openssl/lib/engines-1.1\""   -MMD -MF test/testutil/driver.d.tmp -MT test/testutil/driver.o -c -o test/testutil/driver.o test/testutil/driver.c
test/testutil/driver.c:77:12: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 static int should_report_leaks()
            ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:6332: test/testutil/driver.o] Error 1
```

**Comment by mspncp** [comment]
BTW: why wasn't this caught by the extended tests of #6542? Is there no build with `enable-crypto-mdebug`?

**Comment by mspncp** [comment]
Travis failure is unrelated:

```
../../util/shlib_wrap.sh sh ../../test/recipes/95-test_external_pyca_data/cryptography.sh => 1
not ok 1 - running Python Cryptography tests
```

**Comment by mspncp** [comment]
Merged, thanks!
