### ISSUE TITLE
undefined reference to `private_MD5_Init'

### ISSUE THREAD

**Issue by vanand123** [openssl/openssl#17837]
After upgrading openssl from 1.0.1 to 1.1.1, compilation got failed with below error:
```
undefined reference to `private_MD5_Init'
collect2: error: ld returned 1 exit status
```

**Code Block:**
```
static unsigned char* _MD5_local(const unsigned char* d, size_t n, unsigned char* md)
{
        MD5_CTX c;

        if (!private_MD5_Init(&c))
        {
                return NULL;
        }

        MD5_Update(&c, d, n);

        MD5_Final(md, &c);

        return md;
}
```

**Text Symbol Comparison:**
```
bash-4.1$nm -C -A libcrypto.so.1.0.1 | grep -i "private_Md5_Init"
libcrypto.so.1.0.1:000aaa1d T private_MD5_Init

bash-4.1$nm -C -A libcrypto.so.1.1 | grep -i "private_Md5_Init"
libcrypto.so.1.1:0018b546 t private_MD5_Init

T : Global text symbol.
t : Local text symbol.
```

Does it mean that we can't use "private_Md5_Init" with openssl 1.1.1 onwards? If so, Is there any similar API for same functionality?

**Comment by tmshort** [comment]
Correct. That function was named "private" and should not have been used.
There are MD5 APIs available in 1.1.1: https://www.openssl.org/docs/man1.1.1/man3/MD5_Init.html
In 3.0, those "algorithm-specific" APIs have been deprecated, and new EVP methods should be used.
https://www.openssl.org/docs/man3.0/man7/migration_guide.html

**Comment by t8m** [comment]
private_MD5_Init was a FIPS specific hack. You can just use MD5_Init() instead.

However what Todd wrote above applies if you plan to migrate to 3.0 at some point.

**Comment by vanand123** [comment]
After replacing "private_Md5_Init" with "MD5_Init" in the same above code block, the code is not giving any error during compilation but it is crashing in FIPS mode.
The stacktrace is as below:
```
#0 0xf7721430 in __kernel_vsyscall ()
#1 0xf691c2a7 in raise () from /usr/lib/libc.so.6
#2 0xf691dae3 in abort () from /usr/lib/libc.so.6
#3 0xf7186a0f in OPENSSL_die () from /usr/local/cm/lib/libcrypto.so.1.1
#4 0xf7245524 in MD5_Init () from /usr/local/cm/lib/libcrypto.so.1.1
#5 0x567e6f8b in _MD5_local (md=0xf0af38b4 "", n=4, d=<optimized out>) at Test.cpp:194
```
**Note:** Using custom openssl with "FIPS Object Module" to make openssl 1.1.1 as FIPS Compliant.

**Comment by paulidale** [comment]
There is no FIPS object module for 1.1.1.  There never will be.
1.1.1 is fundamentally not FIPS compliant.

**Comment by t8m** [comment]
> **Note:** Using custom openssl with "FIPS Object Module" to make openssl 1.1.1 as FIPS Compliant.

Then please report the issue to the authors of the customization. We are sorry, as this is not something we provide we cannot help with resolving the issues with that code.
