### ISSUE TITLE
Build Failure on GCC 7: Missing Intrinsic _mm256_set_m128i in OpenSSL 4.0.0

### ISSUE THREAD

**Issue by neeraj210287** [openssl/openssl#30958]
Description:
I am reporting a build failure encountered when compiling the OpenSSL 4.0.0 final release on a host using GCC 7 (specifically x86_64-suse-linux/7).

Error Message:
The build fails during the compilation of AVX2-optimized code:
crypto/evp/enc_b64_avx2.c: error: implicit declaration of function ‘_mm256_set_m128i’

Technical Context:
The file crypto/evp/enc_b64_avx2.c utilizes the _mm256_set_m128i() intrinsic. This intrinsic was introduced in GCC 8, making it unavailable for older toolchains like GCC 7. While the [OpenSSL 4.0.0 release notes](https://openssl-library.org/post/2026-04-14-openssl-40-final-release/) mention a move toward [C99 compliance](https://sourcegraph.com/github.com/openssl/openssl/-/blob/NEWS.md), there is no explicit mention that the minimum GCC version has effectively been raised to GCC 8 for x86_64 builds using default optimizations.
Request for Clarification/Action:

Documentation: Should the release notes or INSTALL.md be updated to reflect this higher compiler requirement for x86_64 AVX2 support?

Build System: Is there a planned fix for the Configure script to detect the absence of this intrinsic and gracefully fall back to non-AVX2 code for GCC 7 users?

Environment Details:
OpenSSL Version: 4.0.0 Final
OS: SUSE Linux
Compiler: GCC 7.x
Architecture: x86_64

**Comment by nhorman** [comment]
Our platform policy:
 https://share.google/dXzQnKfzot2KFJ8qJ

Lists the minimal compiler needed for all our supported platforms

Gcc 9 has been the minimum for our x8664 platforms for some time

**Comment by petrovr** [comment]
Hello,

На 25.04.26 г. в 4:05, Neil Horman написа:
> nhorman left a comment (openssl/openssl#30958)
> 
> Our platform policy:
>   https://share.google/dXzQnKfzot2KFJ8qJ
> 
> Lists the minimal compiler needed for all our supported platforms
> 
> Gcc 9 has been the minimum for our x8664 platforms for some time

A) linux-x86_64 		Ubuntu Server 20.04 		x86_64 		gcc 9

B)

Ubuntu 20.04 LTS

Model: Ubuntu 20.04 LTS (Focal Fossa)
Version: 20.04
Release Date: April 23, 2020
Minimum Requirements:

     Processor: 2 GHz dual-core processor
     RAM: 4 GiB
     Storage: 25 GB of free hard drive space
     Display: VGA capable of 1024x768 screen resolution

Supported Architectures: AMD64/EM64T (e.g., Athlon64, Opteron, EM64T Xeon, Core 2)

AVX2 out of requirements!

...


Modern Linux enterprise requires x86-64-v2 and avx2 is not in requirements.

---

Does not make sense to use GCC requirements to override Linux requirements.


It seems to me this code should be activated only if is requested explicitly.

It the future releases like OpenSSL 5 user should be able to exclude avx2 requirements.


Regards,
Roumen Petrov

**Comment by petrovr** [comment]
На 24.04.26 г. в 11:00, neeraj210287 написа:
> neeraj210287 created an issue (openssl/openssl#30958)
> 
> Description:
> I am reporting a build failure encountered when compiling the OpenSSL 4.0.0 final release on a host using GCC 7 (specifically x86_64-suse-linux/7).


This Linux distribute "newer" complier versions, but software with OpenSSL 4.0 cannot be distributed.


> 
> Error Message:
> The build fails during the compilation of AVX2-optimized code:
> crypto/evp/enc_b64_avx2.c: error: implicit declaration of function ‘_mm256_set_m128i’


If I'm not wrong assembler code detects CPU and used different code paths.

Does the same apply to C-code?
If 4.0 is build with a "newer" compiler, does code run on an "old" CPU?


[SNIP]
Roumen

**Comment by beldmit** [comment]
> Does the same apply to C-code? If 4.0 is build with a "newer" compiler, does code run on an "old" CPU?

Yes. At least there were special efforts to have run-time detection of AVX instructions availabilty, and would consider it a bug if it doesn't work this way

**Comment by nhorman** [comment]
ok, so what you're asserting here is that, if you use gcc9, the build completes properly, but if you then run it on an older  processor that does not contain AVX2 support, you get a runtime failure, correct?

Assuming that is the case, yeah, that looks like a bug.  It seems to have been introduced with commit 3a69b190289, which does build time detection of AVX2 (using #ifdef (__AVX2__) ), so we get those instructions in code weather or not they are present at run time.

**Comment by esyr** [comment]
Compiler command has to include the relevant `-m` option (that enables compile-time usage of relevant instructions) in order for `#ifdef (__AVX2__)` path to take place, I don't think it's an issue in the code introduced by the commit.

**Comment by neeraj210287** [comment]
Hello Team,

We tried to compile the code using "Default System Compiler" provided by SLE15 SP6. But my point is, if minimum gcc compiler version is there for OpenSSL, that should be mentioned in release notes or provide the link of that particular section from where user's can get the information regarding minimum supported compiler version.

Thanks,
Neeraj Gupta

**Comment by esyr** [comment]
> if minimum gcc compiler version is there for OpenSSL

I don't think this is the case;  there's a "minimum supported compiler version", a compiler version for which CI is run (as generally outlined in [1]), but if there's a PR submitted that enables compilation for older versions, it can be considered for inclusion (as usually those don't incur dramatic ongoing maintenance costs), like [2], for example.

[1] https://openssl-library.org/policies/general/platform-policy/
[2] https://github.com/openssl/openssl/pull/30901

**Comment by nhorman** [comment]
@neeraj210287 I think what you're saying is that, if a given distribution has a compiler that we no longer support, we should mention in the release notes how to work around that?

We can't do that for every change we make, when we decide to update our compiler support profile.  Some changes can't be overcome (though this one can, in exactly the way @esyr mentions).  The onus to discover that is on the builder, otherwise we would spend indordinate amounts of time describing how to build openssl large numbers of tools we no longer support

**Comment by neeraj210287** [comment]
@nhorman, I understand that team can't describe how to build the openssl on all the compiler versions. But, my point is it's better if team mentioned the link of platform policy into release notes for reference. 
I'm fully agree with your point that we or builder need to identify, how to compile the library in old compilers. 

Thanks everyone for your time and support

**Comment by mbroz** [comment]
The same problem is for MSVC 2013, even if fixed basic compilation stuff, it ends with ``error LNK2019: unresolved external symbol _mm256_extract_epi8`` ...

**Comment by petrovr** [comment]
Hello,

На 28.04.26 г. в 17:05, Milan Broz написа:
> mbroz left a comment (openssl/openssl#30958)
> 
> The same problem is for MSVC 2013, even if fixed basic compilation stuff, it ends with ``error LNK2019: unresolved external symbol _mm256_extract_epi8`` ...

OpenSSL team will respond - not according polices.

Do not support default compiler from some Linux enterprise edition does not look good. Also, build time solution does not seem difficult to implement.

Regards
Roumen

**Comment by mbroz** [comment]
Supporting old compilers is sometimes complicated, but we should not break it if there is no strong reason.

IMO this specific AVX2 case should be simple to fix , stand by, please.

**Comment by thesamesam** [comment]
This still fails in some cases: https://github.com/openssl/openssl/issues/31199
