### ISSUE TITLE
OpenSSL 3.4 returning undefined reference to EVP_MD_CTX_get_size_ex

### ISSUE THREAD

**Issue by alex-rowe** [openssl/openssl#26621]
We are building Fluent Bit on an Ubuntu 22 docker image that has our OpenSSL configured for FIPS.

We have been building against OpenSSL FIPS 3.3, and the builds were working fine.

We've recently had a change to use OpenSSL FIPS 3.4 and our builds stop working now during the `make` stage of compiling Fluent Bit.

Our dockerfile is almost 1:1 to https://github.com/fluent/fluent-bit/blob/master/packaging/distros/ubuntu/Dockerfile, just removing anything that isn't Ubuntu 22.04, and we have OpenSSL FIPS added to our base image.

At the end of running `make` we receive the below error:

```
[100%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libfluent-bit.a(flb_hash.c.o): in function `flb_hash_init':
/tmp/fluent-bit/src/flb_hash.c:72: undefined reference to `EVP_MD_CTX_get_size_ex'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:416: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:8608: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

The offending line is https://github.com/fluent/fluent-bit/blob/master/src/flb_hash.c#L72

```
context->digest_size = EVP_MD_CTX_size(context->backend_context);
```

From what I can see in the 3.4 changelog, the use of `EVP_MD_CTX_size` should be now pointing to `EVP_MD_CTX_get_size_ex`, and that's the error that we get, but it's saying that `EVP_MD_CTX_get_size_ex` is undefined.

Below are the OpenSSL versions and providers being used

```
# openssl version -a
OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)
built on: Thu Jan 30 12:29:10 2025 UTC
platform: linux-aarch64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib64/engines-3"
MODULESDIR: "/usr/local/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x8fd

# openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.4.0
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.0.9
    status: active
```

Previously this was tested and working in `OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)`. The only change so far has been OpenSSL 3.3 to 3.4.

We need to also use the FIPS Provider that is a FIPS validated module, and `3.0.9` is the latest for that.

Why would `EVP_MD_CTX_get_size_ex` be showing as undefined is we're on the `3.4.0` branch, of is that due to the difference between versions of the FIPS and default providers?

**Comment by paulidale** [comment]
My guess would be that you are picking up a system or other installation of OpenSSL that predates this call.

**Comment by alex-rowe** [comment]
Looking through the output of `cmake` it showed this

```
Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "3.0.2") 
```

Which was picking up the old system OS installation

Adding an environment variable for `OPENSSL_ROOT_DIR=/usr/local`, made it show

```
Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "3.4.0")  
```

Which is the correct version, but no the correct version of `libcrypto.so`

Adding another environment variable for `PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig` which had all the `.pc` files of where the new `.so` libraries are got it working

```
Found OpenSSL: /usr/local/lib64/libcrypto.so (found version "3.4.0")
```

I'll close this one out now and leave this for anyone else with the same issue.
