### PR TITLE
Fix DTLS1_BAD_VER (Cisco AnyConnect VPN) support (for 1.0.2)

### PR DESCRIPTION
**Pull request by dwmw2**
Selected backports from PR #1296 (for HEAD/1.1) to 1.0.2.

Needed to lift some of `packet_locl.h` from HEAD, and some of `tls1_PRF()` from `ssl/t1_enc.c`, to make the test case functional. Otherwise it's basically the same code modulo OpenSSL API differences and the lack of `EVP_md5_sha1()`.

There is perhaps a case to be made for omitting the ubsan `satsub64be()` fix from 1.0.2, since it was never going to be a problem in *practice* and we don't actually have the ubsan build support in 1.0.2.
There is also a case for not having known "undefined" behaviour now that we know it's there though, too :)

### CODE REVIEW

**Comment by dwmw2** [comment]
WTAF. Trying this in an attempt to get the test case to build on Windows...
```
#ifdef OPENSSL_SYS_WINDOWS
/* WTF? <openssl/rand.h> includes <windows.h> and breaks the build with winsock crap */
extern int RAND_bytes(unsigned char *buf, int num);
#else
#include <openssl/rand.h>
#endif
```

**Comment by dwmw2** [comment]
Now that PR #1296 is merged (thanks) I've cherry-picked these commits again, to explicitly reference the commits in master. In doing so it's preserved the original 'Reviewed-by' tags in the commit messages. Please let me know if I should have manually removed those to allow a specific review for 1.0.2.

I note that 1.0.1 is also currently broken (since 1.0.1q), and wants at least the 'Fix SSL_export_keying_material' fix. It also has the undefined behaviour in `satsub64be()` but the argument for leaving it alone there (on the basis that it's purely theoretical) is even stronger than for 1.0.2.

**Comment by dwmw2** [comment]
Collapsed the final 'add test case' commit in both 1.0.2 and 1.0.1 branches to incorporate the later cleanups from commit eb633d03fe2db3.

**Comment by dwmw2** [comment]
Updated to resolve (trivial Makefile) conflicts with the other DTLS test that's just been added...
1.0.1 branch also updated.

**Comment by dwmw2** [comment]
Please don't make new 1.0.1 and 1.0.2 releases without at least the `Fix SSL_export_keying_material() for DTLS1_BAD_VER` patch.

I've blacklisted the current versions of OpenSSL 1.0.[12] as broken in OpenConnect's configure script, and have assumed that 1.0.1u and 1.0.2i will be fixed...

Now I've added a test case, I'm *hoping* never to have to add to my collection in
http://git.infradead.org/users/dwmw2/openconnect.git/blob/5c6163a:/configure.ac#l539

**Comment by richsalz** [comment]
@mattcaswell , can you review for 1.0.2 ?

**Comment by dwmw2** [comment]
The new test failures in my latest push don't look like they're mine.
```
ca.c:2119:24: error: expression which evaluates to zero treated as a null
      pointer constant of type 'OPENSSL_STRING' (aka 'char *')
      [-Werror,-Wnon-literal-null-conversion]
    row[DB_rev_date] = '\0';
                       ^~~~
``` 
I'm going to blame that on commit a03f81f4e and @richsalz

**Comment by dwmw2** [comment]
Test failures still Not My Fault™:
```
s_cb.c:551:33: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                   (void *)bio, argp, (unsigned long)argi, ret, ret);
                                ^~~~
s_cb.c:556:33: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
                   (void *)bio, argp, (unsigned long)argi, ret, ret);
                                ^~~~
```

**Comment by mattcaswell** [comment]
+1 from me.
@richsalz can you reconfirm, I think there have been some minor tweaks since your review.

**Comment by richsalz** [comment]
Still +1

**Comment by mattcaswell** [comment]
Pushed. Thanks!

**Comment by dwmw2** [comment]
Thanks. And at least the SSL_export_keying_material() one for 1.0.1 please?

**Comment by mattcaswell** [comment]
1.0.1 is only receiving security fixes, so this doesn't qualify for backporting. It's out of support completely in 4 months.

**Comment by dwmw2** [comment]
Hmm, even for regressions? This *used* to work in 1.0.1...

**Comment by mattcaswell** [comment]
That's a good question actually...I'll raise it with the team

**Comment by richsalz** [comment]
+1

**Comment by mattcaswell** [comment]
Cherry picked the SSL_export_keying_material() commit to 1.0.1 based on internal team discussion.
