### ISSUE TITLE
OQS external test failure

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#19296]
OQS test failed, found in #18852 

https://github.com/openssl/openssl/actions/runs/2751220188/jobs/4323839531
```
[ 14%] Building C object oqsprov/CMakeFiles/oqsprovider.dir/oqsprov_keys.c.o
4063
/home/runner/work/openssl/openssl/oqs-provider/oqsprov/oqsprov_keys.c:75:32: error: 'OQS_SIG_alg_rainbow_I_classic' undeclared here (not in a function); did you mean 'OQS_SIG_alg_rainbow_V_classic'?
4064
   75 |        { 0, "rainbowIclassic", OQS_SIG_alg_rainbow_I_classic, KEY_TYPE_SIG, 128 },
4065
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4066
      |                                OQS_SIG_alg_rainbow_V_classic
4067
make[4]: *** [oqsprov/CMakeFiles/oqsprovider.dir/build.make:104: oqsprov/CMakeFiles/oqsprovider.dir/oqsprov_keys.c.o] Error 1
```

**Comment by mattcaswell** [comment]
Did you mean #18852?

**Comment by mattcaswell** [comment]
@baentsch

**Comment by beldmit** [comment]
> Did you mean #18852?

Sure, sorry.

**Comment by baentsch** [comment]
Would it be possible to initiate a test re-run? Per the [log file this is a run "failed on 28 Jul in 15m 56s "](https://github.com/openssl/openssl/actions/runs/2751220188/jobs/4323839531): Since then (on Sep 9, to be precise), the oqs-provider/subproject reference [got updated](https://github.com/openssl/openssl/pull/19184) making this error impossible -- okok, ...making the error highly unlikely to appear again (I'm enough of a computer scientist to not rule out anything :) --  as the algorithm referenced above got removed then.

**Comment by baentsch** [comment]
Thanks for the re-run, @t8m. https://github.com/openssl/openssl/actions/runs/3150682520/jobs/5123768537 indicates this issue can be closed.

**Comment by beldmit** [comment]
Thanks!
