### ISSUE TITLE
openssl 1.1.1c doesn't compile with AT12.0/ppc64le

### ISSUE THREAD

**Issue by alaingautherot** [openssl/openssl#9519]
Hello,
I'm trying to compile openssl 1.1.1c on ppc64le centos7 using AT12.0 (ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/redhat/RHEL7/at12.0) and even though libraries seem to be compiled, I get link errors on the apps:

> /opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: apps/openssl.o: in function `list_main':
openssl.c:(.text+0x1180): undefined reference to `EVP_PKEY_meth_get_count'
> /opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: openssl.c:(.text+0x11b8): undefined reference to `EVP_PKEY_meth_get0'
> /opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: apps/asn1pars.o: in function `asn1parse_main':
asn1pars.c:(.text+0x448): undefined reference to `ASN1_ITEM_lookup'
> /opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: asn1pars.c:(.text+0x4c4): undefined reference to `ASN1_ITEM_get'
> ...

My guess is that there is a mixup with an SSL library part of the AT12.0 install at /opt/at12.0/lib64/libssl.a

I have attached a full archive with the config + build + bug report: [openssl_ppc64le_build_error.zip](https://github.com/openssl/openssl/files/3463049/openssl_ppc64le_build_error.zip)

Anybody has an idea how to fix this?
Thanks,
Alain

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input
