### ISSUE TITLE
OpenSSL 3.5.0 build fails on OpenEuler 22.03 (AArch64) due to incorrect CFLAGS/CXXFLAGS generation

### ISSUE THREAD

**Issue by prodcd** [openssl/openssl#27832]
**Issue Summary**
OpenSSL 3.5.0 fails to compile on OpenEuler 22.03 with a Kunpeng (AArch64) CPU. The make process aborts with gcc errors, specifically "unrecognized command-line option" or "unknown pass" for standard OpenSSL configure options like --enable-quic, --enable-tls1_3, --with-sm2, --with-sm3, --with-sm4, and --disable-static.

**Detailed Description**
When attempting to build OpenSSL 3.5.0 from source on an OpenEuler 22.03 system with a Kunpeng (AArch64) CPU, the configure script completes successfully. However, the subsequent make command fails.

Upon inspecting the generated Makefile, it was found that the CFLAGS and CXXFLAGS variables incorrectly include the OpenSSL configure options (e.g., --enable-quic, --with-sm2, --disable-static) directly as GCC compiler flags. GCC does not recognize these as valid options, leading to compilation errors.

This issue occurs even when using the recommended configure parameters for enabling HTTP/3 (QUIC) and China's Commercial Cryptography (国密) algorithms. Removing these specific feature flags from the configure command (e.g., trying to compile only with --disable-static) still results in the same type of error for the remaining OpenSSL options that are mistakenly passed to GCC.

Steps to Reproduce
System Environment:

Operating System: OpenEuler 22.03 LTS
Architecture: AArch64 (Kunpeng CPU)
GCC Version: gcc (GCC) 10.3.1
Perl Version: This is perl 5, version 34, subversion 0 (v5.34.0) built for aarch64-linux-thread-multi

Download OpenSSL:

`wget https://www.openssl.org/source/openssl-3.5.0.tar.gz
tar -xzf openssl-3.5.0.tar.gz
cd openssl-3.5.0`

Configure OpenSSL:

`./config --prefix=/usr/local/openssl-3.5.0 --openssldir=/usr/local/openssl-3.5.0 shared zlib --enable-quic --enable-tls1_3 --with-sm2 --with-sm3 --with-sm4 --disable-static`

Attempt to Build:

`make -j$(nproc)`

**Expected Behavior**
The make command should complete successfully, compiling OpenSSL 3.5.0 with the specified features (QUIC, TLS 1.3, SM2/SM3/SM4, shared libraries). The Makefile should correctly translate configure options into appropriate compiler flags (e.g., -D macros) or link commands, rather than passing them directly to GCC.

Actual Behavior
The make command fails with gcc errors. Examples of the errors observed:
`
gcc: error: unrecognized command-line option '--with-sm2'
gcc: error: unrecognized command-line option '--with-sm3'
gcc: error: unrecognized command-line option '--with-sm4'
cc1: error: unknown pass quic specified in '-fenable'
cc1: error: unknown pass tls1_3 specified in '-fenable'
cc1: error: unknown pass static specified in '-fdisable'
`
These errors occur because the generated Makefile (specifically CFLAGS and CXXFLAGS variables, e.g., lines 3799-3800) contains the OpenSSL configure options:`

Makefile
`
CFLAGS=-Wall -O3 --enable-quic --enable-tls1_3 --with-sm2 --with-sm3 --with-sm4 --disable-static
CXXFLAGS=-Wall -O3 --enable-quic --enable-tls1_3 --with-sm2 --with-sm3 --with-sm4 --disable-static`

**Potential Root Cause**
The configdata.pm script or the underlying Makefile.in templates appear to incorrectly concatenate certain configure options directly into CFLAGS and CXXFLAGS, instead of processing them into GCC-compatible compilation flags or internal OpenSSL definitions. This seems to be a Makefile generation bug specific to this version of OpenSSL in this particular environment (OpenEuler 22.03 AArch64).

**Temporary Workaround (Not recommended for production/may not enable all features)**
Manually editing the generated Makefile after config to remove the problematic options from CFLAGS and CXXFLAGS allows the compilation to proceed for basic features. However, this is not a sustainable solution and may prevent the desired features (QUIC, 国密) from being properly enabled.

**Request**
Please investigate this Makefile generation issue for OpenSSL 3.5.0 on AArch64 (OpenEuler 22.03) to ensure that configure options are correctly handled and not mistakenly passed as compiler flags to GCC.

**Comment by t8m** [comment]
There should be no `--` in front of these enable/disable options for the Configure script. There is also no `with-sm2` (or sm3, sm4) option - it is named `enable-sm2` or `no-sm2` if you want to enable sm2 support or disable it. Although it is enabled by default, so you do not have to explicitly enable it. There is no `disable-static` option and TLS-1.3 and QUIC are also enabled by default (and they are unlikely to get disabled by default in any foreseeable time).

A correct command line could be:
```
./config --prefix=/usr/local/openssl-3.5.0 --openssldir=/usr/local/openssl-3.5.0 shared zlib enable-sm2 enable-sm3 enable-sm4
```

That is to be on the safe side with enablement of smx algorithms although they are also currently enabled by default.
