### ISSUE TITLE
curve448: android-armv7 build fails due to unknown uint128_t

### ISSUE THREAD

**Issue by gjasny** [openssl/openssl#14804]
Hello,

this is a regression between 3.0.0-alpha13 and 3.0.0-alpha14. My Android build for armv7 fails (with NDKr21 and ANDROID_API=19). Compilation fails with:

```
clang  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -fPIC -pthread  -target armv7a-linux-androideabi -gcc-toolchain /opt/android-ndk-r21d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r21d/platforms/android-19/arch-arm -Wa,--noexecstack -Qunused-arguments -Wall -O3 -fPIC -ffunction-sections -funwind-tables -fexceptions -fno-strict-aliasing -mfpu=vfp -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/home/ec2-user/54uxy13nulcbcfk/_deploy/Applications_Android_armeabi-v7a_cxx17/openssl\"" -DENGINESDIR="\"/home/ec2-user/54uxy13nulcbcfk/_deploy/Applications_Android_armeabi-v7a_cxx17/lib/engines-3\"" -DMODULESDIR="\"/home/ec2-user/54uxy13nulcbcfk/_deploy/Applications_Android_armeabi-v7a_cxx17/lib/ossl-modules\"" -D__ANDROID_API__=19 -isystem /opt/android-ndk-r21d/sysroot/usr/include/arm-linux-androideabi -isystem /opt/android-ndk-r21d/sysroot/usr/include -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -DNDK_DEBUG=1 -D__ANDROID_API__=19 -MMD -MF crypto/ec/libcrypto-lib-curve25519.d.tmp -MT crypto/ec/libcrypto-lib-curve25519.o -c -o crypto/ec/libcrypto-lib-curve25519.o crypto/ec/curve25519.c
crypto/ec/curve448/arch_64/f_impl.c:19:14: error: expected ';' after expression
    uint128_t accum0 = 0, accum1 = 0, accum2;
             ^
             ;
crypto/ec/curve448/arch_64/f_impl.c:19:5: error: use of undeclared identifier 'uint128_t'
    uint128_t accum0 = 0, accum1 = 0, accum2;
    ^
crypto/ec/curve448/arch_64/f_impl.c:19:15: error: use of undeclared identifier 'accum0'
    uint128_t accum0 = 0, accum1 = 0, accum2;
              ^
```

Thanks,
Gregor

**Comment by gjasny** [comment]
Steps to reproduce (cross-compiled from macos):

```
export ANDROID_NDK_ROOT=~/Android/android-ndk-r21e
PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:$PATH
./Configure android-arm -D__ANDROID_API__=19
make build_libs
```

**Comment by gjasny** [comment]
@amitay This got probably broken by a72da9ecebcd8e9b9caf6a3d05251a7008e9c614 / #14784

**Comment by mattcaswell** [comment]
Hmmm. This  code in Configure is supposed to detect support in the compiler for 128 bit ints:

https://github.com/openssl/openssl/blob/6d9e045ef724df0ddc8c8f66dcfdff4f8ba0bc03/Configure#L1576-L1588

I wonder what goes wrong.

**Comment by amitay** [comment]
Looks like this is a problem of NDK version R21e.

The culprit build command is:

`clang  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include -I../.. -I../../include -I..  /../providers/common/include -I../../providers/implementations/include  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM   -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DS  HA1_ASM -DSHA256_ASM -DSHA512_ASM -fPIC -pthread  -target armv7a-linux-androideabi -gcc-toolchain /home/amitay/d  evel/android-ndk-r21e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/amitay/devel/an  droid-ndk-r21e/platforms/android-19/arch-arm -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELE  TE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/  usr/local/lib/ossl-modules\"" -D__ANDROID_API__=19 -isystem /home/amitay/devel/android-ndk-r21e/sysroot/usr/incl  ude/arm-linux-androideabi -isystem /home/amitay/devel/android-ndk-r21e/sysroot/usr/include -DOPENSSL_BUILDING_OP  ENSSL -DNDEBUG -D__ANDROID_API__=19 -MMD -MF crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.d.tmp -MT crypto/ec  /curve448/arch_64/libcrypto-lib-f_impl.o -c -o crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.o ../../crypto/ec  /curve448/arch_64/f_impl.c`

In this case the CC is set to **clang**.

`
$ clang -E -dM - < /dev/null | grep INT128
`
`
#define __SIZEOF_INT128__ 16
`

However if it used with the right target (armv7a-linux-androideabi), there is no definition of `__SIZEOF_INT128__`
`
$  clang -target armv7a-linux-androideabi -E -dM - < /dev/null | grep INT128
`

If I try NDK version R22b the relevant build command is:

`
armv7a-linux-androideabi19-clang  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include -I../.. -I../../include -I../../providers/common/include -I../../providers/implementations/include  -DAES_ASM -DBSAES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -D__ANDROID_API__=19 -MMD -MF crypto/ec/libcrypto-lib-curve25519.d.tmp -MT crypto/ec/libcrypto-lib-curve25519.o -c -o crypto/ec/libcrypto-lib-curve25519.o ../../crypto/ec/curve25519.c
`

In this case, CC is set to **armv7a-linux-androideabi19-clang** which is a wrapper around `clang` that sets the right target and there is no definition of `__SIZEOF_INT128__`.

`
$ armv7a-linux-androideabi19-clang -E -dM - < /dev/null | grep INT128
`

So if you are using NDK version R21e, you can fix the build with:
`
CC=armv7a-linux-androideabi19-clang ../../Configure android-arm -D__ANDROID_API__=19
`

**Comment by amitay** [comment]
@mattcaswell  We possibly can handle this issue in `Configurations/15-android.conf` by setting `CC` (and maybe `CROSS_COMPILE`) to point to the correct wrapper for clang.

**Comment by mattcaswell** [comment]
Thanks for the investigation! Really useful.

I have a proposed fix in #14812.

**Comment by catenacyber** [comment]
I also got this with
`setarch i386 ./config no-poly1305 no-shared no-threads -m32 && make build_generated libcrypto.a`

I get the following compile error
```
Step #13:  clang  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DPADLOCK_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -fPIC -m32 -Wa,--noexecstack -Qunused-arguments -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -m32 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -MMD -MF crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.d.tmp -MT crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.o -c -o crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.o crypto/ec/curve448/arch_64/f_impl.c
Step #13: crypto/ec/curve448/arch_64/f_impl.c:17:21: warning: incompatible pointer types initializing 'const uint64_t *' (aka 'const unsigned long long *') with an expression of type 'word_t const[16]' [-Wincompatible-pointer-types]
Step #13:     const uint64_t *a = as->limb, *b = bs->limb;
Step #13:                     ^   ~~~~~~~~
Step #13: crypto/ec/curve448/arch_64/f_impl.c:17:36: warning: incompatible pointer types initializing 'const uint64_t *' (aka 'const unsigned long long *') with an expression of type 'word_t const[16]' [-Wincompatible-pointer-types]
Step #13:     const uint64_t *a = as->limb, *b = bs->limb;
Step #13:                                    ^   ~~~~~~~~
Step #13: crypto/ec/curve448/arch_64/f_impl.c:18:15: warning: incompatible pointer types initializing 'uint64_t *' (aka 'unsigned long long *') with an expression of type 'word_t [16]' [-Wincompatible-pointer-types]
Step #13:     uint64_t *c = cs->limb;
Step #13:               ^   ~~~~~~~~
Step #13: crypto/ec/curve448/arch_64/f_impl.c:19:14: error: expected ';' after expression
Step #13:     uint128_t accum0 = 0, accum1 = 0, accum2;
Step #13:              ^
Step #13:              ;
Step #13: crypto/ec/curve448/arch_64/f_impl.c:19:5: error: use of undeclared identifier 'uint128_t'
Step #13:     uint128_t accum0 = 0, accum1 = 0, accum2;
```

**Comment by mattcaswell** [comment]
Please test out the proposed fix in #14812

**Comment by catenacyber** [comment]
I am afraid it does not work, still getting the same error

**Comment by gjasny** [comment]
Hello,

I haven't found time to deeply look into the issue but my suspicion in that the Android Bionic libc does not provide a 128bit integer type.

The compile time test is done against the compiler preprocessor macros which promise support from the compiler. In previous revisions the compiler 128bit types were used (and probably worked as expected).

Semi-related: would it make sense to add a basic Android CI target for armv7 and arm64?

Thanks,
Gregor

**Comment by mattcaswell** [comment]
> I am afraid it does not work, still getting the same error

Have you completely cleaned your environment and run Configure again?

**Comment by catenacyber** [comment]
> Have you completely cleaned your environment and run Configure again?

@mattcaswell Yes using oss-fuzz `python infra/helper.py shell ecc-diff-fuzzer` (so fresh image from docker with just git clone), then applying your patch
```
diff --git a/Configure b/Configure
index e36c5d93..8cd14f0a 100755
--- a/Configure
+++ b/Configure
@@ -1577,7 +1577,8 @@ if (!$disabled{asm} && !$predefined_C{__MACH__} && $^O ne 'VMS') {
 $config{use_int128} = 0;
 {
     my $cc = $config{CROSS_COMPILE}.$config{CC};
-    open(PIPE, "$cc -E -dM - </dev/null 2>&1 |");
+    $target{cflags} =~ /(-target (\w|-)+)/;
+    open(PIPE, "$cc $1 -E -dM - </dev/null 2>&1 |");
     while(<PIPE>) {
         if (m/__SIZEOF_INT128__/) {
             $config{use_int128} = 1;
```
Then running the mentioned commands
`setarch i386 ./config no-poly1305 no-shared no-threads -m32`
and
`make build_generated libcrypto.a` fails because of these `uint128_t`

I can change these commands if they are not right

**Comment by mattcaswell** [comment]
Hmm. I'm looking suspiciously at the `-m32` argument...

**Comment by mattcaswell** [comment]
I suspect my original patch didn't quite cover all cflags for all cases. It worked in my environment, but it perhaps not everywhere.

I've updated #14812 with more complete coverage of the cflags.

@catenacyber could you give the updated patch another try?

**Comment by mattcaswell** [comment]
Hmmm....hold that request. It seems the CIs don't like the new patch

**Comment by mattcaswell** [comment]
Also see #14863 for another instance of this.

**Comment by citrus-it** [comment]
I am seeing the same issue building alpha14 on OmniOS (where alpha13 was fine) - a load of new warnings too.
This is gcc 10.2, and we build and ship the openssl libraries as both 32-bit and 64-bit - this is the 32-bit build that is failing.

```
gcc  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DPOLY1305_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -fPIC -pthread -O2 -fno-aggressive-loop-optimizations -fstack-protector-strong -m32 -Wa,--noexecstack -Wall -O3 -fomit-frame-pointer -DFILIO_H -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/ssl\"" -DENGINESDIR="\"/usr/lib/engines-3\"" -DMODULESDIR="\"/usr/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG  -MMD -MF crypto/ec/curve448/libcrypto-lib-eddsa.d.tmp -MT crypto/ec/curve448/libcrypto-lib-eddsa.o -c -o crypto/ec/curve448/libcrypto-lib-eddsa.o crypto/ec/curve448/eddsa.c
crypto/ec/curve448/arch_64/f_impl.c: In function 'gf_mul':
crypto/ec/curve448/arch_64/f_impl.c:17:25: warning: initialization of 'const uint64_t *' {aka 'const long long unsigned int *'} from incompatible pointer type 'const word_t *' {aka 'const unsigned int *'} [-Wincompatible-pointer-types]
   17 |     const uint64_t *a = as->limb, *b = bs->limb;
      |                         ^~
crypto/ec/curve448/arch_64/f_impl.c:17:40: warning: initialization of 'const uint64_t *' {aka 'const long long unsigned int *'} from incompatible pointer type 'const word_t *' {aka 'const unsigned int *'} [-Wincompatible-pointer-types]
   17 |     const uint64_t *a = as->limb, *b = bs->limb;
      |                                        ^~
crypto/ec/curve448/arch_64/f_impl.c:18:19: warning: initialization of 'uint64_t *' {aka 'long long unsigned int *'} from incompatible pointer type 'word_t *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
   18 |     uint64_t *c = cs->limb;
      |                   ^~
crypto/ec/curve448/arch_64/f_impl.c:19:5: error: unknown type name 'uint128_t'; did you mean 'uint32_t'?
   19 |     uint128_t accum0 = 0, accum1 = 0, accum2;
      |     ^~~~~~~~~
      |     uint32_t
crypto/ec/curve448/arch_64/f_impl.c:50:16: warning: right shift count >= width of type [-Wshift-count-overflow]
   50 |         accum0 >>= 56;
      |                ^~~
crypto/ec/curve448/arch_64/f_impl.c:51:16: warning: right shift count >= width of type [-Wshift-count-overflow]
   51 |         accum1 >>= 56;
      |                ^~~
crypto/ec/curve448/arch_64/f_impl.c:60:12: warning: right shift count >= width of type [-Wshift-count-overflow]
   60 |     accum0 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:61:12: warning: right shift count >= width of type [-Wshift-count-overflow]
   61 |     accum1 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c: In function 'gf_mulw_unsigned':
crypto/ec/curve448/arch_64/f_impl.c:69:25: warning: initialization of 'const uint64_t *' {aka 'const long long unsigned int *'} from incompatible pointer type 'const word_t *' {aka 'const unsigned int *'} [-Wincompatible-pointer-types]
   69 |     const uint64_t *a = as->limb;
      |                         ^~
crypto/ec/curve448/arch_64/f_impl.c:70:19: warning: initialization of 'uint64_t *' {aka 'long long unsigned int *'} from incompatible pointer type 'word_t *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
   70 |     uint64_t *c = cs->limb;
      |                   ^~
crypto/ec/curve448/arch_64/f_impl.c:71:5: error: unknown type name 'uint128_t'; did you mean 'uint32_t'?
   71 |     uint128_t accum0 = 0, accum4 = 0;
      |     ^~~~~~~~~
      |     uint32_t
crypto/ec/curve448/arch_64/f_impl.c:79:16: warning: right shift count >= width of type [-Wshift-count-overflow]
   79 |         accum0 >>= 56;
      |                ^~~
crypto/ec/curve448/arch_64/f_impl.c:81:16: warning: right shift count >= width of type [-Wshift-count-overflow]
   81 |         accum4 >>= 56;
      |                ^~~
crypto/ec/curve448/arch_64/f_impl.c:86:20: warning: right shift count >= width of type [-Wshift-count-overflow]
   86 |     c[5] += accum0 >> 56;
      |                    ^~
crypto/ec/curve448/arch_64/f_impl.c:90:20: warning: right shift count >= width of type [-Wshift-count-overflow]
   90 |     c[1] += accum4 >> 56;
      |                    ^~
crypto/ec/curve448/arch_64/f_impl.c: In function 'gf_sqr':
crypto/ec/curve448/arch_64/f_impl.c:95:25: warning: initialization of 'const uint64_t *' {aka 'const long long unsigned int *'} from incompatible pointer type 'const word_t *' {aka 'const unsigned int *'} [-Wincompatible-pointer-types]
   95 |     const uint64_t *a = as->limb;
      |                         ^~
crypto/ec/curve448/arch_64/f_impl.c:96:19: warning: initialization of 'uint64_t *' {aka 'long long unsigned int *'} from incompatible pointer type 'word_t *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
   96 |     uint64_t *c = cs->limb;
      |                   ^~
crypto/ec/curve448/arch_64/f_impl.c:97:5: error: unknown type name 'uint128_t'; did you mean 'uint32_t'?
   97 |     uint128_t accum0 = 0, accum1 = 0, accum2;
      |     ^~~~~~~~~
      |     uint32_t
crypto/ec/curve448/arch_64/f_impl.c:120:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  120 |     accum0 >>= 55;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:121:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  121 |     accum1 >>= 55;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:142:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  142 |     accum0 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:143:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  143 |     accum1 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:162:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  162 |     accum0 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:163:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  163 |     accum1 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:186:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  186 |     accum0 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:187:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  187 |     accum1 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:196:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  196 |     accum0 >>= 56;
      |            ^~~
crypto/ec/curve448/arch_64/f_impl.c:197:12: warning: right shift count >= width of type [-Wshift-count-overflow]
  197 |     accum1 >>= 56;
      |            ^~~
gmake[1]: *** [Makefile:14591: crypto/ec/curve448/arch_64/libcrypto-lib-f_impl.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/data/omnios-build/omniosorg/bloody/_build/openssl-3.0.0/openssl-3.0.0-alpha14'
```

**Comment by citrus-it** [comment]
It appears that Configure is not using the supplied CFLAGS when doing the check for `__SIZEOF_INT128__`.

```
bloody:omnios.bloody:% gcc -m32 -E -dM - < /dev/null | grep SIZEOF_INT128
bloody:omnios.bloody:% gcc -E -dM - < /dev/null | grep SIZEOF_INT128
#define __SIZEOF_INT128__ 16
```

**Comment by mattcaswell** [comment]
> It appears that Configure is not using the supplied CFLAGS when doing the check for __SIZEOF_INT128__.

Yes. Unfortunately my attempt to patch this in #14812 by adding all the CFLAGS results in different problems (on some platforms Configure then seems to decide that `__SIZEOF_INT128__` is not available when in fact it is). I have another idea on how to solve this. I just need to find some dev cycles to implement it.

**Comment by mattcaswell** [comment]
I've taken a different approach with the patch. New fix in #14941. Please test and let me know how you get on!

**Comment by citrus-it** [comment]
Tested on OmniOS - alpha 14 + this new patch, all fine and all tests passed:
```
All tests successful.
Files=233, Tests=3271, 902 wallclock secs (13.59 usr  2.63 sys + 522.43 cusr 288.64 csys = 827.31 CPU)
Result: PASS
```

**Comment by catenacyber** [comment]
Works like a charm, thanks @mattcaswell now waiting to see it merged
