### ISSUE TITLE
Build failure of 3.4.1: `threads_pthread.c: error: redefinition of 'fallback_atomic_exchange_n_uint64_t'`

### ISSUE THREAD

**Issue by barracuda156** [openssl/openssl#26740]
Something got broken here:

```
/usr/bin/gcc-4.2  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -fPIC -fno-common -arch ppc -std=gnu9x -Wa,-force_cpusubtype_ALL -pipe -Os -arch ppc -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include  -c -o crypto/libcrypto-lib-threads_pthread.o crypto/threads_pthread.c
/usr/bin/gcc-4.2  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -fPIC -fno-common -arch ppc -std=gnu9x -Wa,-force_cpusubtype_ALL -pipe -Os -arch ppc -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include  -c -o crypto/libcrypto-lib-threads_win.o crypto/threads_win.c
/usr/bin/gcc-4.2  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -fPIC -fno-common -arch ppc -std=gnu9x -Wa,-force_cpusubtype_ALL -pipe -Os -arch ppc -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include  -c -o crypto/libcrypto-lib-time.o crypto/time.c
/usr/bin/gcc-4.2  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -fPIC -fno-common -arch ppc -std=gnu9x -Wa,-force_cpusubtype_ALL -pipe -Os -arch ppc -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include  -c -o crypto/libcrypto-lib-trace.o crypto/trace.c
crypto/threads_pthread.c:214: error: redefinition of 'fallback_atomic_exchange_n_uint64_t'
crypto/threads_pthread.c:196: error: previous definition of 'fallback_atomic_exchange_n_uint64_t' was here
crypto/threads_pthread.c: In function 'update_qp':
crypto/threads_pthread.c:564: warning: implicit declaration of function 'fallback_atomic_compare_exchange_n_uint64_t'
crypto/threads_pthread.c:564: error: '__ATOMIC_ACQ_REL' undeclared (first use in this function)
crypto/threads_pthread.c:564: error: (Each undeclared identifier is reported only once
crypto/threads_pthread.c:564: error: for each function it appears in.)
crypto/threads_pthread.c:564: error: '__ATOMIC_RELAXED' undeclared (first use in this function)
make[1]: *** [crypto/libcrypto-lib-threads_pthread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_openssl3/openssl3/work/openssl-3.4.1'
make: *** [build_sw] Error 2
```

**Comment by barracuda156** [comment]
@nhorman Could you please take a look? The breakage caused by https://github.com/openssl/openssl/commit/fbd34c03e3ca94d3805e97a01defdf8b6037f61c

**Comment by rainerjung** [comment]
See also #26711.

**Comment by barracuda156** [comment]
> But you should have __ATOMIC_ACQ_REL defined. What platform are you building for? Can you provide the output of ./configdata --dump

This is likely due to gcc-4.2 not supporting modern atomics. I will see if this builds with the modern gcc, but it is a rather unpleasant if in order to get something as fundamental as OpenSSL one will need to bootstrap the whole gcc first.

It is on macOS 10.6 (powerpc, but the arch itself is unlikely to be the issue).

**Comment by barracuda156** [comment]
@nhorman So yes, no problem with gcc 10.5.0, but it is really desirable to avoid a requirement for C11-capable compiler, since that introduces a dependency requiring multiple hours of compilation on some systems.

See also a failure on i386 with clang 11:
```
/opt/local/libexec/clang-11-bootstrap/bin/clang  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DPOLY1305_ASM -DRC4_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -fPIC -arch i386 -pipe -Os -arch i386 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DBROKEN_CLANG_ATOMICS -I/opt/local/include -MMD -MF crypto/libcrypto-lib-threads_win.d.tmp -c -o crypto/libcrypto-lib-threads_win.o crypto/threads_win.c
crypto/threads_pthread.c:214:1: error: redefinition of 'fallback_atomic_exchange_n_uint64_t'
IMPL_fallback_atomic_exchange_n(uint64_t)
^
crypto/threads_pthread.c:186:26: note: expanded from macro 'IMPL_fallback_atomic_exchange_n'
    static ossl_inline t fallback_atomic_exchange_n_##t(t *p, t v)           \
                         ^
<scratch space>:141:1: note: expanded from here
fallback_atomic_exchange_n_uint64_t
^
crypto/threads_pthread.c:196:1: note: previous definition is here
IMPL_fallback_atomic_exchange_n(uint64_t)
^
crypto/threads_pthread.c:186:26: note: expanded from macro 'IMPL_fallback_atomic_exchange_n'
    static ossl_inline t fallback_atomic_exchange_n_##t(t *p, t v)           \
                         ^
<scratch space>:139:1: note: expanded from here
fallback_atomic_exchange_n_uint64_t
^
crypto/threads_pthread.c:564:10: warning: implicit declaration of function 'fallback_atomic_compare_exchange_n_uint64_t' is invalid in C99 [-Wimplicit-function-declaration]
    if (!ATOMIC_COMPARE_EXCHANGE_N(uint64_t, &lock->qp_group[current_idx].users, &ret, update,
         ^
crypto/threads_pthread.c:216:55: note: expanded from macro 'ATOMIC_COMPARE_EXCHANGE_N'
#  define ATOMIC_COMPARE_EXCHANGE_N(t, p, e, d, s, f) fallback_atomic_compare_exchange_n_##t(p, e, d, s, f)
                                                      ^
<scratch space>:155:1: note: expanded from here
fallback_atomic_compare_exchange_n_uint64_t
^
1 warning and 1 error generated.
make[1]: *** [crypto/libcrypto-lib-threads_pthread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_openssl3/openssl3/work/openssl-3.4.1'
make: *** [build_sw] Error 2
```

https://build.macports.org/builders/ports-10.6_i386-builder/builds/193593/steps/install-port/logs/stdio

**Comment by barracuda156** [comment]
@nhorman By the way, this is another bug, I think: if 64-bit atomics is requires, `libatomic` should be linked in where needed.

**Comment by barracuda156** [comment]
@nhorman After passing `-latomic` manually, I got the build working with gcc 10.5.0.

Should I open another issue for `libatomic`?

**Comment by nhorman** [comment]
sure

**Comment by nhorman** [comment]
can you try with the attached patch?

**Comment by barracuda156** [comment]
@nhorman Unfortunately no, it still fails if I apply https://github.com/openssl/openssl/pull/26747/commits/f5bcc82fbfc75873c67855a8028c35112589db1d on top of 3.4.1.
Do I need another commit from the master?

**Comment by barracuda156** [comment]
Ok, I just need to use the master, not 3.4.1, it won’t work with the latter.

**Comment by barracuda156** [comment]
@nhorman All good, f5bcc82fbfc75873c67855a8028c35112589db1d on top of 5949918f9afa85d72535676f114346ed541e0b1e builds fine with gcc-4.2.

**Comment by Sp1l** [comment]
(maintainer of FreeBSD OpenSSL ports)

This bug also appears on FreeBSD i386, all currently supported and the latest versions (13.3. 14.1, 14.2, 15) since OpenSSL 3.4.1 / 3.3.3
No such issue on the supported platforms. 3.5.0-alpha1 is OK (and contains the patches)

What commits do I need to cherry-pick for 3.4.1 and 3.3.3 to fix the build?

```
--- crypto/libfips-lib-threads_pthread.o ---
crypto/threads_pthread.c:218:1: error: redefinition of 'fallback_atomic_exchange_n_uint64_t'
  218 | IMPL_fallback_atomic_exchange_n(uint64_t)
      | ^
crypto/threads_pthread.c:190:26: note: expanded from macro 'IMPL_fallback_atomic_exchange_n'
  190 |     static ossl_inline t fallback_atomic_exchange_n_##t(t *p, t v)           \
      |                          ^
<scratch space>:105:1: note: expanded from here
  105 | fallback_atomic_exchange_n_uint64_t
      | ^
crypto/threads_pthread.c:200:1: note: previous definition is here
  200 | IMPL_fallback_atomic_exchange_n(uint64_t)
      | ^
crypto/threads_pthread.c:190:26: note: expanded from macro 'IMPL_fallback_atomic_exchange_n'
  190 |     static ossl_inline t fallback_atomic_exchange_n_##t(t *p, t v)           \
      |                          ^
<scratch space>:103:1: note: expanded from here
  103 | fallback_atomic_exchange_n_uint64_t
      | ^
crypto/threads_pthread.c:568:10: warning: call to undeclared function 'fallback_atomic_compare_exchange_n_uint64_t'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  568 |     if (!ATOMIC_COMPARE_EXCHANGE_N(uint64_t, &lock->qp_group[current_idx].users, &ret, update,
      |          ^
crypto/threads_pthread.c:220:55: note: expanded from macro 'ATOMIC_COMPARE_EXCHANGE_N'
  220 | #  define ATOMIC_COMPARE_EXCHANGE_N(t, p, e, d, s, f) fallback_atomic_compare_exchange_n_##t(p, e, d, s, f)
      |                                                       ^
<scratch space>:119:1: note: expanded from here
  119 | fallback_atomic_compare_exchange_n_uint64_t
      | ^
1 warning and 1 error generated.
*** [crypto/libfips-lib-threads_pthread.o] Error code 1
```

**Comment by barracuda156** [comment]
@pradorocchi gcc-4.2 does not support C11 atomics. However, I wonder why the fallback is not being used. Are you using the latest version of the port? I have `openssl3` 3.4.1 build with gcc-4.2 on 10.6.8 ppc from the existing portfile. Try running `port sync` and make sure you have revision 1 and not 0.

**Comment by barracuda156** [comment]
@Sp1l Probably you just need to pick the patches from https://github.com/macports/macports-ports/commit/32dfc23aa9a830a0daec19e617cdb8464adeadcd
