### ISSUE TITLE
std::unique_ptr<SSL> does not compile with 1.1.x

### ISSUE THREAD

**Issue by aduvenhage** [openssl/openssl#4344]
I have some code that manages SSL and SSL_CTX pointers with unique_ptr.

The following code compiles with OpenSSL 1.0.2, but not with OpenSSL 1.1.1:

std::unique_ptr<SSL>    m_pSession

I include 'openssl/ssl.h', but with OpenSSL 1.1.1 I get the following compile error (using Visual Studio):

error C2027: use of undefined type 'ssl_st'

I have googled a little and it seems that the later version of OpenSSL does not provide the real declaration of ssl_st in the accessible include files? What would be the solution to this?

**Comment by richsalz** [comment]
The contents of most struct's are now opaque; that is for C programming.  C++ is different, in that it wants fields declared so that it can call the right destructor, etc.  You are going to have to write little wrapper objects I think.

**Comment by mattcaswell** [comment]
Not really a C++ kinda guy (just C) but this para struck me as relevant (from http://en.cppreference.com/w/cpp/memory/unique_ptr)

"std::unique_ptr may be constructed for an incomplete type T, such as to facilitate the use as a handle in the pImpl idiom. If the default deleter is used, T must be complete at the point in code where the deleter is invoked,"

Are you using the default deleter? If so that sounds unlikely to give you the right results (even in 1.0.2). You need to invoke SSL_free().

**Comment by richsalz** [comment]
The unique_ptr can take two params, the second is the "default deleter"

**Comment by mattcaswell** [comment]
> The unique_ptr can take two params, the second is the "default deleter"

Isn't the second one the "deleter", and if you don't specify one you get the "default deleter"?

**Comment by richsalz** [comment]
Yes, and not seeing the user's code we don't know what they did.  I would be surprised if they are using the system delete since that would crash pretty darn quickly.  But it doesn't matter, the code will have to be modified as I first wrote :)

**Comment by levitte** [comment]
You may find some answers here: https://stackoverflow.com/questions/9954518/stdunique-ptr-with-an-incomplete-type-wont-compile

**Comment by aduvenhage** [comment]
I updated my implementation to use a custom deleter for SSL and SSL_CTX.  Will test with v1.1.x again soon.  I was calling SSL_free and SSL_CTX_free manually before, but now the code is actually much cleaner, thank you.

**Comment by kyadav78** [comment]
Hi , 
 i have got the same error(error C2027: use of undefined type 'ssl_st') while compiling my c++ project while integrating openssl 1.1.1b for TLS1.3 support. 
@aduvenhage : Could you please share me the solution for this problem? what exactly did you do as part of custom deleter implementation?

Regards
Kunal

**Comment by kyadav78** [comment]
Hi @levitte ,
 Could you please detailed out the fix?
Regards
Kunal

**Comment by levitte** [comment]
Considering I can't see the offending code, I can only resort to guessing, and I'm not C++ savvy enough for a quick working example.  However, it was already said that you somehow need to provide a deleter functor that calls `SSL_free`, and I do believe that the stackoverflow entry that I linked to earlier provides general examples on how to do that that is beyond what I can do in 5 minutes.

https://stackoverflow.com/questions/9954518/stdunique-ptr-with-an-incomplete-type-wont-compile
