### ISSUE TITLE
OpenSSL 3.0 make doesn't work on MacOS 11 when configuring for iOS Sim x86_64

### ISSUE THREAD

**Issue by NerevarineRule** [openssl/openssl#16752]
I have a script that I used for building static libs out of OpenSSL 1.1.1j for iOS/iOS Sim/MacOS targets.

For some reason, this started breaking on OpenSSL 3.0 when it tries to run "make" on the command line tool for iOS Sim x86_64 target on Xcode 13 with below error:

```
xcrun -sdk iphonesimulator cc  -Iinclude -Iproviders/implementations/include -Iproviders/common/include  -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk -fno-common -fembed-bitcode -mios-version-min=11.0 -mios-simulator-version-min=11.0 -arch x86_64 -fno-common -O3 -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG   -c -o providers/legacy-dso-legacyprov.o providers/legacyprov.c

xcrun -sdk iphonesimulator cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk -fno-common -fembed-bitcode -mios-version-min=11.0 -mios-simulator-version-min=11.0 -arch x86_64 -fno-common -O3 -L. -Wl,-search_paths_first  \

                -o providers/legacy.dylib \

                providers/legacy-dso-legacyprov.o \

                providers/liblegacy.a providers/libcommon.a -lcrypto  

Undefined symbols for architecture x86_64:

  "_main", referenced from:

     implicit entry/start for main executable

ld: symbol(s) not found for architecture x86_64
```
Would anyone know what the issue might be? I have attached the build script and the config file that I used.
This script does the following:
1)  untars the openssl 3.0.0 tar file and then creates a temporary dir & configures for a given architecture (ex: x86_64 or arm64)

```
   if [ "$OS" == "MacOSX" ]; then
      ${SRC_DIR}/Configure macos-$ARCH no-asm no-shared --prefix="${PREFIX}" &> "${PREFIX}.config.log"
   elif [ "$OS" == "MacOSX_Catalyst" ]; then
      ${SRC_DIR}/Configure mac-catalyst-$ARCH no-asm no-shared --prefix="${PREFIX}" &> "${PREFIX}.config.log"
   elif [ "$OS" == "iPhoneSimulator" ]; then
      ${SRC_DIR}/Configure ios-sim-cross-$ARCH no-asm no-shared --prefix="${PREFIX}" &> "${PREFIX}.config.log"
   elif [ "$OS" == "iPhoneOS" ]; then
      ${SRC_DIR}/Configure ios-cross-$ARCH no-asm no-shared --prefix="${PREFIX}" &> "${PREFIX}.config.log"
   fi
```

2)  Then runs make & make install command, which fails due to above error.

Seems like openssl 3.0 added providers folder which seems to be giving the issue. looks like main.c is absent in that folder, and could that be the reason why?

Has anyone ever encountered this issue on Xcode 13 command line tool on MacOS11? 
FYI, this script works perfectly with openssl 1.1.1j.
Any help or insights would be appreciated.

Thanks,
Peter

[openssl_3.0_script.tar.gz](https://github.com/openssl/openssl/files/7289404/openssl_3.0_script.tar.gz)

**Comment by xtkoba** [comment]
It seems odd that the `-shared` flag is not passed to `cc` when making `providers/legacy.dylib`.

`Configure`ing with `no-legacy` might help if the legacy provider is not needed.

**Comment by t8m** [comment]
The help wanted label was set for an extended period of time without any community help. The iOS support is outside of the set of primary and secondary platforms. Closing.
