### PR TITLE
convert CRYPTO_THREAD_run_once to use InitOnceExecuteOnce api

### LINKED ISSUE #22059: Windows CRYPTO_THREAD_run_once() implementation does not guarantee memory ordering which leads to undefined behaviour in multithreading contexts
# Platform and versions
 * Windows 11 arm64
 * OpenSSL: 3.1.2 (but the current `master` is also affected)
 * MSVC 2022 compiler

# Description
The current implementation of `CRYPTO_THREAD_run_once()` for the Windows system (see https://github.com/openssl/openssl/blob/d2873946dfaff5537ea3d1adf3890e33a3f276ff/crypto/threads_win.c#L134-L152) has a subtle issue, which can be exploited especially when running on architectures with weak memory ordering CPUs (like ARM).

Function's lock-free loop correctly synchronises the access to the `once` variable (by doing atomic operation with `InterlockedCompareExchange` API), however if the `init()` function writes some kind of global/shared variable(s), it might lead to `out-of-order reads` by another threads - aka the "consumer" threads might see the global data as incomplete even if `once` was changed.
There are multiple reasons to lead into out-of-order memory access (e.g. compiler optimisations, CPU memory access reordering, CPU cache), see a good introduction to the topic https://learn.microsoft.com/en-us/windows/win32/sync/synchronization-and-multiprocessor-issues

In my case, I discovered the problem by investigating some sporadic crashes in `OPENSSL_thread_stop()` called in parallel from multiple threads, from an application which links OpenSSL statically. From time to time, it happened that `glob_tevent_reg` to be incomplete in `init_thread_remove_handlers` https://github.com/openssl/openssl/blob/d2873946dfaff5537ea3d1adf3890e33a3f276ff/crypto/initthread.c#L176 - aka `gtr->lock` was NULL which made https://github.com/openssl/openssl/blob/d2873946dfaff5537ea3d1adf3890e33a3f276ff/crypto/initthread.c#L179 dereference a null pointer.

Basically, with the current implementation of `CRYPTO_THREAD_run_once()` there's a real danger that MT applications to be affected w/o knowing where to pinpoint - e.g. the out-of-order data can easily create (heap) memory corruptions which are much more fun to debug than a crash by null pointer access.

# PoC and solutions
I have created a small project to show-case the problem and implemented some fix proposals - refer to the `README.md` file from the archive
[CRYPTO_THREAD_run_once-windows.zip](https://github.com/openssl/openssl/files/12574275/CRYPTO_THREAD_run_once-windows.zip)

My recommendation is to adapt `CRYPTO_THREAD_run_once ` implementation to call Windows's `InitOnceExecuteOnce` API when the target is post Windows Vista (especially because XP is EOL for a while) and to keep the current implementation (plus the `MemoryBarrier()` fix) for the obsolete XP builds.

### PR DESCRIPTION
**Pull request by nhorman**
convert CRYPTO_THREAD_run_once to use InitOnceExecuteOnce api
    
Issue #22059 reported a race condition in CRYPTO_THREAD_run_once on
    windows platforms.  The most correct fix for this is to convert the
    windows run_once implementation to use the Win32 InitOnceExecuteOnce
    interface.  Doing so requires at least Windows Vista/Windows Server 2008
    to be available, and because WinXP hasn't built since 3.0 released, it
    seems sensible to bump our minimal NT version to be 0x600 (Vista/2008)
    
Also, while we're at it, this change caught a bad programming practice
    in the rio_notifier code, which attempts to reset the once variable
    during shutdown.  The windows static initalizer macro for this api is
    constructed such that attempting to do so causes a build break.  Since
    once variables are not meant to be reset (since they are only triggered
    once), remove that reset code to avoid the breakage.

### CODE REVIEW

File: crypto/threads_win.c [hunk 1]
```diff
@@ -512,32 +512,30 @@ void CRYPTO_THREAD_lock_free(CRYPTO_RWLOCK *lock)
...
+static BOOL CALLBACK init_wrapper(PINIT_ONCE InitOnce, void *param, PVOID *context)
+{
+    struct init_once_cb_info *info = (struct init_once_cb_info *)param;
+
+    info->init();
+    return TRUE;
+}
 
 /*
  * We don't use InitOnceExecuteOnce because that isn't available in WinXP which
```
Comment (mattcaswell) [inline crypto/threads_win.c]: Note this comment. If we no longer care about WinXP we should update the comment

Comment (nhorman) [reply crypto/threads_win.c]: yeah, I will, I just want to figure out how to keep InitOnceExecuteOnce from crashing first :)

File: ssl/rio/rio_notifier.c [hunk 2]
```diff
@@ -84,7 +84,6 @@ static void wsa_done(void)
         CRYPTO_atomic_add(&wsa_ref, -1, &ref, wsa_lock);
         if (ref == 0) {
             ossl_wsa_cleanup();
-            ensure_wsa_startup_once = CRYPTO_ONCE_STATIC_INIT;
```
Comment (mattcaswell) [inline ssl/rio/rio_notifier.c:87]: Why this change? I seems problematic to me. We can end up with unitialised WSA, but cannot initialise it again

**Review by mattcaswell — CHANGES_REQUESTED** [review]
This is a significant change that must not be back ported.

File: crypto/threads_win.c [hunk 3]
```diff
@@ -512,32 +512,28 @@ void CRYPTO_THREAD_lock_free(CRYPTO_RWLOCK *lock)
...
-        return 1;
+    info->init();
+    return TRUE;
+}
 
-    do {
-        result = InterlockedCompareExchange(lock, ONCE_ININIT, ONCE_UNINITED);
-        if (result == ONCE_UNINITED) {
-            init();
-            *lock = ONCE_DONE;
```
Comment (npajkovsky) [inline crypto/threads_win.c:535]: On weakly ordered CPUs, especially ARM/ARM64, another thread can observe ONCE_DONE but still not reliably observe all writes done by init(). There should be `InterlockedExchange(lock, ONCE_DONE);`


```c
    volatile LONG *lock = (volatile LONG *)once;

    for (;;) {
        LONG result = InterlockedCompareExchange(lock,
            ONCE_ININIT,
            ONCE_UNINITED);

        switch (result) {
        case ONCE_UNINITED:
            init();
            /*
             * Publish completion with an interlocked store.
             * This gives the release/full-barrier behaviour needed so
             * other threads that observe ONCE_DONE.
             */
            InterlockedExchange(lock, ONCE_DONE);
            return 1;
        case ONCE_DONE:
            return 1;
        case ONCE_ININIT:
            break;
        default:
            return 0;
        }
    }
```

File: ssl/rio/rio_notifier.c (hunk 2 above)
Comment (nhorman) [reply ssl/rio/rio_notifier.c:87]: This is documented in the commit message.  ensure_wsa_startup_once is a global variable, and statically initalized, so it will never be used uninitalized.

The reinitalization in wsa_done is a programming error, as re-initalizing a once variable is inherently racy (consider the situation in which two threads are attempting to initializes a run-once section in which the first fails and re-initializes it only after the second thread succeeds).

We need to rely on the fact that the os level at-most-once primitives maintain state properly here in the failure case (either allowing for retry or marking a single failure as permanent).

This worked before because the pthread implementation lets us shoot ourselves in the foot here, and for windows we used our own atomic implementation (which was itself broken as per #22059).  Switching to the InitOnceExecuteOnce api fixes #22059, but gives rise to a compilation error in the code above as the INIT_ONCE macro is constructed such that uses outside of static declarations result in build breaks.

The right fix seems to be to no reinitialize once variables at run time at all.

File: crypto/threads_win.c (hunk 3 above)
Comment (nhorman) [reply crypto/threads_win.c:535]: I'm not sure what you're getting at here.  The entire code block above was removed in favor of the InitOnceExecuteOnce api to address exactly the problem you are describing (as outlined in #22059)

Comment (npajkovsky) [reply crypto/threads_win.c:535]: I'm just pointing out that the code can be fixed and be compatible with XP.

Comment (nhorman) [reply crypto/threads_win.c:535]: Ok, thats a fair point, but I think its a separate discussion we need to have.

There was a comment [here](https://github.com/openssl/openssl/issues/22059#issuecomment-4575400433) which suggested that the fix here should be (a) replace the internal implementation and (b) bump our minimal support to be windows 7, which I followed

I know that there has been discussion that disagrees with the removal of windows xp support (I don't have the last issue that I investigated this on), but @mbroz has an issue [here](https://github.com/openssl/private/issues/872) with notes on it.  The last version of openssl I was able to build on windows xp was 3.0.0 I believe.

So whatever we decide, I think its important to note two major things:
1) openssl on windows XP hasn't been buildable since early in the 3.0 series (about 5-ish years now).
2) Its an unadopted platform (meaning we don't test on it, and have no ability to consistently maintain the platform going forward.

Given those two above items, I strongly feel like we shouldn't in any way fool ourselves into thinking that windows xp works now, and consequently shouldn't pretend that any constraint we place on code going forward (i.e. not using apis that don't exist in windows xp) is going to keep xp somehow working.

Thats not to say we shouldn't consider making xp work, however.  I'm only suggesting that we split this conversation out into two separate questions:

1) Is this change ok functionally?  I.e. does it do what we want it to do on the platforms we support?  I think the answer is yes, and if there is consensus, we move forward with it.

2) Do we want to support windows XP?  If so, we should undertake the effort to add some level of CI for it, and go through the process of building it and fixing every build/runtime issue we encounter on it.  This should be done independently and asynchronously to (1), as its going to be a large undertaking.

**Review by npajkovsky — DISMISSED** [review]

**Comment by jogme** [comment]
@nhorman do you want to fix the dword alignment in this PR if at all?

**Comment by nhorman** [comment]
> @nhorman do you want to fix the dword alignment in this PR if at all?

@jogme turns out I was wrong about that.  The problem I was encountering turned out to be one of definition.  windows.h wasn't included in crypto.h properly, and somehow Visual C decided that the INIT_ONCE type should be defined as an integer type rather than what the windows api expects, and so I was corrupting memory.  Including windows.h in e_os2.h fixed it.

**Review by jogme — DISMISSED** [review]
LGTM, thanks!

File: ssl/rio/rio_notifier.c (hunk 2 above)
Comment (mattcaswell) [reply ssl/rio/rio_notifier.c:87]: This needs a larger refactor than this change to fix this problem. Consider the following code:

``` C
    SSL *d;

    /* This code ends up calling ensure_wsa_startup() and therefore WSAStartup()*/
    d = SSL_new_domain(ctx, SSL_DOMAIN_FLAG_THREAD_ASSISTED);

    /*
     * This code ends up calling wsa_done(). The ref count drops to zero so ossl_wsa_cleanup
     * gets called and hence WSACleanup()
     */
    SSL_free(d);

    /*
     * This code calls wsa_startup() again, but the run_once has already executed and
     * WSAStartup() does not get called again
     */
    d = SSL_new_domain(ctx, SSL_DOMAIN_FLAG_THREAD_ASSISTED);
```

With the previous code this "worked" (WSAStartup() gets called again). Now it doesn't.

If we are going to remove this resetting of `ensure_wsa_startup_once` then we also need to remove the ref counting code, and ensure WSACleanup() really only gets called once after everything has finished.

**Review by mattcaswell — CHANGES_REQUESTED** [review]

**Comment by nhorman** [comment]
@mattcaswell 

> This needs a larger refactor than this change to fix this problem. Consider the following code:

You're right, this does need some more work.  We can't do the wsa_done call until such time as the the whole process exits, or we will be in a situation in which we won't be able to recreate the lock that gets allocated in the run once routine, and so we run the risk of attempting to use a NULL pointer for our lock.

Fortunately, we're in luck here.  The do_wsa_startup routine does 2 things:

1) Creates the wsa_lock
2) Initalizes the Winsock libraray vai WSAStartup

There is something of a chain of dependencies here:
a) The lock is only created for the purposes of the non-atomic platform use case for CRYPTO_ATOMIC on the wsa_ref atomic variable
b) The wsa_ref atomic variable is only there to track the number of parallel users of the rio notifier.  The wsa_ref value reaching zero indicates we can call wsa_done, which frees the allocated lock in (1) and shuts down the Winsock DLL in (2).

BUT

According to:
https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsacleanup

WSACleanup is already automatcially called when the process exists, the implication being that we don't need to shut it down when there are no more users, we can just let it remain initalized until the openssl-using process itself exists.

If we abandon the need to cleanup winsock, and just let the runtime library do it for us, then there is no more need for reference counting, just one time initalization.  So we can eliminate the refcount variable.

If theres no need for ref counting, theres no need for the lock that protects it, and we can eliminate that as well.

So ensure_wsa_startup can just be reduced to a call to WSAStartup, and everything else can be safely removed.

I'll make those changes

**Review by mattcaswell — APPROVED** [review]

**Review by bob-beck — APPROVED** [review]

**Review by t8m — APPROVED** [review]

File: include/internal/e_os.h [hunk 4]
```diff
@@ -109,7 +109,7 @@
  *	0x0603 // Windows 8.1
  *	0x0A00 // Windows 10
  */
-#define _WIN32_WINNT 0x0501
+#define _WIN32_WINNT 0x0600
```
Comment (mbroz) [inline include/internal/e_os.h:112]: As our default toolchain cannot compile binaries for WinXP without additional settings, this is perhaps fine. But apparently the change here should not be backported then...

**Comment by nhorman** [comment]
merged to master, thank you
