### PR TITLE
Drop darwin-i386(-cc) targets from Configurations

### LINKED ISSUE #18515: Drop darwin-i386(-cc) targets from Configurations
I was using a bash script to install OpenSSL 3.0.2 for a development project. It used to work, until recently (assuming a Mac update?) or maybe something else?

## Details:
MacOS Monterey v12.4
Confirmed running from a rosetta terminal whose `arch` gives `i386`

## Example:
```bash
wget https://www.openssl.org/source/openssl-3.0.2.tar.gz 
echo "98e91ccead4d4756ae3c9cde5e09191a8e586d9f4d50838e7ec09d6411dfdb63 openssl-3.0.2.tar.gz" | sha256sum --check
tar -xzvf openssl-3.0.2.tar.gz
cd openssl-3.0.2
make clean
perl Configure darwin-i386-cc enable-fips -shared no-weak-ssl-ciphers
make
sudo make install
```

## Error message:
```
...
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: could not create compact unwind for _RAND_load_file: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _RAND_write_file: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _ossl_store_handle_load_result: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _read_string_inner: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _process_pci_value: stack subl instruction is too different from dwarf stack size
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)
ld: warning: could not create compact unwind for _epki2pki_decode: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _prov_tls13_hkdf_expand: stack subl instruction is too different from dwarf stack size
Undefined symbols for architecture i386:
...
     (maybe you meant: _X509_VERIFY_PARAM_set_time, _X509_STORE_CTX_set_time , _X509_time_adj , _ossl_x509_set1_time , _ossl_x509_check_cert_time , _err_clear_last_constant_time , _TS_TST_INFO_get_time , _TS_TST_INFO_set_time , _TS_RESP_CTX_set_time_cb , _OSSL_PARAM_set_time_t , _PKCS7_add0_attrib_signing_time , _ossl_asn1_time_to_tm , _X509_cmp_time , _OSSL_PARAM_get_time_t , _X509_time_adj_ex , _X509_cmp_current_time , _OSSL_PARAM_construct_time_t , _CT_POLICY_EVAL_CTX_get_time , _CT_POLICY_EVAL_CTX_set_time , _SCT_set_timestamp , _X509_VERIFY_PARAM_get_time , _SCT_CTX_set_time , _X509_cmp_timeframe , _SCT_get_timestamp , _ossl_asn1_time_from_tm , _OSSL_PARAM_BLD_push_time_t , _ASN1_TIME_cmp_time_t , _ASN1_UTCTIME_cmp_time_t , _ossl_asn1_time_print_ex )
  "_usleep$UNIX2003", referenced from:
      _BIO_wait in libcrypto-shlib-bio_lib.o
      _BIO_do_connect_retry in libcrypto-shlib-bio_lib.o
      _poll_for_response in libcrypto-shlib-cmp_client.o
  "_vfprintf", referenced from:
      _OPENSSL_showfatal in libcrypto-shlib-cryptlib.o
  "_write$UNIX2003", referenced from:
      _conn_write in libcrypto-shlib-bss_conn.o
      _conn_puts in libcrypto-shlib-bss_conn.o
      _dgram_write in libcrypto-shlib-bss_dgram.o
      _fd_write in libcrypto-shlib-bss_fd.o
      _sock_write in libcrypto-shlib-bss_sock.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libcrypto.3.dylib] Error 1
make: *** [build_libs] Error 2
```

## Other comments: 
On x86 ubuntu, and alpine linux, everything works smoothly and the improvements made in the 3.x release are very very appreciated. Any ideas on where to go from here would be incredibly helpful.

### PR DESCRIPTION
**Pull request by n13l**
Fixes #18515

### CODE REVIEW

**Comment by n13l** [comment]
The CI jobs failing don't seem relevant after the rebase.

**Comment by esyr** [comment]
I guess, by the same token, we can drop ppc and ppc64 darwin targets as well.

**Comment by npajkovsky** [comment]
Are we sure we want to drop support for systems that compile just fine and cause us no problems to have them around?

**Comment by n13l** [comment]
> Are we sure we want to drop support for systems that compile just fine and cause us no problems to have them around?

There is a sensible summary, and there is agreement on dropping the target: https://github.com/openssl/openssl/issues/18515

**Comment by t8m** [comment]
Merged to the master branch. Thank you.
