### PR TITLE
Fix no-des

### LINKED ISSUE #1746: openssl-1.0.2j does not compile with 'no-des' option
# how to reproduce
 
Using either Centos6 64bit or MacOS 10.12 (probably other Unix system too)
 
$ tar xzf openssl-1.0.2j.tar.gz
$ cd openssl-1.0.2j
$ ./config shared no-des no-comp no-engine
…
$ make depend
$ make
…
 
# expected result
 
it compiles
 
# actual result
 
make[2]: Entering directory ‘…./openssl-1.0.2j/apps'
../libcrypto.so: undefined reference to `EVP_des_ede3_wrap'
 
# remarks
 
·         it works fine when I remove the “no-des” option form ./config
·         it works fine with openssl-1.0.1

### PR DESCRIPTION
**Pull request by levitte**
Fixes #1746

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by levitte** [comment]
merged
