### ISSUE TITLE
Build of 1.0.2m is broken with "no-ssl2 no-ssl3 no-ssl3-method"

### ISSUE THREAD

**Issue by misery** [openssl/openssl#4658]
```
s23_clnt.c:762:29: warning: implicit declaration of function 'SSLv3_client_method'; did you mean 'SSLv23_client_method'? [-Wimplicit-function-declaration]
                 s->method = SSLv3_client_method();
```

```
../libssl.so: undefined reference to `SSLv3_client_method'
```

Introduced by 44191de234b061145a6ed14221927ec0c9c7b7bf

**Comment by kroeckx** [comment]
Fixed by https://github.com/openssl/openssl/pull/4649
