### ISSUE TITLE
error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’ in openssl 1.1

### ISSUE THREAD

**Issue by v-sijeff** [openssl/openssl#12447]
Hello, I have been tasked with fixing a program that I have never seen before.  It compiles and runs quite nicely with openssl 1.0 but will **not** compile with 1.1  The error message is:

```
$ make
  CC      main.c
main.c: In function ‘do_signature’:
main.c:63:10: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  memcpy(x->signature->data, sig_buf, sig_len);
          ^~
Makefile:54: recipe for target 'main.o' failed
make: *** [main.o] Error 1
$ 
```

The relevant code is:
```
        /* Replace the signature in the Cert with HSM signature */
        memcpy(x->signature->data, sig_buf, sig_len);
        x->signature->length = sig_len;

```
I see where X509 is defined in ossl.h but I am having trouble following beyond that.

I looked at [bug report 2990](https://github.com/openssl/openssl/issues/2990) .  Over 3 years ago, richsalz wrote: "Yes, like most of the OpenSSL structures it is now an opaque datatype. What fields do you need? We would have to write accessors and documentation. It would go into master and 1.1.0 because missing accessors we consider a bug."  No good deed goes unpunished, Rich. 

Thank you

**Comment by richsalz** [comment]
I'm no longer part of the OpenSSL project.  Hopefully someone else will pick this up.  I think the team is at full capacity working on 3.0 and FIPS.  Good luck.

**Comment by v-sijeff** [comment]
Rich,

I suspected that might be the answer.  Thank you for the quick response.  I wish you all the best.

Jeff


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by v-sijeff** [comment]
I found an answer that almost but not quite works: In [OpenSSL 1.1.0 Changes](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes), there is a comment in tiny text at the bottom of the page that says:

> [openssl-compat.tar.gz](https://wiki.openssl.org/images/e/ed/Openssl-compat.tar.gz) - openssl-compat.tar.gz includes sources files openssl-compat.h and openssl-compat.c. The files provide the OpenSSL 1.1.0 compatibility layer for OpenSSL 1.0.2 and below users. OpenSSL 1.0.2 users should add openssl-compat.h and openssl-compat.c to their project, and then access data members through the functions.

This almost works because libcrypto-compat.c includes `includes.h` and I am trying to find includes.h.  I found an includes.h at [kroeckx/openssh-portable](https://github.com/kroeckx/openssh-portable/blob/master/includes.h) and it might or might not be the right one because it references config.h.  Now it may be that I should download that entire set of files and run config on them and then make them.  More information as I develop it.

**Comment by slontis** [comment]
Work around it using..

const ASN1_BIT_STRING *signature;
X509_get0_signature(&signature, NULL, x);

**Comment by mattcaswell** [comment]
Looks like this has been answered. Closing.

**Comment by mattcaswell** [comment]
There is no such field in recent versions of OpenSSL. According to this commit log (359aa38fbee) it was removed 7 years ago because it was no longer used. Looking in OpenSSL 1.0.2 - which is the last version where that field still exists in the structure - I can't see any use of it there either.
