### ISSUE TITLE
Commit bed4afa81b9 breaks compilation on MacOS on the current master

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#5290]
Verified on MacOS El Capitan, Sierra 10.12.6, and High Sierra 10.13.3 (all running latest available Xcode). 

### Here's the error:
```
$ ./config --prefix=$HOME/openssl-1.1 --debug --openssldir=$HOME/openssl-1.1/etc --with-rand-seed=rdcpu enable-aria enable-ec_nistp_64_gcc_128 enable-md2 enable-rc5 enable-weak-ssl-ciphers enable-zlib-dynamic enable-tls1_3 enable-tls13downgrade
. . . . .
clang  -I. -Icrypto/include -Iinclude -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -Qunused-arguments -fPIC -DDSO_DLFCN -DHAVE_DLFCN_H -DZLIB -DZLIB_SHARED -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -I/opt/local/include -DOPENSSLDIR="\"/Users/uri/openssl-1.1/etc\"" -DENGINESDIR="\"/Users/uri/openssl-1.1/lib/engines-1.1\""  -c -MMD -MF crypto/rand/rand_unix.d.tmp -MT crypto/rand/rand_unix.o -c -o crypto/rand/rand_unix.o crypto/rand/rand_unix.c
crypto/rand/rand_lib.c:235:41: error: function-like macro '__GLIBC_PREREQ' is not defined
         || (defined(__GLIBC_PREREQ) && __GLIBC_PREREQ(2, 17)))
                                        ^
1 error generated.
```

Native `clang` does **not** like that define.

The offending commit bed4afa81b9 is a part of #5269 by Pauli, intended to fix MacOS compilation, but in fact broke it worse.

### Solution:

Get rid of that monstrosity, as no MacOS at least after 10.5.x defines `__GLIBC_PREREQ`.
```
diff --git a/crypto/rand/rand_lib.c b/crypto/rand/rand_lib.c
index 69c3c79c6d..66f23b744c 100644
--- a/crypto/rand/rand_lib.c
+++ b/crypto/rand/rand_lib.c
@@ -231,8 +231,7 @@ static uint64_t get_timer_bits(void)
 # if defined(_POSIX_C_SOURCE) \
      && defined(_POSIX_TIMERS) \
      && _POSIX_C_SOURCE >= 199309L \
-     && (!defined(__GLIBC__) \
-         || (defined(__GLIBC_PREREQ) && __GLIBC_PREREQ(2, 17)))
+     && (!defined(__GLIBC__))
     {
         struct timespec ts;
         clockid_t cid;
```

With the proposed fix it not only compiles correctly, but passes all of its own validation tests.

**Comment by paulidale** [comment]
There is a fix in #5279 which is awaiting approval.

**Comment by mouse07410** [comment]
1. Can you please point at the specific commit?
2. It wasn't broken before, so I don't understand why one needed to mess with it.

**Comment by paulidale** [comment]
There is only one commit in that PR: https://github.com/openssl/openssl/pull/5279/commits/55598f4127eac4e1caaa43ba8f664885ca5bd5f0

This change simplifies code elsewhere.

The proposed fix above will fail with older glibc versions at link time.

**Comment by mouse07410** [comment]
OK, thanks. Will wait then.

**Comment by paulidale** [comment]
I don't believe Travis has a CI loop for OS/X.  It was discussed at one point but I don't remember anything coming of it.

**Comment by mouse07410** [comment]
> I don't believe Travis has a CI loop for OS/X

Based on the above, maybe it should. It serves us well for [Crypto++](https://github.com/weidai11/cryptopp.git) and[ Botan](https://github.com/randombit/botan.git).

**Comment by levitte** [comment]
We turned off osx in our `.travis.yml` because [it was too slow](https://github.com/travis-ci/travis-ci/issues/7304). However, that seems to have changed recently, so we should add it back...

**Comment by richsalz** [comment]
Since you submitted the build-fix PR, has this issue now morphed into "maybe add OS/X to travis" ? Or should we close this one.

**Comment by richsalz** [comment]
and the PR to put osx back was done, so closing this.
