### ISSUE TITLE
OSCP Response Library Conflicts

### ISSUE THREAD

**Issue by sratnesh** [openssl/openssl#12202]
Hi , 

I am doing  OCSP validation For Cert Revocation in C++ using Open ssl 
and using the below code as a basic framework to develop my application.

http://www.zedwood.com/article/cpp-x509-certificate-revocation-check-by-ocsp

Everything works fine but I am getting compilation error for OSCP response 

There is a OSCP library conflicts and need help in resloving this issue 

![image](https://user-images.githubusercontent.com/67142442/85109885-b0583800-b22f-11ea-9bb6-1bd3b7372652.png)

![image](https://user-images.githubusercontent.com/67142442/85109942-c960e900-b22f-11ea-8273-9e01dd3a8949.png)

Please guide how I can get this fixed 

Thanks
Ratnesh

**Comment by DDvO** [comment]
Hi @sratnesh, you are trying to access the internals of the opaque OCSP response datatype.

You could do but then would need to include the internal `crypto/ocsp/ocsp_local.h` file.
Yet this is bad programming practice and not an OpenSSL bug.

Better use the official access functions such as `OCSP_response_get1_basic()`; see, e.g., 
https://github.com/openssl/openssl/blob/master/doc/man3/OCSP_response_status.pod
