### ISSUE TITLE
OpenSSL 1.1.1 Multiple DTLS record handling issue

### ISSUE THREAD

**Issue by tbbalaji** [openssl/openssl#18968]
Hi Dev Group,

I am using OpenSSL 1.1.1 and noticing an issue related to DTLS. During the DTLS handshake, my application software acts as a DTLS server. After it sends Server Hello Done message, when it receives a IP/UDP datagram that contains multiple DTLS records encoded consecutively in the same packet (for example Certificate handshake message DTLS record followed by Client key exchange DTLS record, followed by Certificate Verify, followed by Change Cipher spec, followed by Finished/encrypted handshake), my application forwards the full UDP payload (without the UDP header that contains the total length) to ssl3_accept() function. However OpenSSL only processes the very 1st Certificate handshake DTLS record and does not process the next records. Basically when OpenSSL code calls ssl_read_bytes(), it never gets the 2nd DTLS record and so the handshake fails. However later ssl_read_bytes() returns the 1st record from the retransmitted packet from the client and never gets to the 2nd record for some reason. This happens after we upgraded the OpenSSL from 1.0.1 to 1.1.1. Has anyone noticed this problem or is there any known issue around this area?

Advanced thanks for your help and support.

Thanks,
Balaji

**Comment by mattcaswell** [comment]
> my application forwards the full UDP payload (without the UDP header that contains the total length) to ssl3_accept()

How do you do this? Are you using a custom BIO?

**Comment by tbbalaji** [comment]
Application creates 2 BIO's using memory segment one for read and the other for write and set the 2 BIO's in SSL using SSL_set_bio(s, rbio, wbio).

**Comment by mattcaswell** [comment]
I'm not aware of any problems with OpenSSL in this area (it's not a known problem).

Are you using `BIO_s_mem()` for this? Or are you using a custom memory backed BIO? Note that `BIO_s_mem()` is not really suitable for DTLS although it will probably (mostly) work. Notably `BIO_s_mem()` is designed for stream semantics not packet semantics - so it does not respect packet boundaries. It also does not implement the various ctrls that `BIO_s_dgram()` does for doing things like querying the underlying MTU.

I am wondering whether some strange effect from using the stream based `BIO_s_mem()` is somehow causing this. Although I don't know why it used to work in 1.0.1 (but then again *lots* of stuff has changed between 1.0.1 and 1.1.1).

**Comment by mattcaswell** [comment]
One thing that you might be able to check - is the data actually read from the mem BIO and then dropped? Or is it never read?

**Comment by tbbalaji** [comment]
Yes I am using BIO_s_mem() for the BIO object creation. Application gets the UDP payload of the UDP packet coming from wire and writing the payload to the read BIO.

ssl_read_bytes() in dtls_get_reassembled_message() in statem_dtls.c returns the 1st DTLS certificate record correctly. I would assume this is reading from the mem BIO. However I don't know after reading, the read content from MEM BIO is removed or still persist in the memory. But after DTLS process successfully the certificate message and the state machine attempts to read the next DTLS record using ssl_read_bytes, it does not get the 2nd DTLS record. Rather after some time, ssl_read_bytes() returns the 1st DTLS record of retransmitted packet.

The question I have since the application is sending only the UDP payload (as opposed to UDP header which contains the total length which is the sum of all DTLS records including UDP header length), how does the OpenSSL know that there is a 2nd DTLS record after reading the 1st record successfully?

**Comment by tbbalaji** [comment]
Also regarding your previous comment

" is the data actually read from the mem BIO and then dropped? Or is it never read?"

is there any API that can used to check the above?

**Comment by mattcaswell** [comment]
> The question I have since the application is sending only the UDP payload (as opposed to UDP header which contains the total length which is the sum of all DTLS records including UDP header length), how does the OpenSSL know that there is a 2nd DTLS record after reading the 1st record successfully?

With DTLS, OpenSSL will attempt to read an entire packet in one go. It holds the entire packet in an internal buffer. When you call `SSL_accept()` it will enter its handshake state machine. If it is expecting to receive a record as the next step in the handshake then it will attempt to get one from its internal record layer. The record layer will first check its internal buffered data to see if it might have a record there. If the buffer is empty then it will try to pull in another packet from the underlying BIO.

Once the buffer has data then it will first read the record header and discover the record length. Then, it pulls in the record body and processes the record as appropriate. The state machine will then check what its expecting next. If its expecting to receive another record then the process repeats. If at any point it is trying to read, and the internal buffer is empty, and underlying BIO returns no data, then SSL_accept() will return, and will signal `SSL_ERROR_WANT_READ`.

With DTLS you should never get "half" a record. So, if there is unprocessed data in the internal buffer then it should always consist of some whole number of records. If it ever finds itself with "half" a record then it will just discard it. It will also discard records if they appear to be malformed, or cannot be decrypted. This is a significant difference between TLS and DTLS. In TLS, malformed records will immediately abort the connection. DTLS tolerates them.

> is there any API that can used to check the above?

You can use `BIO_pending()` to check if there is unread data available in a BIO.

**Comment by tbbalaji** [comment]
Thanks for the explanation. 

FYI, when the application writes the UDP payload (containing multiple DTLS recods) to the BIO using BIO_write(), I confirmed that the return value of BIO_write() call matches the buffer length argument given to the API. So the full UDP payload is written to the BIO correctly which I assume OpenSSL should be able to read it.

**Comment by tbbalaji** [comment]
Do you know if I have to write the full UDP packet (UDP header + UDP payload) to the BIO from the application? Currently I am writing only the UDP payload without the UDP header to the BIO and it worked fine on OpenSSL 1.0.1.

**Comment by mattcaswell** [comment]
> Do you know if I have to write the full UDP packet (UDP header + UDP payload) to the BIO from the application? Currently I am writing only the UDP payload without the UDP header to the BIO and it worked fine on OpenSSL 1.0.1.

Only the payload should be written not the header.

**Comment by t8m** [comment]
How do you use the BIO_s_mem(). Do you BIO_write() the packet payload into it or do you use something else?

**Comment by tbbalaji** [comment]
Based on my debugging further, there is no issue in the OpenSSL code. My
application code after getting the full packet payload from the BIO was
dropping the rest of the payload unintentionally after processing the 1st
record.

Thank you very much for the clarifications.

**Comment by mattcaswell** [comment]
Seems like this is resolved so closing.
