### ISSUE TITLE
OpenSSL 3.0: Compiler error with gcc 12.2.0 for x86_64 and lp64 data model

### ISSUE THREAD

**Issue by tanjahummel** [openssl/openssl#20036]
With OpenSSL 3.0, I get a compile error in **aes_x86core.c**, when using gcc 12.2.0 for a x86_64 target and lp64 data model.
It worked with OpenSSL 1.1.1n

```
crypto/aes/aes_x86core.c:89:28: error: conflicting types for 'u64'; have 'long long unsigned int'

crypto/aes/aes_local.h:27:18: note: previous declaration of 'u64' with type 'u64' {aka 'long unsigned int'}
```

there are two different typedefs for u64:

aes_local.h:
`typedef uint64_t u64;` 

aes_x86core.h:
```
#if (defined(_WIN32) || defined(_WIN64)) && !defined(__MINGW32__)
typedef unsigned __int64 u64;
#define U64(C)  C##UI64
#elif defined(__arch64__)
typedef unsigned long u64;
#define U64(C)  C##UL
#else
typedef unsigned long long u64;
#define U64(C)  C##ULL
#endif
```

for x86_64 with lp64 data model, aes_x86core.h defines **unsigned long long** for u64, which is wrong and conflicts with the type defined in aes_local.h

Is this a bug or is there something wrong with my configuration?

**Comment by t8m** [comment]
This does not affect 1.1.1 branch.

**Comment by t8m** [comment]
Fix in 20043

**Comment by t8m** [comment]
Hmm, the file actually isn't used by OpenSSL build at all and should be removed.

**Comment by t8m** [comment]
I am not sure how is your build triggering an error on the file as it should not be built at all.

**Comment by tanjahummel** [comment]
There was a problem with my build configuration. Without aes_x86core.c it is working fine.
Thank you!
