### ISSUE TITLE
Compiling OpenSSL 1.1.0 on Windows using MSys2 (GCC 7.3)

### ISSUE THREAD

**Issue by Eurobertics** [openssl/openssl#6063]
Hello,
since OpenSSL >=1.1.0 I have some problems using static libraries when I self compile the package.
Compile messages following at bottom.

Compiling OpenSSL works without any problems using (for static libraries):

> perl Configure mingw64 no-asm no-shared --prefix=xxx
mingw32-make depend
mingw32-make
mingw32-make install

When I want to use the static libraries (libcrypto.a / libssl.a) in an application I get compiler errors
regarding DLL-Import specs. It seems to be, that some system-libraries are not inlcuded in the OpenSSL compiled libraries.
(Side note: I'm building a static library with self written code and importing the OpenSSL symbols
of the static libraries into My own library to have a compact one-file (static) library.)

**Notice:** This works perfectly with OpenSSL 1.0.2k.
What I noticed as well, is that "make depend" does nothing since OpenSSL 1.1.0.

Building on:
OS: Windows 10
Build-System: MSys2 / MinGW64
GCC: 7.3.0
CMake (for My test application project): 3.10
IDE: CLion instead of VC

Snipped of build output from test application at linking process:
[...]
> C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0xaa): undefined reference to `__imp_getnameinfo'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0xdb): undefined reference to `__imp_ntohs'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0x1ed): undefined reference to `gai_strerrorW'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0x6f8): undefined reference to `__imp_freeaddrinfo'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0xb2b): undefined reference to `__imp_getaddrinfo'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_addr.o):b_addr.c:(.text+0xb68): undefined reference to `gai_strerrorW'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0xc5): undefined reference to `__imp_WSAStartup'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0xd3): undefined reference to `__imp_WSAGetLastError'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0x266): undefined reference to `__imp_WSAStartup'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0x274): undefined reference to `__imp_WSAGetLastError'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0x32c): undefined reference to `__imp_ntohs'
C:/Users/brobertz/CLionProjects/yatest/../yacrypt/cmake-build-debug\libyacryptbig.a(b_sock.o):b_sock.c:(.text+0x373): undefined reference to `__imp_getsockopt'
[...]

**Comment by dot-asm** [comment]
Quoting INSTALL.W32 from 1.0.2 or NOTES.WIN from 1.1.0. "Linking your application. If you link with static OpenSSL libraries, then you're expected to additionally link your application with WS2_32.LIB, GDI32.LIB, ADVAPI32.LIB, CRYPT32.LIB and USER32.LIB." It's same text in both releases. In other words it shouldn't have worked even in 1.0.2. If it did, then *that* was rather anomaly, i.e. it shouldn't have worked.

**Comment by Eurobertics** [comment]
Thanks for you response.
Indeed that worked until 1.0.2n.
After all, I linked the needed libraries in the current version, but at the wrong point. Actually everything works perfectly. Thanks for pointing the right direction.
