### PR TITLE
Fix build on illumos with gcc 5.3

### PR DESCRIPTION
**Pull request by pyhalov**
gcc 5.3 defines STDC_VERSION to 201112L (c99), together with _XOPEN_SOURCE 500 this leads to compilation error in feature-tests.h ("Compiler or options invalid for pre-UNIX 03 X/Open applications and pre-2001 POSIX applications").

### CODE REVIEW

**Comment by richsalz** [comment]
Doesn't that break every other Sun build?

**Comment by pyhalov** [comment]
Checked OpenSSL builds with GCC 4.9 and 5.3 on OpenIndiana.

**Comment by dot-asm** [comment]
Addressed in master in 2e6d7799ffc47604d06e0465afeb84b91aff8006.

**Comment by dot-asm** [comment]
As for 1.0.2. As it turns out unlike master the _XOPEN_SOURCE macro is defined prior first #include and even though it's not really most optimal approach, compilation is likely to succeed. For this reason I'd be reluctant to modify unless OP can confirm failure. @pyhalov, could you try to compile 1.0.2. [In master there also was a bug in setvbuf fall, as it turns out it's not present in 1.0.2.]

**Comment by pyhalov** [comment]
Without   # define _XOPEN_SOURCE 500 ?

**Comment by pyhalov** [comment]
with following patch applied (backported from https://github.com/openssl/openssl/commit/2e6d7799ffc47604d06e0465afeb84b91aff8006) 

[2e6d7799ffc47604d06e0465afeb84b91aff8006.patch.txt](https://github.com/openssl/openssl/files/273549/2e6d7799ffc47604d06e0465afeb84b91aff8006.patch.txt)

OpenSSL 1.0.2h builds fine on OpenIndiana with gcc 5.3 and 4.9

**Comment by dot-asm** [comment]
1.0.2 is addressed in e10b54ca32280d9fec20085f404dcdcf2217c90e. Thanks. Closing.
