### ISSUE TITLE
3.0.3 Compilation problems

### ISSUE THREAD

**Issue by WyzHyl** [openssl/openssl#18346]
crypto/bn/bn_dh.c:34:5: error: initializer element is not constant
crypto/bn/bn_dh.c:34:5: error: (near initialization for 'modp_1536_p[0]')

Error when compiling 3.0.3, 1.X version does not have this problem，The compiler used is the ARM cross compiler

**Comment by paulidale** [comment]
ca2bf555cd64bc9624af1259ce3cd27f95a5763e is the culprit commit.

**Comment by t8m** [comment]
Except this is a clear bug of the compiler - the initializer is a constant expression.

**Comment by paulidale** [comment]
I've seen a few (ancient) compilers didn't like constant expressions.

The C89 standard says it is allowed in 6.5.7 but doesn't admit it in foot note 54 in 6.4 which defines constant expressions.  It doesn't appear to mandate that constant expressions are evaluated at compiler time (they _can_ be).

C99 mandates that they are evaluated at compile time.

**Comment by paulidale** [comment]
I think the answer to the original question is your compiler is at fault.

**Comment by WyzHyl** [comment]
I think the reason is that the compiler I'm using doesn't recognize this form of initialization
static const BN_ULONG modp_1536_p[] = {
    BN_DEF(0xFFFFFFFF, 0xFFFFFFFF), BN_DEF(0xCA237327, 0xF1746C08),

**Comment by t8m** [comment]
Yes, and that's a serious deficiency of the compiler as it is just a preprocessor macro expanding to a simple constant expression `(BN_ULONG)0xF1746C08 << 32 | 0xCA237327`
