### ISSUE TITLE
armv4 cross-build fails

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#11453]
I tried to build master with 
```
$ arm-linux-gnueabihf-gcc -v
Using built-in specs.
COLLECT_GCC=arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/home/ed/gnu/arm-linux-gnueabihf-linux64/libexec/gcc/arm-linux-gnueabihf/10.0.0/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../gcc-trunk-1/configure --prefix=/home/ed/gnu/arm-linux-gnueabihf-linux64 --target=arm-linux-gnueabihf --enable-languages=all --with-cpu=cortex-a57 --with-mode=thumb --with-fpu=fp-armv8 --with-float=hard
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.0.0 20190907 (experimental) (GCC) 
```
this is what happened:
```
providers/libimplementations.a providers/libcommon.a providers/libfips.a -ldl -pthread 
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: providers/libimplementations.a(libimplementations-lib-cipher_aes_gcm_hw.o): in function `armv8_aes_gcm_encrypt':
cipher_aes_gcm_hw.c:(.text+0x15e): undefined reference to `aes_gcm_enc_192_kernel'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: cipher_aes_gcm_hw.c:(.text+0x178): undefined reference to `aes_gcm_enc_128_kernel'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: cipher_aes_gcm_hw.c:(.text+0x192): undefined reference to `aes_gcm_enc_256_kernel'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: providers/libimplementations.a(libimplementations-lib-cipher_aes_gcm_hw.o): in function `armv8_aes_gcm_decrypt':
cipher_aes_gcm_hw.c:(.text+0x1da): undefined reference to `aes_gcm_dec_192_kernel'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: cipher_aes_gcm_hw.c:(.text+0x1f4): undefined reference to `aes_gcm_dec_128_kernel'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.0/../../../../arm-linux-gnueabihf/bin/ld: cipher_aes_gcm_hw.c:(.text+0x20e): undefined reference to `aes_gcm_dec_256_kernel'
collect2: error: ld returned 1 exit status
```
I will re-build with a more recent gcc version
I also saw some fatal warnings about BIO_printf with %ld but value is uint64_t
armv4 is long = int = 32 bits

**Comment by bernd-edlinger** [comment]
Hi @slontis how are you doing in australia?

**Comment by bernd-edlinger** [comment]
@slontis this is a build failure, I think you should look at it?
Do you need help with testing it, like a cross-compiler?

**Comment by slontis** [comment]
You are probably better off getting the person who added this to look at it.
@zorrorffm ?

**Comment by bernd-edlinger** [comment]
Ah sorry @slontis apologies for thinking that was your work.
How did he do that?

**Comment by slontis** [comment]
Not sure. I assume it compiled when it was done though.

**Comment by bernd-edlinger** [comment]
Oh, you mean I have to bisect that one?

**Comment by bernd-edlinger** [comment]
Maybe tomorrow.  I try to sleep first.

**Comment by zorrorffm** [comment]
aarch64 aes-gcm assembly implementations such as aes_gcm_enc_128_kernel are supposed to be compiled into providers/libfips.a.  Could you check configdata.pm to see if asm_arch is aach64?

**Comment by bernd-edlinger** [comment]
No I use linux-armv4 that one is broken

**Comment by zorrorffm** [comment]
> 
> 
> No I use linux-armv4 that one is broken

So you compile successfully after fixing linux-armv4?

**Comment by bernd-edlinger** [comment]
what is the question,
compile works fine, but link dont work,  see above.

**Comment by zorrorffm** [comment]
> 
> 
> what is the question,
> compile works fine, but link dont work, see above.

Sorry, I misunderstand that.    

I guess the link error comes from aes_gcm_enc_128_kernel  not being compiled into libfips.a.  if asm_arch in configdata.pm is aarch64, it should be compiled into libfips.a. I suspect that asm_arch in configdata.pm is not aarch64, could you check that?  You can check that by run perl configdata.pm --dump.

**Comment by bernd-edlinger** [comment]
np. BTW: I don't have physical access to the real hardware, because of the lock-down here.
I only have a cross compiler (home built, if you want I can give you access to the binaries).
So I cannot really test much either.

the requested information follows:
```
$ ./configdata.pm --dump

Command line (with current working directory = .):

    /usr/bin/perl ./Configure linux-armv4 CROSS_COMPILE=arm-linux-gnueabihf-

Perl information:

    /usr/bin/perl
    5.18.2 for x86_64-linux-gnu-thread-multi

Enabled features:

    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cmp
    cms
    comp
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    dynamic-engine
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    fips
    gost
    idea
    legacy
    makedepend
    md4
    mdc2
    module
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    padlockeng
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    secure-memory
    seed
    shared
    siphash
    siv
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method

Disabled features:

    afalgeng            [cross-compiling] OPENSSL_NO_AFALGENG
    asan                [default]         OPENSSL_NO_ASAN
    buildtest-c++       [default]         
    crypto-mdebug       [default]         OPENSSL_NO_CRYPTO_MDEBUG
    devcryptoeng        [default]         OPENSSL_NO_DEVCRYPTOENG
    ec_nistp_64_gcc_128 [default]         OPENSSL_NO_EC_NISTP_64_GCC_128
    egd                 [default]         OPENSSL_NO_EGD
    external-tests      [default]         OPENSSL_NO_EXTERNAL_TESTS
    fuzz-libfuzzer      [default]         OPENSSL_NO_FUZZ_LIBFUZZER
    fuzz-afl            [default]         OPENSSL_NO_FUZZ_AFL
    ktls                [default]         OPENSSL_NO_KTLS
    md2                 [default]         OPENSSL_NO_MD2 (skip crypto/md2)
    msan                [default]         OPENSSL_NO_MSAN
    rc5                 [default]         OPENSSL_NO_RC5 (skip crypto/rc5)
    sctp                [default]         OPENSSL_NO_SCTP
    ssl-trace           [default]         OPENSSL_NO_SSL_TRACE
    trace               [default]         OPENSSL_NO_TRACE
    ubsan               [default]         OPENSSL_NO_UBSAN
    unit-test           [default]         OPENSSL_NO_UNIT_TEST
    uplink              [no uplink_arch]  OPENSSL_NO_UPLINK
    weak-ssl-ciphers    [default]         OPENSSL_NO_WEAK_SSL_CIPHERS
    zlib                [default]         
    zlib-dynamic        [default]         
    ssl3                [default]         OPENSSL_NO_SSL3
    ssl3-method         [default]         OPENSSL_NO_SSL3_METHOD

Config target attributes:

    AR => "ar",
    ARFLAGS => "r",
    CC => "gcc",
    CFLAGS => "-Wall -O3",
    CXX => "g++",
    CXXFLAGS => "-Wall -O3",
    HASHBANGPERL => "/usr/bin/env perl",
    RANLIB => "ranlib",
    RC => "windres",
    asm_arch => "armv4",
    bn_ops => "BN_LLONG RC4_CHAR",
    build_file => "Makefile",
    build_scheme => [ "unified", "unix" ],
    cflags => "-pthread",
    cppflags => "",
    cxxflags => "-std=c++11 -pthread",
    defines => [  ],
    disable => [  ],
    dso_ldflags => "-z defs",
    dso_scheme => "dlfcn",
    enable => [ "afalgeng" ],
    ex_libs => "-ldl -pthread",
    includes => [  ],
    lflags => "",
    lib_cflags => "",
    lib_cppflags => "-DOPENSSL_USE_NODELETE",
    lib_defines => [ "OPENSSL_BUILDING_OPENSSL" ],
    module_cflags => "-fPIC",
    module_cxxflags => undef,
    module_ldflags => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    perl_platform => "Unix",
    perlasm_scheme => "linux32",
    shared_cflag => "-fPIC",
    shared_defflag => "-Wl,--version-script=",
    shared_defines => [  ],
    shared_ldflag => "-Wl,-znodelete -shared -Wl,-Bsymbolic",
    shared_rcflag => "",
    shared_sonameflag => "-Wl,-soname=",
    shared_target => "linux-shared",
    thread_defines => [  ],
    thread_scheme => "pthreads",
    unistd => "<unistd.h>",

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 

Makevars:

    AR              = arm-linux-gnueabihf-ar
    ARFLAGS         = r
    CC              = arm-linux-gnueabihf-gcc
    CFLAGS          = -Wall -O3
    CPPDEFINES      = 
    CPPFLAGS        = 
    CPPINCLUDES     = 
    CROSS_COMPILE   = arm-linux-gnueabihf-
    CXX             = arm-linux-gnueabihf-g++
    CXXFLAGS        = -Wall -O3
    HASHBANGPERL    = /usr/bin/env perl
    LDFLAGS         = 
    LDLIBS          = 
    PERL            = /usr/bin/perl
    RANLIB          = arm-linux-gnueabihf-ranlib
    RC              = arm-linux-gnueabihf-windres
    RCFLAGS         = 

NOTE: These variables only represent the configuration view.  The build file
template may have processed these variables further, please have a look at the
build file for more exact data:
    Makefile

build file:

    Makefile

build file templates:

    Configurations/common0.tmpl
    Configurations/unix-Makefile.tmpl
    Configurations/common.tmpl
```

Today, I updated from b5f7aa5 where I previously was,
to 4b1fe47....

Interestingly now the problem appears to be worse:
```
${LDCMD:-arm-linux-gnueabihf-gcc} -pthread -Wa,--noexecstack -Wall -O3 -L.   \
		-o test/afalgtest \
		test/afalgtest-bin-afalgtest.o \
		test/libtestutil.a -lcrypto -ldl -pthread 
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: test/libtestutil.a(libtestutil-lib-driver.o): in function `setup_test_framework':
driver.c:(.text+0x248): undefined reference to `test_random_seed'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: test/libtestutil.a(libtestutil-lib-driver.o): in function `run_tests':
driver.c:(.text+0x408): undefined reference to `test_random_seed'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: driver.c:(.text+0x638): undefined reference to `test_random'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: driver.c:(.text+0xa40): undefined reference to `test_random'
collect2: error: ld returned 1 exit status
make[1]: *** [test/aesgcmtest] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: test/libtestutil.a(libtestutil-lib-driver.o): in function `setup_test_framework':
driver.c:(.text+0x248): undefined reference to `test_random_seed'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: test/libtestutil.a(libtestutil-lib-driver.o): in function `run_tests':
driver.c:(.text+0x408): undefined reference to `test_random_seed'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: driver.c:(.text+0x638): undefined reference to `test_random'
/home/ed/gnu/arm-linux-gnueabihf-linux64/lib/gcc/arm-linux-gnueabihf/10.0.1/../../../../arm-linux-gnueabihf/bin/ld: driver.c:(.text+0xa40): undefined reference to `test_random'
collect2: error: ld returned 1 exit status
make[1]: *** [test/afalgtest] Error 1
make[1]: Leaving directory `/home/ed/OPC/openssl'
```
And guess what, I do make again, and it succeeds.
I wonder if that may be a race condition in building the openssl

That reminds me of a similar problem I had with building gdb, where also
a race condition happened.

**Comment by bernd-edlinger** [comment]
This is what I refered to, and how I fixed it.  the system here is
the same with gnu make 3.81 @levitte 
See https://github.com/bminor/binutils-gdb
```
commit 1ee7b812e778e4fddcfaa5f0be023dfdfb5a4d6e
Author: Bernd Edlinger <bernd.edlinger@hotmail.de>
Date:   Fri Dec 13 17:21:21 2019 +0100

    Fix build with GNU Make 3.81
    
    GNU Make 3.81 is apparently confused when the same
    source file is processed by a pattern rule and an
    explicit rule at the same time with different output file.
    The pattern %.o: ../%.c and alloc-ipa.o: ../alloc.c
    both have the source ../alloc.c but two independent
    object files alloc.o and alloc-ipa.o, so
    while building gdbserver I see the following message:
    
    make[4]: Circular alloc-ipa.o <- ../alloc.c dependency dropped.
      CXX    alloc-ipa.o
    g++: warning: '-x c++' after last input file has no effect
    g++: fatal error: no input files
    compilation terminated.
    
    In the make debug output I see the pattern is first correct:
    
    alloc-ipa.o: ../alloc.c | config.h build-gnulib-gdbserver/import/string.h
            $(IPAGENT_COMPILE) $(WARN_CFLAGS_NO_FORMAT) $<
            $(POSTCOMPILE)
    
    But after the "Circular" dependency is dropped, the pattern
    is changed to:
    
    alloc-ipa.o: | config.h build-gnulib-gdbserver/import/string.h
            $(IPAGENT_COMPILE) $(WARN_CFLAGS_NO_FORMAT) $<
            $(POSTCOMPILE)
    
    So indeed now $< is empty, and the build step fails.
    
    This happens only when alloc.o needs to be built, when alloc.o
    was already built, the build succeeds, but it takes often
    several attempts until the build succeeds.
    By rewriting the alloc-ipa.c: ../alloc.c rule into a pattern
    rule, the problem goes away.
    
    While already at it, this patch removes also the
    $(WARN_CFLAGS_NO_FORMAT) from the build rule, which is just a
    copy/paste thing that is not necessary for alloc.c at all.
```

**Comment by bernd-edlinger** [comment]
Hmm, funny, today I tried to build it again and it worked.

I think I haven't changed anything.

I'll leave this open for a while.  I think this is a race condition, somewhere.

**Comment by paulidale** [comment]
Can we close this yet?

**Comment by t8m** [comment]
We have armv4 cross compile builds passing in the CI. Closing.
