### ISSUE TITLE
Upgrading from 1.1.1k -> 1.1.1l via Intel x64 Mac OS X 10.11.6 darwin64-x86_64-cc

### ISSUE THREAD

**Issue by francisuk1989** [openssl/openssl#16487]
1.1.1k was working fine for Mac OS X 10.11.6 under **darwin64-x86_64-cc** but upgrading to the newer version of 1.1.1l gives an error? Also tried brew but no luck is just the same error.

```
From source **openssl-1.1.1l.tar.gz**

FransMacPro:openssl-1.1.1l francis$ ./config
Operating system: x86_64-apple-darwinDarwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64
WARNING! If you wish to build 32-bit libraries, then you have to
         invoke 'KERNEL_BITS=32 ./config '.
Configuring OpenSSL version 1.1.1l (0x101010cfL) for darwin64-x86_64-cc
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

OpenSSL has been successfully configured

```
```
make install

 -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -MMD -MF crypto/rand/rand_unix.d.tmp -MT crypto/rand/rand_unix.o -c -o crypto/rand/rand_unix.o crypto/rand/rand_unix.c
In file included from crypto/rand/rand_unix.c:38:
/usr/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
typedef CCCryptorStatus CCRNGStatus;
        ^
crypto/rand/rand_unix.c:385:47: error: use of undeclared identifier 'kCCSuccess'
    if (CCRandomGenerateBytes(buf, buflen) == kCCSuccess)
                                              ^
2 errors generated.
make[1]: *** [crypto/rand/rand_unix.o] Error 1
make: *** [all] Error 2
```
```

**Comment by slontis** [comment]
@t8m -This was attempted to be fixed via https://github.com/openssl/openssl/pull/16409).
10.11.6 is El Capitan
I can see someone is also having issues on 10.12 (Sierra) which they worked around by setting the include path..
https://stackoverflow.com/questions/68957915/macos-10-12-brew-install-openssl-issue?rq=1
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/CommonCrypto/CommonRandom.h..
 is the same path as my local machine (Catalina).

**Comment by t8m** [comment]
Is the missing path just a general problem in brew or should the minimum MacOS version for using CommonRandom be just bumped somewhat higher?

**Comment by h-vetinari** [comment]
> @t8m -This was attempted to be fixed via #16409).

This _was_ fixed by #16409, but that fix has not been released yet.

**Comment by robmcgee-mag** [comment]
FYI: After applying these code changes we can build on older Mac versions(10.8 & 10.9) again, however we see a new test failure on 10.10 & 10.11 for 05-test_rand.t
For example:
`make test V=1 TESTS=test_rand
/Applications/Xcode7.2.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode7.2.app/Contents/Developer/usr/bin/make _tests
( cd test; \
  mkdir -p test-runs; \
  SRCTOP=../. \
  BLDTOP=../. \
  RESULT_D=test-runs \
  PERL="perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=`cd .././engines 2>/dev/null && pwd` \
  OPENSSL_DEBUG_MEMORY=on \
    perl .././test/run_tests.pl test_rand )
../test/recipes/05-test_rand.t ..
1..2
    # Subtest: ../drbgtest
    1..6
        # Subtest: test_kats
        1..6
        ok 1 - iteration 1
        ok 2 - iteration 2
        ok 3 - iteration 3
        ok 4 - iteration 4
        ok 5 - iteration 5
        ok 6 - iteration 6
    ok 1 - test_kats
        # Subtest: test_error_checks
        1..6
        ok 1 - iteration 1
        ok 2 - iteration 2
        ok 3 - iteration 3
        ok 4 - iteration 4
        ok 5 - iteration 5
        ok 6 - iteration 6
    ok 2 - test_error_checks
    # ERROR: (int) 'status == 0' failed @ test/drbgtest.c:697
    # [11] compared to [0]
    # ERROR: (bool) 'test_drbg_reseed_after_fork(master, public, private) == true' failed @ test/drbgtest.c:799
    # false
    not ok 3 - test_rand_drbg_reseed
    ok 4 - test_rand_seed
    ok 5 - test_rand_add
    ok 6 - test_multi_thread
../../util/shlib_wrap.sh ../drbgtest => 1
not ok 1

#   Failed test at ../test/recipes/05-test_rand.t line 16.
    # Subtest: ../drbg_cavs_test
`

Am I safe to skip these tests for time being?

**Comment by lprimak** [comment]
Are you sure you are applying the changes?  The errors indicate they are not applied

**Comment by robmcgee-mag** [comment]
Ah thank you I missed [this ](https://github.com/openssl/openssl/pull/16587/files)one. 
`osx10.10 xcode 7.2l` works now but I still see the issue on `osx10.11 xcode 8.1` strangely enough.

**Comment by robmcgee-mag** [comment]
@lprimak can you reproduce this issue by any chance?

**Comment by lprimak** [comment]
@robmcgee-mag i have no issues on El Capitan 10.11 now. Sorry.
