### ISSUE TITLE
The openssl app can't be built directly from a clean state

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#11932]
In https://github.com/openssl/openssl/pull/11682#issuecomment-631241508, @paulidale made a remark that it is not possible to build `apps/openssl` directly from a clean state:

```
make clean && ./config && make apps/openssl
```
This made me wonder whether this actually worked in master and 1.1.1, and it turned out this was not the case either.

**master**

```
~/src/openssl$ make apps/openssl
/usr/bin/perl apps/progs.pl -C "apps/openssl" > apps/progs.c
/usr/bin/perl apps/progs.pl -H "apps/openssl" > apps/progs.h
gcc  -Iapps -I. -Iinclude -Iapps/include  -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_BUILDING_OPENSSL  -MMD -MF apps/openssl-bin-asn1pars.d.tmp -MT apps/openssl-bin-asn1pars.o -c -o apps/openssl-bin-asn1pars.o apps/asn1pars.c
In file included from ./e_os.h:14,
                 from apps/include/apps.h:13,
                 from apps/asn1pars.c:13:
include/openssl/opensslconf.h:13:10: fatal error: openssl/configuration.h: No such file or directory
 #include <openssl/configuration.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22463: apps/openssl-bin-asn1pars.o] Error 1
```

**1.1.1**

```
~/src/openssl-1.1.1$ make apps/openssl
/usr/bin/perl apps/progs.pl apps/openssl > apps/progs.h
gcc  -I. -Iinclude -Iapps -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wno-long-long -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wswitch -Wsign-compare -Wshadow -Wformat -Wtype-limits -Wundef -Werror -Wmissing-prototypes -Wstrict-prototypes   -MMD -MF apps/asn1pars.d.tmp -MT apps/asn1pars.o -c -o apps/asn1pars.o apps/asn1pars.c
In file included from apps/apps.h:13,
                 from apps/asn1pars.c:13:
./e_os.h:14:11: fatal error: openssl/opensslconf.h: No such file or directory
 # include <openssl/opensslconf.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6380: apps/asn1pars.o] Error 1
```

### A missing dependency

In both cases, the compilation fails because the generated header files are missing. During normal builds, the files are generated in time, but not if one builds `apps/openssl` directly. While this is not an issue for regular users, it is inconvenient for developers.

The problem can be fixed by making the app's modules depend on the `$(GENERATED_MANDATORY)` files. The `$(GENERATED_MANDATORY)` list is generated from the empty DEPEND entries and actually the comment indicates that those dependencies should be built before anything else.

**master**

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/build.info#L10-L14

**1.1.1**

https://github.com/openssl/openssl/blob/e512efe0894481679a5d3c57d10bf4ea97046c2a/build.info#L16-L19

This works for `make`, but not for `make apps/openssl`. I was able to fix the build by adding the dependencies manually to the Makefile, but I failed to do it properly in the OpenSSL build system. But for @levitte it should be an easy fix, right?

On a related note it seems inconvenient that the `GENERATED_MANDATORY` list has proliferated a lot recently. Originally, in 1.1.1 it used to contain only the generated header files

```
GENERATED_MANDATORY=include/crypto/bn_conf.h include/crypto/dso_conf.h include/openssl/opensslconf.h
```

but in master a lot of generated pod files (and one cnf file) have been added

```
GENERATED_MANDATORY=doc/man1/openssl-asn1parse.pod doc/man1/openssl-ca.pod \
                    doc/man1/openssl-ciphers.pod doc/man1/openssl-cmds.pod \
                    doc/man1/openssl-cmp.pod doc/man1/openssl-cms.pod \
                    doc/man1/openssl-crl.pod doc/man1/openssl-crl2pkcs7.pod \
                    doc/man1/openssl-dgst.pod doc/man1/openssl-dhparam.pod \
                    doc/man1/openssl-dsa.pod doc/man1/openssl-dsaparam.pod \
                    doc/man1/openssl-ec.pod doc/man1/openssl-ecparam.pod \
                    doc/man1/openssl-enc.pod doc/man1/openssl-engine.pod \
                    doc/man1/openssl-errstr.pod \
                    doc/man1/openssl-fipsinstall.pod \
                    doc/man1/openssl-gendsa.pod doc/man1/openssl-genpkey.pod \
                    doc/man1/openssl-genrsa.pod doc/man1/openssl-info.pod \
                    doc/man1/openssl-kdf.pod doc/man1/openssl-list.pod \
                    doc/man1/openssl-mac.pod doc/man1/openssl-nseq.pod \
                    doc/man1/openssl-ocsp.pod doc/man1/openssl-passwd.pod \
                    doc/man1/openssl-pkcs12.pod doc/man1/openssl-pkcs7.pod \
                    doc/man1/openssl-pkcs8.pod doc/man1/openssl-pkey.pod \
                    doc/man1/openssl-pkeyparam.pod \
                    doc/man1/openssl-pkeyutl.pod doc/man1/openssl-prime.pod \
                    doc/man1/openssl-provider.pod doc/man1/openssl-rand.pod \
                    doc/man1/openssl-rehash.pod doc/man1/openssl-req.pod \
                    doc/man1/openssl-rsa.pod doc/man1/openssl-rsautl.pod \
                    doc/man1/openssl-s_client.pod \
                    doc/man1/openssl-s_server.pod \
                    doc/man1/openssl-s_time.pod doc/man1/openssl-sess_id.pod \
                    doc/man1/openssl-smime.pod doc/man1/openssl-speed.pod \
                    doc/man1/openssl-spkac.pod doc/man1/openssl-srp.pod \
                    doc/man1/openssl-storeutl.pod doc/man1/openssl-ts.pod \
                    doc/man1/openssl-verify.pod doc/man1/openssl-version.pod \
                    doc/man1/openssl-x509.pod \
                    doc/man7/openssl_user_macros.pod \
                    include/crypto/bn_conf.h include/crypto/dso_conf.h \
                    include/openssl/configuration.h \
                    include/openssl/opensslv.h \
                    test/provider_internal_test.cnf
```

Would it be possible to separate those from the generated headers by adding a new kind of dependency like `DEPEND[doc]` `DEPEND[test]` for those?

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/doc/man1/build.info#L2-L56

https://github.com/openssl/openssl/blob/5e5bc836fbc5b1c0af428864f5286bbb225f7baf/test/build.info#L731

**Comment by paulidale** [comment]
Thanks for digging into this.

There are a number of dependency issues in the makefile.  I've not isolated any properly but I am running `make distclean; ./config && make` far too often.  It's a safe but time consuming way to rebuild.

From memory, I've run into problems changing `build.info` files and not doing a distclean rebuild and adding/removing APIs via `make update`.

**Comment by levitte** [comment]
When building a specific file, you must `make build_generated` first.

As for @paulidale's last remark, a simple solution is to run `make` twice. What happens is that in the first run, auto-generated dependencies from the previous run are out of sync, but are regenerated, and the second run has the dependencies in sync again. It's a chicken-and-egg problem, and only happens for devs who change the source a lot :wink:

**Comment by mspncp** [comment]
Ok @levitte, I take your winking eye as a works-for-me, wont-fix. That's fair enough since you provided a viable workaround for impatient devs.

So I took a second look at the main targets:  `make [-j8] build_programs` seems to be a main target which comes close to `make build_generated ; make [-j8] apps/openssl`, and it's easier to remember. However, it still builds a lot of unneeded programs. So I tried to create a make target optimized for building only the openssl application. See #11946 (master) and #11947 (1.1.1).

**Comment by levitte** [comment]
@mspncp, you won't get away from the chicken-and-egg problem, though, and that wink wasn't specifically directed at you.

**Comment by KarimH22** [comment]
hello
I'm facing the issue within 
make libssl.a
all the .a lib are not made depends on build_generated, it is a pity...
I think you can enhance the rule maker to make build_generated always done (.PHONY something like that)

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by t8m** [comment]
Closing as the issue was labeled as inactive for extended period of time and there was no additional input.
Please add a comment if you have any further information to support reopening the issue.
