### ISSUE TITLE
OpenSSL 1.1.1c gives linker error LNK2019 when used with Mongoose 3.7

### ISSUE THREAD

**Issue by ganeshkamath89** [openssl/openssl#9784]
Mongoose 3.7 taken from: https://code.google.com/archive/p/mongoose/
worked well with openssl 1.0.1j implementation.

We want to use the TLS 1.3 support that comes with openssl 1.1.1c which is LTS till 2023.
But, when we moved to the latest openssl 1.1.1c we started getting linker errors.

Unfortunately Mongoose versions after this have a commercial license and we wish to use the free license that came with 3.7.

Upon compiling with the new Openssl, we get the following linker warnings in Visual Studio:
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_new referenced in function _mg_connect
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_free referenced in function _free_context
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_set_fd referenced in function _sslize
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_use_PrivateKey_file referenced in function _set_ssl_option
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_use_certificate_file referenced in function _set_ssl_option
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_use_certificate_chain_file referenced in function _set_ssl_option
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_CTX_set_verify referenced in function _mg_connect
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_new referenced in function _sslize
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_free referenced in function _close_connection
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_accept referenced in function _worker_thread
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_connect referenced in function _mg_connect
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_read referenced in function _pull
1>mongoose.obj : error LNK2019: unresolved external symbol _SSL_write referenced in function _push
1>mongoose.obj : error LNK2019: unresolved external symbol _TLS_server_method referenced in function _set_ssl_option
1>mongoose.obj : error LNK2019: unresolved external symbol _TLS_client_method referenced in function _mg_connect
1>mongoose.obj : error LNK2019: unresolved external symbol _OPENSSL_init_ssl referenced in function _set_ssl_option
1>mongoose.obj : error LNK2019: unresolved external symbol _ERR_get_error referenced in function _ssl_error
1>mongoose.obj : error LNK2019: unresolved external symbol _ERR_error_string referenced in function _ssl_error

Why is openssl not backward compatible. Is there some way using which we could use the new openssl with old Mongoose. 

Request the members of the community to please help with this.

**Comment by levitte** [comment]
1.1.0 was a major release, with quite a number of changes, the most prominent one being that a number of types were made opaque and a set of accessor functions were added.  Depending on what the application does (in this case, mongoose), it may need some rework.

As for the libraries, they were renamed to become more uniform across platforms, so Windows DLLs for the 1.1.x versions are called libcrypto-1_1.dll and libssl-1_1.dll for 32-bit, libcrypto-1_1-x64.dll and libssl-1_1-x64.dll for 64-bit, with the import libraries libcrypto.lib and libssl.lib.  We had to do a name change either way because of the overall API/ABI changes.  Keeping the names libeay32.dll and ssleay32.dll would have brought only an illusion of smooth upgradability, but would only have made old applications start failing, which would have been worse.

**Comment by levitte** [comment]
The mongoose has become non-free later on is regrettable, but nothing we can do much about...

**Comment by ganeshkamath89** [comment]
Hi,
     Thank you for your response.

We are using the libcrypto.lib and libssl.lib that are produced from openssl 1.1.1c.
I am not asking for a name change of the lib files.

I am asking how to resolve the linker errors that are coming because of change in the definitions of different functions that are shown in the linker error.

Is there some kind of interface that is readily available that does the function definition translation to suit the old usage.

**Comment by levitte** [comment]
Function signatures are irrelevant when linking object files coming from C source.  Only the names matter.

Maybe this helps?  At the very least, it may explain why you have a difference in symbol names...
You might want to have a similar look on your end...

```
C:\Users\Richard\Work\_openssl-1.1.1-64>objdump -t libssl.lib | find "SSL_set_fd"
[  3](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_SSL_set_fd
[  5](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 SSL_set_fd
```

I think that a relevant question may be how you built mongoose...  and possibly when?

I'll add that I'm not Windows savvy at this level, so I'll try to figure it out with the knowledge I have or information I can find.  I'm sorry if I offended you.  Can I have your patience?

**Comment by ganeshkamath89** [comment]
Thank you once again. You have given me a good lead. I will update you when I get a success.

**Comment by ganeshkamath89** [comment]
Thank you. our build is now succeeding.

I was getting the problem from copying the wrong lib files in openssl. I was copying the lib files “libapps.lib” and “openssl.lib” from “apps” instead of copying the files “libcrypto.lib” and “libssl.lib” that were generated in the openssl home folder.

**Comment by levitte** [comment]
Oh good. So that mean we can close this issue, right?

**Comment by ganeshkamath89** [comment]
Please close the issue. Thank you :)

**Comment by hamedgibago** [comment]
> 
> 
> Hi,
> Thank you for your response.
> 
> We are using the libcrypto.lib and libssl.lib. We are also using libcrypto-1_1.dll and libssl-1_1.dll files along with that as traditionally we have used 32 bit builds itself after building the source of openssl 1.1.1c.
> 
> I am not asking for a name change of the lib files.
> 
> I am asking how to resolve the linker errors that are coming because of change in the definitions of different functions that are shown in the linker error.
> 
> Is there some kind of interface that is readily available that does the function definition translation to suit the old usage.
> 
> Linker Error LNK 2019 comes when linker is not able to find the function definitions for the following function names:
> 
> > _SSL_CTX_new, _SSL_CTX_free, _SSL_set_fd, _SSL_CTX_use_PrivateKey_file, _SSL_CTX_use_certificate_file, _SSL_CTX_use_certificate_chain_file, _SSL_CTX_set_verify, _SSL_new, _SSL_free, _SSL_accept, _SSL_connect, _SSL_read, _SSL_write, _TLS_server_method, _TLS_client_method, _OPENSSL_init_ssl, _ERR_get_error, _ERR_error_string
> 
> I see that the function names are still present but their signatures, return types have changed, so I am asking if there is some interface or equivalent function that can be substituted in their place to achieve the same output as before.
> 
> Furthermore there might be some pre-processor definition that you might have introduced in this version of openssl, that does the required name matching for the changed functions. I am not aware of the intricasies of openssl, that is why I am asking your help so desperately.

In addition to libcrypto.lib;libssl.lib; for linking, the error for linking
