### ISSUE TITLE
Missing Symbols During Make Test

### ISSUE THREAD

**Issue by talkinggoat** [openssl/openssl#23594]
I have been trying to install OpenSSL from source on AIX, in a custom location, but keep getting an error when running make test:

```
# The following symbols are missing in crypto:
#   ACCESS_DESCRIPTION_free
#   ACCESS_DESCRIPTION_it
#   ACCESS_DESCRIPTION_new
#   ADMISSIONS_free
#   ADMISSIONS_get0_admissionAuthority
#   ADMISSIONS_get0_namingAuthority
#   ADMISSIONS_get0_professionInfos
#   ADMISSIONS_it
#   ADMISSIONS_new
#   ADMISSIONS_set0_admissionAuthority
#   ADMISSIONS_set0_namingAuthority
#   ADMISSIONS_set0_professionInfos
#   ADMISSION_SYNTAX_free
...


not ok 2 - check that there are no missing symbols in crypto
# ------------------------------------------------------------------------------
#   Failed test 'check that there are no missing symbols in crypto'
#   at test/recipes/01-test_symbol_presence.t line 239.
# The following symbols are missing in ssl:
#   BIO_f_ssl
#   BIO_new_buffer_ssl_connect
#   BIO_new_ssl
#   BIO_new_ssl_connect
#   BIO_ssl_copy_session_id
#   BIO_ssl_shutdown
#   DTLS_client_method
#   DTLS_get_data_mtu
#   DTLS_method
#   DTLS_server_method
#   DTLS_set_timer_cb
#   DTLSv1_2_client_method
#   DTLSv1_2_method
#   DTLSv1_2_server_method
...


04-test_bio_core.t ...................... ok

        # INFO:  @ test/bio_dgram_test.c:120
        # # Testing with AF_INET, local=1
        # 
        # ERROR: (bool) 'do_sendmmsg(b1, tx_msg, 2, 0, &num_processed) == true' failed @ test/bio_dgram_test.c:277
        # false
        # 00000001:error:8000003A:system library:dgram_sendmmsg:Destination address required:crypto/bio/bss_dgram.c:1378:
        # 00000001:error:1000006F:BIO routines:dgram_sendmmsg:local address not available:crypto/bio/bss_dgram.c:1361:
        # 00000001:error:1000006F:BIO routines:dgram_sendmmsg:local address not available:crypto/bio/bss_dgram.c:1368:
        # OPENSSL_TEST_RAND_SEED=1707930328
        not ok 3 - iteration 3
# ------------------------------------------------------------------------------
    # OPENSSL_TEST_RAND_SEED=1707930328
    not ok 1 - test_bio_dgram
# ------------------------------------------------------------------------------
../../util/wrap.pl ../../test/bio_dgram_test => 1
not ok 1 - running bio_dgram_test
# ------------------------------------------------------------------------------
#   Failed test 'running bio_dgram_test'
#   at /custom/opt/apache/openssl-3.2.1/util/perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.04-test_bio_dgram.t ..................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
...


Test Summary Report
-------------------
01-test_symbol_presence.t             (Wstat: 512 (exited 2) Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
04-test_bio_dgram.t                   (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=298, Tests=3580, 927 wallclock secs ( 6.07 usr  0.83 sys + 416.14 cusr 78.16 csys = 501.20 CPU)
Result: FAIL
make: The error code from the last command is 1.


Stop.
make: The error code from the last command is 2.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.

```

```
perl configdata.pm --dump

 

Command line (with current working directory = .):

 

    perl ./Configure --prefix=/custom/opt/apache/openssl --openssldir=/custom/opt/apache/openssl LDFLAGS=-maix64 -Wl,-bbigtoc shared aix64-gcc

 

Perl information:

 

    perl

    5.38.0 for ppc-aix-thread-multi-64all

 

Enabled features:

 

    apps

    argon2

    aria

    asm

    async

    autoalginit

    autoerrinit

    autoload-config

    bf

    blake2

    bulk

    cached-fetch

    camellia

    capieng

    cast

    chacha

    cmac

    cmp

    cms

    comp

    ct

    default-thread-pool

    deprecated

    des

    dgram

    dh

    docs

    dsa

    dso

    dtls

    dynamic-engine

    ec

    ec2m

    ecdh

    ecdsa

    ecx

    engine

    err

    filenames

    gost

    http

    idea

    legacy

    loadereng

    makedepend

    md4

    mdc2

    module

    multiblock

    nextprotoneg

    ocb

    ocsp

    padlockeng

    pic

    pinshared

    poly1305

    posix-io

    psk

    quic

    rc2

    rc4

    rdrand

    rfc3779

    rmd160

    scrypt

    secure-memory

    seed

    shared

    siphash

    siv

    sm2

    sm2-precomp

    sm3

    sm4

    sock

    srp

    srtp

    sse2

    ssl

    ssl-trace

    static-engine

    stdio

    tests

    thread-pool

    threads

    tls

    ts

    ui-console

    whirlpool

    tls1

    tls1-method

    tls1_1

    tls1_1-method

    tls1_2

    tls1_2-method

    tls1_3

    dtls1

    dtls1-method

    dtls1_2

    dtls1_2-method

 

Disabled features:

 

    acvp-tests          [cascade]        OPENSSL_NO_ACVP_TESTS

    afalgeng            [not-linux]      OPENSSL_NO_AFALGENG

    asan                [default]        OPENSSL_NO_ASAN

    brotli              [default]        OPENSSL_NO_BROTLI

    brotli-dynamic      [default]        OPENSSL_NO_BROTLI_DYNAMIC

    buildtest-c++       [default]       

    winstore            [not-windows]    OPENSSL_NO_WINSTORE

    crypto-mdebug       [default]        OPENSSL_NO_CRYPTO_MDEBUG

    devcryptoeng        [default]        OPENSSL_NO_DEVCRYPTOENG

    ec_nistp_64_gcc_128 [default]        OPENSSL_NO_EC_NISTP_64_GCC_128

    egd                 [default]        OPENSSL_NO_EGD

    external-tests      [default]        OPENSSL_NO_EXTERNAL_TESTS

    fips                [default]       

    fips-securitychecks [cascade]        OPENSSL_NO_FIPS_SECURITYCHECKS

    fuzz-afl            [default]        OPENSSL_NO_FUZZ_AFL

    fuzz-libfuzzer      [default]        OPENSSL_NO_FUZZ_LIBFUZZER

    ktls                [default]        OPENSSL_NO_KTLS

    md2                 [default]        OPENSSL_NO_MD2 (skip crypto/md2)

    msan                [default]        OPENSSL_NO_MSAN

    rc5                 [default]        OPENSSL_NO_RC5 (skip crypto/rc5)

    sctp                [default]        OPENSSL_NO_SCTP

    tfo                 [default]        OPENSSL_NO_TFO

    trace               [default]        OPENSSL_NO_TRACE

    ubsan               [default]        OPENSSL_NO_UBSAN

    unit-test           [default]        OPENSSL_NO_UNIT_TEST

    uplink              [no uplink_arch] OPENSSL_NO_UPLINK

    weak-ssl-ciphers    [default]        OPENSSL_NO_WEAK_SSL_CIPHERS

    zlib                [default]        OPENSSL_NO_ZLIB

    zlib-dynamic        [default]        OPENSSL_NO_ZLIB_DYNAMIC

    zstd                [default]        OPENSSL_NO_ZSTD

    zstd-dynamic        [default]        OPENSSL_NO_ZSTD_DYNAMIC

    ssl3                [default]        OPENSSL_NO_SSL3

    ssl3-method         [default]        OPENSSL_NO_SSL3_METHOD

 

Config target attributes:

 

    AR => "ar -X64",

    ARFLAGS => "qc",

    CC => "gcc",

    CFLAGS => "-O",

    HASHBANGPERL => "/usr/bin/env perl",

    RANLIB => "ranlib -X64",

    RC => "windres",

    asm_arch => "ppc64",

    bn_ops => "SIXTY_FOUR_BIT_LONG RC4_CHAR",

    build_file => "Makefile",

    build_scheme => [ "unified", "unix" ],

    cflags => "-maix64 -pthread",

    cppflags => "",

    defines => [ "OPENSSL_BUILDING_OPENSSL" ],

    disable => [  ],

    dso_scheme => "dlfcn",

    enable => [  ],

    ex_libs => "-pthread",

    includes => [  ],

    lflags => "-Wl,-bsvr4",

    lib_cflags => "",

    lib_cppflags => "-DB_ENDIAN",

    lib_defines => [  ],

    module_cflags => "",

    module_cxxflags => undef,

    module_ldflags => "-Wl,-G,-bsymbolic,-bnoentry",

    perl_platform => "AIX",

    perlasm_scheme => "aix64",

    shared_cflag => "",

    shared_defflag => "-Wl,-bE:",

    shared_defines => [  ],

    shared_extension => "64.so.\$(SHLIB_VERSION_NUMBER)",

    shared_fipsflag => "-Wl,-binitfini:_init:_cleanup",

    shared_ldflag => "-shared -static-libgcc -Wl,-G,-bsymbolic,-bnoentry",

    shared_rcflag => "",

    shared_target => "aix",

    sys_id => "AIX",

    thread_defines => [  ],

    thread_scheme => "pthreads",

    unistd => "<unistd.h>",

 

Recorded environment:

 

    AR =

    ARFLAGS =

    AS =

    ASFLAGS =

    BUILDFILE =

    CC =

    CFLAGS = -m64

    CPP =

    CPPDEFINES =

    CPPFLAGS =

    CPPINCLUDES =

    CROSS_COMPILE =

    CXX =

    CXXFLAGS =

    HASHBANGPERL =

    LD =

    LDFLAGS =

    LDLIBS =

    MT =

    MTFLAGS =

    OPENSSL_LOCAL_CONFIG_DIR =

    PERL =

    RANLIB =

    RC =

    RCFLAGS =

    RM =

    WINDRES =

    __CNF_CFLAGS =

    __CNF_CPPDEFINES =

    __CNF_CPPFLAGS =

    __CNF_CPPINCLUDES =

    __CNF_CXXFLAGS =

    __CNF_LDFLAGS =

    __CNF_LDLIBS =

 

Makevars:

 

    AR              = ar -X64

    ARFLAGS         = qc

    ASFLAGS         =

    CC              = gcc

    CFLAGS          = -m64

    CPPDEFINES      =

    CPPFLAGS        =

    CPPINCLUDES     =

    CXXFLAGS        =

    HASHBANGPERL    = /usr/bin/env perl

    LDFLAGS         = -maix64 -Wl,-bbigtoc

    LDLIBS          =

    PERL            = perl

    RANLIB          = ranlib -X64

    RC              = windres

    RCFLAGS         =

 

NOTE: These variables only represent the configuration view.  The build file

template may have processed these variables further, please have a look at the

build file for more exact data:

    Makefile

 

build file:

 

    Makefile

 

build file templates:

 

    Configurations/common0.tmpl

    Configurations/unix-Makefile.tmpl
```

Thanks for any help!

**Comment by mattcaswell** [comment]
What version of OpenSSL is this?

What do you get when you run `nm -Dpg` and pass the name of the libcrypto or libssl shared object? On my Linux machine I get output like this:

````
$ nm -Dpg libcrypto.so
                 U chmod@GLIBC_2.2.5
                 U tcsetattr@GLIBC_2.2.5
                 U mprotect@GLIBC_2.2.5
                 U fileno@GLIBC_2.2.5
                 U pthread_join@GLIBC_2.34
                 U pthread_cond_destroy@GLIBC_2.3.2
                 U dlerror@GLIBC_2.34
                 U mktime@GLIBC_2.2.5
                 U memset@GLIBC_2.2.5
                 U ftell@GLIBC_2.2.5
                 U shutdown@GLIBC_2.2.5
...snip...
0000000000211ead T OSSL_ENCODER_do_all_provided@@OPENSSL_3.0.0
000000000026bc56 T EVP_PKEY_get_int_param@@OPENSSL_3.0.0
000000000042a516 T X509_REVOKED_get_ext_by_critical@@OPENSSL_3.0.0
000000000010375d T BIO_meth_get_puts@@OPENSSL_3.0.0
0000000000220a5b T ESS_CERT_ID_V2_dup@@OPENSSL_3.0.0
00000000000ecfba T ASN1_item_ex_d2i@@OPENSSL_3.0.0
00000000001998f4 T DH_security_bits@@OPENSSL_3.0.0
000000000041e029 T X509_PURPOSE_get_count@@OPENSSL_3.0.0
00000000003a10b4 T i2d_RSAPublicKey@@OPENSSL_3.0.0
0000000000128ce6 T BN_mod_lshift1@@OPENSSL_3.0.0
00000000003fd253 T UI_method_set_data_duplicator@@OPENSSL_3.0.0
0000000000415f18 T DIST_POINT_NAME_new@@OPENSSL_3.0.0
0000000000245af5 T EVP_des_ecb@@OPENSSL_3.0.0
...snip...
````

If the output format is somehow different then that might confuse the test. Unfortunately AIX is an unadopted platform as per our platform policy, so we have no maintainer for it. It might be that we just need to skip this test on this platform.

My guess is the dgram test failure is something different.

**Comment by talkinggoat** [comment]
OpenSSL 3.2.1
The AIX nm command doesn't have a -D flag, so that might be a problem if it relies on the Linux version of the command.

I don't see the variant I'm trying to compile creating any of the .so files, either. Maybe I'm throwing it the wrong configuration flags, as well?

**Comment by t8m** [comment]
I think we could just skip the test on AIX.

**Comment by Enc-EE** [comment]
I have the same problem on nmake test

Also noticed a warning during nmake:
```
crypto/bio/bss_dgram.c: In function 'dgram_sendmmsg':
crypto/bio/bss_dgram.c:1394:11: warning: implicit declaration of function 'sendmmsg'; did you mean 'sendmsg'? [-Wimplicit-function-declaration]
 1394 |     ret = sendmmsg(b->num, mh, num_msg, sysflags);
      |           ^~~~~~~~
      |           sendmsg
crypto/bio/bss_dgram.c: In function 'dgram_recvmmsg':
crypto/bio/bss_dgram.c:1587:11: warning: implicit declaration of function 'recvmmsg'; did you mean 'recvmsg'? [-Wimplicit-function-declaration]
 1587 |     ret = recvmmsg(b->num, mh, num_msg, sysflags, NULL);
      |           ^~~~~~~~
      |           recvmsg
```
This warning and the failing test both refer to the sendmmsg method.

Sure this can be ignored?

I don't have linking errors like in #23751 

I'm using AIX 7.3 and Building OpenSSL 3.3.2 with gcc 11.2.0

**Comment by mattcaswell** [comment]
> Also noticed a warning during nmake:

This warning looks like a different problem to this issue. Can you raise a new issue?

**Comment by makr73** [comment]
The failing `test_symbol_presence` has been fixed with #29276.
