### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#11987]
Travis in master is failing with:
```
test/ossl_shim/ossl_shim.cc: In function 'int bssl::TicketKeyCallback(SSL*, uint8_t*, uint8_t*, EVP_CIPHER_CTX*, EVP_MAC_CTX*, int)':
test/ossl_shim/ossl_shim.cc:396:43: error: 'OSSL_MAC_PARAM_DIGEST' was not declared in this scope
   *p++ = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST, "SHA256", 0);
                                           ^~~~~~~~~~~~~~~~~~~~~
test/ossl_shim/ossl_shim.cc:396:43: note: suggested alternative: 'OSSL_PARAM_DEFN'
   *p++ = OSSL_PARAM_construct_utf8_string(OSSL_MAC_PARAM_DIGEST, "SHA256", 0);
                                           ^~~~~~~~~~~~~~~~~~~~~
                                           OSSL_PARAM_DEFN
test/ossl_shim/ossl_shim.cc:397:44: error: 'OSSL_MAC_PARAM_KEY' was not declared in this scope
   *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_KEY, kZeros,
                                            ^~~~~~~~~~~~~~~~~~
test/ossl_shim/ossl_shim.cc:397:44: note: suggested alternative: 'OSSL_PARAM_BLD'
   *p++ = OSSL_PARAM_construct_octet_string(OSSL_MAC_PARAM_KEY, kZeros,
                                            ^~~~~~~~~~~~~~~~~~
                                            OSSL_PARAM_BLD
Makefile:27670: recipe for target 'test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o' failed
make[1]: *** [test/ossl_shim/ossl_shim-bin-ossl_shim_cc.o] Error 1
```

**Comment by bernd-edlinger** [comment]
@paulidale this is caused by bac8d066a595454e3f4a75e6e155a9d5b99ce4ea

**Comment by paulidale** [comment]
This slipped passed me unfortunately.
