### ISSUE TITLE
no-dh no-ec doesn't build

### ISSUE THREAD

**Issue by traud** [openssl/openssl#6306]
Fails in OpenSSL 1.1.1-pre6 and -pre7-dev (GitHub master/trunk as of today). Works in OpenSSL 1.1.0h and 1.0.2o. Just `no-dh` or just `no-ec` works. It is the combination of the two, which does not build with the following console output:
```c
clang  -I. -Iinclude -fPIC -pthread -m64 -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF ssl/statem/statem_clnt.d.tmp -MT ssl/statem/statem_clnt.o -c -o ssl/statem/statem_clnt.o ssl/statem/statem_clnt.c
ssl/statem/extensions_srvr.c:830:28: error: no member named 'group_id' in 'struct ssl3_state_st'
    if (group_id != s->s3->group_id
                    ~~~~~  ^
ssl/statem/extensions_srvr.c:905:59: error: no member named 'group_id' in 'struct ssl3_state_st'
                || !WPACKET_put_bytes_u16(&hrrpkt, s->s3->group_id)
                                                   ~~~~~  ^
ssl/statem/../packet_locl.h:824:33: note: expanded from macro 'WPACKET_put_bytes_u16'
    WPACKET_put_bytes__((pkt), (val), 2)
                                ^~~
ssl/statem/extensions_srvr.c:1719:51: error: no member named 'group_id' in 'struct ssl3_state_st'
            || !WPACKET_put_bytes_u16(pkt, s->s3->group_id)
                                           ~~~~~  ^
ssl/statem/../packet_locl.h:824:33: note: expanded from macro 'WPACKET_put_bytes_u16'
    WPACKET_put_bytes__((pkt), (val), 2)
                                ^~~
ssl/statem/extensions_srvr.c:1723:50: error: no member named 'peer_tmp' in 'struct ssl3_state_st'
            || !WPACKET_put_bytes_u8(pkt, s->s3->peer_tmp == NULL)
                                          ~~~~~  ^
ssl/statem/../packet_locl.h:822:33: note: expanded from macro 'WPACKET_put_bytes_u8'
    WPACKET_put_bytes__((pkt), (val), 1)
                                ^~~
4 errors generated.
```
I am on Ubuntu 18.04 LTS and used
`$ sudo apt install clang`
`$ CC=clang CXX=clang++ ./config shared no-dh no-ec no-deprecated`
`$ make`
I tried this combination, to test whether a downstream app uses the compile guards correctly.

**Comment by richsalz** [comment]
I believe this is fixed in master; can you check?

**Comment by mspncp** [comment]
He checked it in master

> Fails in OpenSSL 1.1.1-pre6 and -pre7-dev (GitHub master/trunk as of today).

**Comment by richsalz** [comment]
Oh sorry, missed that.  It looks like no-ec needs to imply no-tls13.

**Comment by traud** [comment]
`CC=clang CXX=clang++ ./config shared no-dh no-ec no-tls1_3 no-deprecated`
reduces the errors, yes. However, just by half. Still, I get two errors.

**Comment by mattcaswell** [comment]
Fixed by commit 1aac20f50. Closing.

**Comment by traud** [comment]
Thank you. Although from the commit, I do not understand why it works now (where this ‘no-ec implies no-tls1_3’ is coming from). Anyway, it works!

**Comment by mattcaswell** [comment]
> where this ‘no-ec implies no-tls1_3’ is coming from

Its part of Configure. There is a table of disablable "cascades", i.e. removing option X implies removing option Y. Here is the line for ec -> tlsv1.3:

https://github.com/openssl/openssl/blob/master/Configure#L493
