### ISSUE TITLE
threadstest.c in openssl-3.0 no longer compiles after commit f9f3096fd26ade6c188ae878a627920c0ddbd803

### ISSUE THREAD

**Issue by markhermeling** [openssl/openssl#18455]
Compile error:
test/threadstest.c: In function 'test_lib_ctx_load_config':
test/threadstest.c:566:12: warning: implicit declaration of function 'thread_run_test'; did you mean 'thread_run'? [-Wimplicit-function-declaration]
  566 |     return thread_run_test(&test_lib_ctx_load_config_worker,
      |            ^~~~~~~~~~~~~~~
      |            thread_run
test/threadstest.c:567:28: error: 'MAXIMUM_THREADS' undeclared (first use in this function)
  567 |                            MAXIMUM_THREADS, &test_lib_ctx_load_config_worker,
      |                            ^~~~~~~~~~~~~~~
test/threadstest.c:567:28: note: each undeclared identifier is reported only once for each function it appears in
test/threadstest.c:568:31: error: 'default_provider' undeclared (first use in this function); did you mean 'opt_provider'?
  568 |                            1, default_provider);
      |                               ^~~~~~~~~~~~~~~~
      |                               opt_provider
test/threadstest.c:569:1: warning: control reaches end of non-void function [-Wreturn-type]
  569 | }
      | ^

I think the cherry picked merge partially from a different branch missed the 
#define MAXIMUM_THREADS 10 
from the beginning of threadstest.c

**Comment by t8m** [comment]
Fixed by #18451
